import Foundation

/// App-owned Pi extension for the safety-gated macOS desktop harness.
///
/// It is installed with the other app-owned extensions but ChatSession only mounts it
/// when the independent opt-in setting is enabled.
enum ComputerUseExtension {
    static func install(into dir: URL) -> String? {
        let file = dir.appendingPathComponent("pipiui-computer-use.ts")
        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try source.write(to: file, atomically: true, encoding: .utf8)
            return file.path
        } catch {
            return nil
        }
    }

    static let source = #"""
// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Custom batch computer tool for all providers; Anthropic messages receives only
// the official computer_20251124 wire shape. OpenAI native computer_call is not used.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { randomUUID } from "node:crypto";

const PORT = process.env.PIPIUI_BRIDGE_PORT;
const CAPABILITY = process.env.PIPIUI_SESSION_KEY;
const COMPUTER_CAPABILITY = process.env.PIPIUI_COMPUTER_CAPABILITY;
const DISPLAY_ID = Number.parseInt(process.env.PIPIUI_COMPUTER_DISPLAY_ID || "", 10);
const DISPLAY_WIDTH = Number.parseInt(process.env.PIPIUI_COMPUTER_WIDTH || "1440", 10);
const DISPLAY_HEIGHT = Number.parseInt(process.env.PIPIUI_COMPUTER_HEIGHT || "900", 10);
const REQUEST_TIMEOUT_MS = 35_000;
const CANCEL_TIMEOUT_MS = 1_500;
const MAX_IN_MEMORY_SCREENSHOTS = 12;
const SCREENSHOT_MARKER = "PIPIUI_COMPUTER_SCREENSHOT";

const screenshots = new Map<string, {
  data: string;
  mimeType: string;
}>();

const ActionSchema = Type.Object({
  type: Type.String({
    description:
      "screenshot | mouse_move | click | left_click | right_click | middle_click | " +
      "double_click | triple_click | left_mouse_down | left_mouse_up | drag | " +
      "left_click_drag | type | key | keypress | hold_key | scroll | wait",
  }),
  coordinate: Type.Optional(Type.Tuple([Type.Number(), Type.Number()])),
  x: Type.Optional(Type.Number()),
  y: Type.Optional(Type.Number()),
  start_coordinate: Type.Optional(Type.Tuple([Type.Number(), Type.Number()])),
  text: Type.Optional(Type.String()),
  keys: Type.Optional(Type.Array(Type.String())),
  scroll_direction: Type.Optional(Type.String()),
  scroll_amount: Type.Optional(Type.Number()),
  duration: Type.Optional(Type.Number()),
  duration_ms: Type.Optional(Type.Number()),
});

type ComputerAction = {
  type?: string;
  action?: string;
  [key: string]: unknown;
};

export function normalizeActions(params: {
  actions?: ComputerAction[];
  action?: string;
  [key: string]: unknown;
}): ComputerAction[] {
  if (Array.isArray(params.actions)) return params.actions;
  if (typeof params.action === "string") {
    // Anthropic's official typed tool sends one action at the top level.
    return [{ ...params, type: params.action }];
  }
  return [];
}

async function bridge(actions: ComputerAction[]): Promise<any> {
  const requestID = randomUUID();
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
  try {
    const response = await fetch(`http://127.0.0.1:${PORT}/rpc`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      signal: controller.signal,
      body: JSON.stringify({
        sessionKey: CAPABILITY,
        computerCapability: COMPUTER_CAPABILITY,
        action: "computer_batch",
        requestID,
        displayID: DISPLAY_ID,
        displayWidth: DISPLAY_WIDTH,
        displayHeight: DISPLAY_HEIGHT,
        actions,
      }),
    });
    const json: any = await response.json();
    if (!json.ok) throw new Error(json.error || "computer bridge request failed");
    return json;
  } catch (error: any) {
    if (controller.signal.aborted) {
      await cancelBridgeRequest(requestID);
      throw new Error("computer request timed out and was cancelled");
    }
    throw error;
  } finally {
    clearTimeout(timer);
  }
}

async function cancelBridgeRequest(requestID: string): Promise<void> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), CANCEL_TIMEOUT_MS);
  try {
    await fetch(`http://127.0.0.1:${PORT}/rpc`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      signal: controller.signal,
      body: JSON.stringify({
        sessionKey: CAPABILITY,
        computerCapability: COMPUTER_CAPABILITY,
        action: "computer_cancel",
        requestID,
      }),
    });
  } catch {
    // The Swift bridge also has a disconnect/timeout cancellation watchdog.
  } finally {
    clearTimeout(timer);
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const ANTHROPIC_20251124_MODEL_PREFIXES = [
  "claude-sonnet-5",
  "claude-opus-4-8",
  "claude-opus-4-7",
  "claude-opus-4-6",
  "claude-sonnet-4-6",
  "claude-opus-4-5",
] as const;

export function isAnthropicComputer20251124Model(
  model: { provider?: string; api?: string; id?: string } | undefined,
): boolean {
  if (!model || model.api !== "anthropic-messages") return false;
  const provider = (model.provider || "").toLowerCase();
  const id = (model.id || "").toLowerCase();
  if (provider !== "anthropic" || !id) return false;
  return ANTHROPIC_20251124_MODEL_PREFIXES.some(
    (prefix) => id === prefix || id.startsWith(`${prefix}-`),
  );
}

function anthropicComputerTool() {
  return {
    type: "computer_20251124",
    name: "computer",
    display_width_px: DISPLAY_WIDTH,
    display_height_px: DISPLAY_HEIGHT,
  };
}

export function replaceComputerTool(tools: unknown): unknown {
  if (!Array.isArray(tools)) return tools;
  return tools.map((tool) => {
    if (!isRecord(tool) || tool.name !== "computer") return tool;
    return anthropicComputerTool();
  });
}

export function mergeBeta(existing: unknown, required: string): string {
  const values = typeof existing === "string"
    ? existing.split(",").map((value) => value.trim()).filter(Boolean)
    : [];
  if (!values.includes(required)) values.push(required);
  return values.join(",");
}

export function retainScreenshot(data: string, mimeType: string): string {
  const id = randomUUID();
  screenshots.set(id, { data, mimeType });
  while (screenshots.size > MAX_IN_MEMORY_SCREENSHOTS) {
    const oldest = screenshots.keys().next().value;
    if (!oldest) break;
    screenshots.delete(oldest);
  }
  return id;
}

function screenshotIDs(content: unknown): string[] {
  if (!Array.isArray(content)) return [];
  const ids: string[] = [];
  const pattern = new RegExp(`\\[${SCREENSHOT_MARKER}:([a-f0-9-]+)\\]`, "g");
  for (const block of content) {
    if (!isRecord(block) || block.type !== "text" || typeof block.text !== "string") continue;
    for (const match of block.text.matchAll(pattern)) ids.push(match[1]);
  }
  return ids;
}

export function injectInMemoryScreenshots(messages: any[]): any[] {
  return messages.map((message) => {
    if (!isRecord(message) || message.role !== "toolResult") return message;
    const ids = screenshotIDs(message.content);
    if (ids.length === 0) return message;
    const images = ids.flatMap((id) => {
      const screenshot = screenshots.get(id);
      return screenshot
        ? [{ type: "image", data: screenshot.data, mimeType: screenshot.mimeType }]
        : [];
    });
    return images.length > 0
      ? { ...message, content: [...(message.content as any[]), ...images] }
      : message;
  });
}

export default function (pi: ExtensionAPI) {
  if (
    !PORT || !CAPABILITY || !COMPUTER_CAPABILITY
    || !Number.isInteger(DISPLAY_ID)
    || !Number.isInteger(DISPLAY_WIDTH)
    || !Number.isInteger(DISPLAY_HEIGHT)
  ) return;

  pi.registerTool({
    name: "computer",
    label: "Computer",
    description:
      "Operate one explicitly authorized macOS app through the PipiUI desktop harness. " +
      "Prefer actions:[...] batches; every accepted batch returns a fresh screenshot. " +
      "Use browser for local/web UI whenever possible. Never use for passwords, terminals, " +
      "payments, publishing, deletion, authentication, or unattended destructive work.",
    // `action` plus single-action fields remain optional so Anthropic's official
    // schema can dispatch into the same executor after the provider-side replacement.
    parameters: Type.Object({
      actions: Type.Optional(Type.Array(ActionSchema, {
        description: "Ordered batch of desktop actions (preferred for custom providers).",
        maxItems: 12,
      })),
      action: Type.Optional(Type.String()),
      coordinate: Type.Optional(Type.Tuple([Type.Number(), Type.Number()])),
      x: Type.Optional(Type.Number()),
      y: Type.Optional(Type.Number()),
      start_coordinate: Type.Optional(Type.Tuple([Type.Number(), Type.Number()])),
      text: Type.Optional(Type.String()),
      keys: Type.Optional(Type.Array(Type.String())),
      scroll_direction: Type.Optional(Type.String()),
      scroll_amount: Type.Optional(Type.Number()),
      duration: Type.Optional(Type.Number()),
      duration_ms: Type.Optional(Type.Number()),
    }),
    async execute(_id, params) {
      const actions = normalizeActions(params as any);
      if (actions.length === 0) {
        throw new Error("computer requires a non-empty actions batch or Anthropic action");
      }
      const result = await bridge(actions);
      const metadata = {
        batchOK: result.batchOK,
        outcomes: result.outcomes,
        foregroundApp: result.foregroundApp,
        windowTitle: result.windowTitle,
        displayID: result.displayID,
        width: result.width,
        height: result.height,
        focusDrift: result.focusDrift,
        ...(result.batchError ? { batchError: result.batchError } : {}),
      };
      const screenshotID = retainScreenshot(
        result.base64,
        result.mimeType || "image/png",
      );
      return {
        content: [
          {
            type: "text" as const,
            text:
              `${JSON.stringify(metadata, null, 2)}\n` +
              `[${SCREENSHOT_MARKER}:${screenshotID}]`,
          },
        ],
        details: metadata,
      };
    },
  });

  // Pi persists toolResult messages to JSONL. Keep only an opaque marker in agent
  // state/session history, then inject the PNG into the cloned provider context.
  // This gives every provider a normal image tool result without writing screenshot
  // bytes to disk. Markers from a restarted session simply have no in-memory image.
  pi.on("context", (event) => ({
    messages: injectInMemoryScreenshots(event.messages as any[]),
  }));

  pi.on("before_provider_request", (event, ctx) => {
    if (
      !isAnthropicComputer20251124Model(ctx.model)
      || !isRecord(event.payload)
    ) return;
    const payload = event.payload as Record<string, unknown>;
    return {
      ...payload,
      tools: replaceComputerTool(payload.tools),
    };
  });

  pi.on("before_provider_headers", (event, ctx) => {
    if (!isAnthropicComputer20251124Model(ctx.model)) return;
    const existingKey = Object.keys(event.headers).find(
      (key) => key.toLowerCase() === "anthropic-beta",
    );
    const key = existingKey || "anthropic-beta";
    event.headers[key] = mergeBeta(
      event.headers[key],
      "computer-use-2025-11-24",
    );
  });
}
"""#
}
