import Foundation

/// Pi extension: structured `git_status` / `git_diff` tools + system-prompt git snapshot.
/// Written to Application Support at launch and loaded via `pi -e <path>`.
enum GitExtension {
    static func install(into dir: URL) -> String? {
        let file = dir.appendingPathComponent("pipiui-git.ts")
        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try source.write(to: file, atomically: true, encoding: .utf8)
            return file.path
        } catch {
            return nil
        }
    }

    private static let source = #"""
// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Structured git tools for the agent: status + capped diff. No shell strings — argv only.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { spawnSync } from "node:child_process";

const DIFF_MAX_BYTES = 80_000;
const MARKER = "## Git (Pipi UI)";

function runGit(args: string[], cwd: string): {
  ok: boolean;
  stdout: string;
  stderr: string;
  code: number;
} {
  const r = spawnSync("git", args, {
    cwd,
    encoding: "utf8",
    maxBuffer: 2 * 1024 * 1024,
    env: process.env,
  });
  const code = typeof r.status === "number" ? r.status : 1;
  return {
    ok: code === 0 && !r.error,
    stdout: typeof r.stdout === "string" ? r.stdout : "",
    stderr:
      (typeof r.stderr === "string" ? r.stderr : "") ||
      (r.error ? String(r.error.message || r.error) : ""),
    code,
  };
}

function text(t: string, isError = false) {
  return {
    content: [{ type: "text" as const, text: t }],
    details: {},
    ...(isError ? { isError: true } : {}),
  };
}

function truncateBytes(s: string, maxBytes: number): { text: string; truncated: boolean } {
  const buf = Buffer.from(s, "utf8");
  if (buf.length <= maxBytes) return { text: s, truncated: false };
  let cut = s.slice(0, maxBytes);
  const nl = cut.lastIndexOf("\n");
  if (nl > 0) cut = cut.slice(0, nl);
  return {
    text: cut + `\n\n[truncated at ${maxBytes} bytes]`,
    truncated: true,
  };
}

function parsePorcelain(output: string): {
  staged: number;
  unstaged: number;
  untracked: number;
} {
  let staged = 0;
  let unstaged = 0;
  let untracked = 0;
  for (const line of output.split(/\r?\n/)) {
    if (line.length < 2) continue;
    const x = line[0];
    const y = line[1];
    if (x === "?" && y === "?") {
      untracked += 1;
      continue;
    }
    if (x === "?" || y === "?") continue;
    if (x !== " ") staged += 1;
    if (y !== " ") unstaged += 1;
  }
  return { staged, unstaged, untracked };
}

function buildSnapshot(cwd: string): string {
  const inside = runGit(["rev-parse", "--is-inside-work-tree"], cwd);
  if (!inside.ok || inside.stdout.trim() !== "true") {
    return `${MARKER}\nnot a git repository`;
  }

  const lines: string[] = [MARKER];
  const abbrev = runGit(["rev-parse", "--abbrev-ref", "HEAD"], cwd);
  const sha = runGit(["rev-parse", "--short", "HEAD"], cwd);
  const branch = abbrev.ok ? abbrev.stdout.trim() : "";
  const shortSha = sha.ok ? sha.stdout.trim() : "";

  if (branch === "HEAD") {
    lines.push(`branch: (detached) @ ${shortSha || "?"}`);
  } else {
    lines.push(`branch: ${branch || "unknown"}`);
  }
  if (shortSha) lines.push(`sha: ${shortSha}`);

  const porcelain = runGit(["status", "--porcelain"], cwd);
  const counts = porcelain.ok
    ? parsePorcelain(porcelain.stdout)
    : { staged: 0, unstaged: 0, untracked: 0 };
  const dirty = counts.staged + counts.unstaged + counts.untracked > 0;
  lines.push(
    `dirty: ${dirty ? "yes" : "no"} (staged=${counts.staged} unstaged=${counts.unstaged} untracked=${counts.untracked})`,
  );

  const up = runGit(
    ["rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{upstream}"],
    cwd,
  );
  if (up.ok && up.stdout.trim()) {
    const name = up.stdout.trim();
    const lr = runGit(["rev-list", "--left-right", "--count", "@{upstream}...HEAD"], cwd);
    let behind = 0;
    let ahead = 0;
    if (lr.ok) {
      const parts = lr.stdout.trim().split(/\s+/);
      if (parts.length >= 2) {
        behind = parseInt(parts[0], 10) || 0;
        ahead = parseInt(parts[1], 10) || 0;
      }
    }
    lines.push(`upstream: ${name} +${ahead} -${behind}`);
  } else {
    lines.push("upstream: (none)");
  }

  const origin = runGit(["remote", "get-url", "origin"], cwd);
  if (origin.ok && origin.stdout.trim()) {
    lines.push(`origin: ${origin.stdout.trim()}`);
  }

  lines.push(
    "Tool: git (action: status | diff | help). Prefer it over raw shell git when summarizing.",
  );
  return lines.join("\n");
}

// Full parameter docs are delivered as a tool result (action "help") rather than carried in
// the schema on every request. See docs/progressive-disclosure.md.
const GIT_HELP = [
  "git actions:",
  "",
  "status                 Branch, SHA, dirty counts (staged/unstaged/untracked), upstream",
  "                       ahead/behind, origin URL, and the porcelain lines.",
  "diff {staged?, path?}  Working-tree diff via `git diff HEAD` (falls back to `git diff`).",
  "                       staged=true uses `--cached`. path limits to one pathspec and must",
  "                       not start with '-'. Output is capped at ~80KB with a truncation note.",
  "help                   This text.",
].join("\n");

function gitStatus() {
  const cwd = process.cwd();
  const inside = runGit(["rev-parse", "--is-inside-work-tree"], cwd);
  if (!inside.ok || inside.stdout.trim() !== "true") {
    return text("not a git repository", true);
  }

  const parts: string[] = [];
  const branch = runGit(["rev-parse", "--abbrev-ref", "HEAD"], cwd);
  const sha = runGit(["rev-parse", "--short", "HEAD"], cwd);
  if (branch.ok) parts.push(`branch: ${branch.stdout.trim()}`);
  if (sha.ok) parts.push(`sha: ${sha.stdout.trim()}`);

  const porcelain = runGit(["status", "--porcelain"], cwd);
  if (!porcelain.ok) {
    return text(`git status failed: ${porcelain.stderr || porcelain.code}`, true);
  }
  const counts = parsePorcelain(porcelain.stdout);
  const dirty = counts.staged + counts.unstaged + counts.untracked > 0;
  parts.push(
    `dirty: ${dirty ? "yes" : "no"} (staged=${counts.staged} unstaged=${counts.unstaged} untracked=${counts.untracked})`,
  );

  const up = runGit(
    ["rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{upstream}"],
    cwd,
  );
  if (up.ok && up.stdout.trim()) {
    const lr = runGit(["rev-list", "--left-right", "--count", "@{upstream}...HEAD"], cwd);
    let behind = 0;
    let ahead = 0;
    if (lr.ok) {
      const p = lr.stdout.trim().split(/\s+/);
      if (p.length >= 2) {
        behind = parseInt(p[0], 10) || 0;
        ahead = parseInt(p[1], 10) || 0;
      }
    }
    parts.push(`upstream: ${up.stdout.trim()} +${ahead} -${behind}`);
  } else {
    parts.push("upstream: (none)");
  }

  const origin = runGit(["remote", "get-url", "origin"], cwd);
  if (origin.ok && origin.stdout.trim()) {
    parts.push(`origin: ${origin.stdout.trim()}`);
  }

  parts.push("");
  parts.push("## porcelain");
  const body = porcelain.stdout.trimEnd();
  parts.push(body.length ? body : "(clean)");

  return text(parts.join("\n"));
}

function gitDiff(params: { staged?: boolean; path?: string }) {
  const cwd = process.cwd();
  const inside = runGit(["rev-parse", "--is-inside-work-tree"], cwd);
  if (!inside.ok || inside.stdout.trim() !== "true") {
    return text("not a git repository", true);
  }

  const staged = !!params.staged;
  const pathSpec =
    typeof params.path === "string" && params.path.trim() ? params.path.trim() : "";

  // Reject path that looks like a flag to avoid option injection via path.
  if (pathSpec.startsWith("-")) {
    return text("invalid path: must not start with '-'", true);
  }

  let args: string[];
  if (staged) {
    args = ["diff", "--cached"];
  } else {
    // Prefer HEAD so new files show as diffs when already staged-or-not mixed; fallback below.
    args = ["diff", "HEAD"];
  }
  if (pathSpec) {
    args.push("--", pathSpec);
  }

  let result = runGit(args, cwd);
  if (!result.ok && !staged) {
    args = pathSpec ? ["diff", "--", pathSpec] : ["diff"];
    result = runGit(args, cwd);
  }
  if (!result.ok) {
    return text(`git diff failed: ${result.stderr || result.code}`, true);
  }

  const raw = result.stdout;
  if (!raw.trim()) {
    return text(staged ? "(no staged changes)" : "(no diff)");
  }

  const { text: out, truncated } = truncateBytes(raw, DIFF_MAX_BYTES);
  const header = truncated
    ? `diff (${staged ? "staged" : "worktree"}; truncated at ${DIFF_MAX_BYTES} bytes)\n\n`
    : `diff (${staged ? "staged" : "worktree"})\n\n`;
  return text(header + out);
}

export default function (pi: ExtensionAPI) {
  // One stable tool instead of git_status + git_diff: fewer schemas in the prefix, and the
  // tool set stays constant so the prompt cache is never invalidated by it.
  pi.registerTool({
    name: "git",
    label: "Git",
    description:
      "Structured git for this project. actions: status, diff{staged?, path?}, help. " +
      'Prefer this over shelling out to git. Call action:"help" for details.',
    promptSnippet: "Structured git status / capped diff",
    promptGuidelines: [
      "Use the git tool rather than shelling out to git status/diff.",
      "If a diff comes back truncated, narrow it with path= instead of re-running it.",
    ],
    parameters: Type.Object({
      action: Type.String({ description: "status | diff | help" }),
      staged: Type.Optional(Type.Boolean()),
      path: Type.Optional(Type.String()),
    }),
    async execute(_id, params) {
      switch (params.action) {
        case "status":
          return gitStatus();
        case "diff":
          return gitDiff(params);
        case "help":
          return text(GIT_HELP);
        default:
          return text(`Unknown git action "${params.action}".\n\n${GIT_HELP}`, true);
      }
    },
  });

  // Cache discipline: this snapshot must never touch the system prompt.
  //
  // `before_agent_start` fires on every user turn and always receives the *base*
  // prompt (agent-session passes `_baseSystemPrompt`), so a MARKER guard never
  // trips and appending here rewrites the cached prefix every turn. Any change to
  // the dirty counts — i.e. every turn where the agent wrote a file — then costs a
  // full re-prime of the whole conversation at uncached prices.
  //
  // A custom message lands *after* the prefix (pi maps role "custom" to a user
  // message), so it is cache-neutral. Emit one only when the snapshot actually
  // changed; steady-state turns then add nothing at all.
  let lastSnapshot: string | null = null;
  pi.on("before_agent_start", () => {
    const snap = buildSnapshot(process.cwd());
    if (snap === lastSnapshot) return;
    lastSnapshot = snap;
    return {
      message: {
        customType: "pipiui-git-snapshot",
        content: [{ type: "text", text: snap }],
        display: false,
      },
    };
  });
}
"""#
}
