import Foundation

/// Pi extension: structured `git_status` / `git_diff` tools + system-prompt git snapshot.
/// Written to Application Support at launch and loaded via `pi -e <path>`.
enum GitExtension {
    static func install(into dir: URL) -> String? {
        let file = dir.appendingPathComponent("pipiui-git.ts")
        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try source.write(to: file, atomically: true, encoding: .utf8)
            return file.path
        } catch {
            return nil
        }
    }

    private static let source = #"""
// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Structured git tools for the agent: status + capped diff. No shell strings — argv only.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { spawnSync } from "node:child_process";

const DIFF_MAX_BYTES = 80_000;
const MARKER = "## Git (Pipi UI)";

function runGit(args: string[], cwd: string): {
  ok: boolean;
  stdout: string;
  stderr: string;
  code: number;
} {
  const r = spawnSync("git", args, {
    cwd,
    encoding: "utf8",
    maxBuffer: 2 * 1024 * 1024,
    env: process.env,
  });
  const code = typeof r.status === "number" ? r.status : 1;
  return {
    ok: code === 0 && !r.error,
    stdout: typeof r.stdout === "string" ? r.stdout : "",
    stderr:
      (typeof r.stderr === "string" ? r.stderr : "") ||
      (r.error ? String(r.error.message || r.error) : ""),
    code,
  };
}

function text(t: string, isError = false) {
  return {
    content: [{ type: "text" as const, text: t }],
    details: {},
    ...(isError ? { isError: true } : {}),
  };
}

function truncateBytes(s: string, maxBytes: number): { text: string; truncated: boolean } {
  const buf = Buffer.from(s, "utf8");
  if (buf.length <= maxBytes) return { text: s, truncated: false };
  let cut = s.slice(0, maxBytes);
  const nl = cut.lastIndexOf("\n");
  if (nl > 0) cut = cut.slice(0, nl);
  return {
    text: cut + `\n\n[truncated at ${maxBytes} bytes]`,
    truncated: true,
  };
}

function parsePorcelain(output: string): {
  staged: number;
  unstaged: number;
  untracked: number;
} {
  let staged = 0;
  let unstaged = 0;
  let untracked = 0;
  for (const line of output.split(/\r?\n/)) {
    if (line.length < 2) continue;
    const x = line[0];
    const y = line[1];
    if (x === "?" && y === "?") {
      untracked += 1;
      continue;
    }
    if (x === "?" || y === "?") continue;
    if (x !== " ") staged += 1;
    if (y !== " ") unstaged += 1;
  }
  return { staged, unstaged, untracked };
}

function buildSnapshot(cwd: string): string {
  const inside = runGit(["rev-parse", "--is-inside-work-tree"], cwd);
  if (!inside.ok || inside.stdout.trim() !== "true") {
    return `${MARKER}\nnot a git repository`;
  }

  const lines: string[] = [MARKER];
  const abbrev = runGit(["rev-parse", "--abbrev-ref", "HEAD"], cwd);
  const sha = runGit(["rev-parse", "--short", "HEAD"], cwd);
  const branch = abbrev.ok ? abbrev.stdout.trim() : "";
  const shortSha = sha.ok ? sha.stdout.trim() : "";

  if (branch === "HEAD") {
    lines.push(`branch: (detached) @ ${shortSha || "?"}`);
  } else {
    lines.push(`branch: ${branch || "unknown"}`);
  }
  if (shortSha) lines.push(`sha: ${shortSha}`);

  const porcelain = runGit(["status", "--porcelain"], cwd);
  const counts = porcelain.ok
    ? parsePorcelain(porcelain.stdout)
    : { staged: 0, unstaged: 0, untracked: 0 };
  const dirty = counts.staged + counts.unstaged + counts.untracked > 0;
  lines.push(
    `dirty: ${dirty ? "yes" : "no"} (staged=${counts.staged} unstaged=${counts.unstaged} untracked=${counts.untracked})`,
  );

  const up = runGit(
    ["rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{upstream}"],
    cwd,
  );
  if (up.ok && up.stdout.trim()) {
    const name = up.stdout.trim();
    const lr = runGit(["rev-list", "--left-right", "--count", "@{upstream}...HEAD"], cwd);
    let behind = 0;
    let ahead = 0;
    if (lr.ok) {
      const parts = lr.stdout.trim().split(/\s+/);
      if (parts.length >= 2) {
        behind = parseInt(parts[0], 10) || 0;
        ahead = parseInt(parts[1], 10) || 0;
      }
    }
    lines.push(`upstream: ${name} +${ahead} -${behind}`);
  } else {
    lines.push("upstream: (none)");
  }

  const origin = runGit(["remote", "get-url", "origin"], cwd);
  if (origin.ok && origin.stdout.trim()) {
    lines.push(`origin: ${origin.stdout.trim()}`);
  }

  lines.push(
    "Tools: git_status (porcelain + branch), git_diff (capped ~80KB). Prefer these over raw shell git when summarizing.",
  );
  return lines.join("\n");
}

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "git_status",
    label: "Git Status",
    description:
      "Return structured git status for the project working tree: branch, SHA, dirty counts " +
      "(staged/unstaged/untracked), upstream ahead/behind, origin URL, and porcelain lines. " +
      "Prefer this over running shell `git status` when you need repo state.",
    promptSnippet: "Structured git status (branch, dirty counts, upstream)",
    promptGuidelines: [
      "Use git_status to inspect the current repo before commit/PR summaries.",
      "Do not shell out to git status when this tool is available.",
    ],
    parameters: Type.Object({}),
    async execute() {
      const cwd = process.cwd();
      const inside = runGit(["rev-parse", "--is-inside-work-tree"], cwd);
      if (!inside.ok || inside.stdout.trim() !== "true") {
        return text("not a git repository", true);
      }

      const parts: string[] = [];
      const branch = runGit(["rev-parse", "--abbrev-ref", "HEAD"], cwd);
      const sha = runGit(["rev-parse", "--short", "HEAD"], cwd);
      if (branch.ok) parts.push(`branch: ${branch.stdout.trim()}`);
      if (sha.ok) parts.push(`sha: ${sha.stdout.trim()}`);

      const porcelain = runGit(["status", "--porcelain"], cwd);
      if (!porcelain.ok) {
        return text(`git status failed: ${porcelain.stderr || porcelain.code}`, true);
      }
      const counts = parsePorcelain(porcelain.stdout);
      const dirty = counts.staged + counts.unstaged + counts.untracked > 0;
      parts.push(
        `dirty: ${dirty ? "yes" : "no"} (staged=${counts.staged} unstaged=${counts.unstaged} untracked=${counts.untracked})`,
      );

      const up = runGit(
        ["rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{upstream}"],
        cwd,
      );
      if (up.ok && up.stdout.trim()) {
        const lr = runGit(["rev-list", "--left-right", "--count", "@{upstream}...HEAD"], cwd);
        let behind = 0;
        let ahead = 0;
        if (lr.ok) {
          const p = lr.stdout.trim().split(/\s+/);
          if (p.length >= 2) {
            behind = parseInt(p[0], 10) || 0;
            ahead = parseInt(p[1], 10) || 0;
          }
        }
        parts.push(`upstream: ${up.stdout.trim()} +${ahead} -${behind}`);
      } else {
        parts.push("upstream: (none)");
      }

      const origin = runGit(["remote", "get-url", "origin"], cwd);
      if (origin.ok && origin.stdout.trim()) {
        parts.push(`origin: ${origin.stdout.trim()}`);
      }

      parts.push("");
      parts.push("## porcelain");
      const body = porcelain.stdout.trimEnd();
      parts.push(body.length ? body : "(clean)");

      return text(parts.join("\n"));
    },
  });

  pi.registerTool({
    name: "git_diff",
    label: "Git Diff",
    description:
      "Return a git diff for the project working tree. Default: unstaged + untracked context via " +
      "`git diff HEAD` (falls back to `git diff`). Set staged=true for `--cached`. Optional path " +
      "limits to one path. Output is hard-capped at ~80KB with an explicit truncation note.",
    promptSnippet: "Capped git diff (staged or worktree, ~80KB max)",
    promptGuidelines: [
      "Use git_diff instead of shelling out to git diff for large changes.",
      "If truncated, summarize from the head of the diff or narrow with path=.",
    ],
    parameters: Type.Object({
      staged: Type.Optional(
        Type.Boolean({
          description: "If true, show staged diff only (`git diff --cached`).",
        }),
      ),
      path: Type.Optional(
        Type.String({
          description: "Optional pathspec to limit the diff (no shell metacharacters needed).",
        }),
      ),
    }),
    async execute(_id, params) {
      const cwd = process.cwd();
      const inside = runGit(["rev-parse", "--is-inside-work-tree"], cwd);
      if (!inside.ok || inside.stdout.trim() !== "true") {
        return text("not a git repository", true);
      }

      const staged = !!params.staged;
      const pathSpec =
        typeof params.path === "string" && params.path.trim() ? params.path.trim() : "";

      // Reject path that looks like a flag to avoid option injection via path.
      if (pathSpec.startsWith("-")) {
        return text("invalid path: must not start with '-'", true);
      }

      let args: string[];
      if (staged) {
        args = ["diff", "--cached"];
      } else {
        // Prefer HEAD so new files show as diffs when already staged-or-not mixed; fallback below.
        args = ["diff", "HEAD"];
      }
      if (pathSpec) {
        args.push("--", pathSpec);
      }

      let result = runGit(args, cwd);
      if (!result.ok && !staged) {
        args = pathSpec ? ["diff", "--", pathSpec] : ["diff"];
        result = runGit(args, cwd);
      }
      if (!result.ok) {
        return text(`git diff failed: ${result.stderr || result.code}`, true);
      }

      const raw = result.stdout;
      if (!raw.trim()) {
        return text(staged ? "(no staged changes)" : "(no diff)");
      }

      const { text: out, truncated } = truncateBytes(raw, DIFF_MAX_BYTES);
      const header = truncated
        ? `diff (${staged ? "staged" : "worktree"}; truncated at ${DIFF_MAX_BYTES} bytes)\n\n`
        : `diff (${staged ? "staged" : "worktree"})\n\n`;
      return text(header + out);
    },
  });

  pi.on("before_agent_start", (event) => {
    if (event.systemPrompt.includes(MARKER)) return;
    const snap = buildSnapshot(process.cwd());
    return { systemPrompt: `${event.systemPrompt}\n\n${snap}` };
  });
}
"""#
}
