import Foundation

/// Pi extension: user-added MCP servers (stdio + HTTP), exposed as local pi tools.
///
/// The extension is a hand-written, zero-dependency MCP client (JSON-RPC 2024-11-05):
///   - stdio: `child_process.spawn(command, args)` + line-delimited JSON over stdin/stdout
///   - http:  `fetch` POST with `${VAR}`-interpolated headers
///
/// Config is hot-read from `PIPIUI_MCP_CONFIG_FILE` (or the default App Support path) at
/// every need, so editing servers in the app takes effect without restarting pi:
/// registering tools still needs a session restart (`/pipiui_reload` or new session).
/// Written to Application Support by `PiPlugin.installAll()` and loaded via `pi -e <path>`.
enum McpBridgeExtension {
    static func install(into dir: URL) -> String? {
        let file = dir.appendingPathComponent("pipiui-mcp.ts")
        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try source.write(to: file, atomically: true, encoding: .utf8)
            return file.path
        } catch {
            return nil
        }
    }

    private static let source = #"""
// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// User-added MCP servers (stdio + HTTP) exposed as local pi tools.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { spawn } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

const PROTOCOL_VERSION = "2024-11-05";
const CLIENT_INFO = { name: "pipiui-mcp-bridge", version: "1.0.0" };
const INIT_TIMEOUT_MS = 15_000;   // initialize / tools/list
const CALL_TIMEOUT_MS = 60_000;   // tools/call

// ---------------------------------------------------------------------------
// Config (hot-read on every use)
// ---------------------------------------------------------------------------

interface ServerConfig {
	enabled: boolean;
	transport: "stdio" | "http";
	command?: string;
	args?: string[];
	env?: Record<string, string>;
	url?: string;
	headers?: Record<string, string>;
}

function configPath(): string {
	return (
		process.env.PIPIUI_MCP_CONFIG_FILE ||
		path.join(os.homedir(), "Library/Application Support/PipiUI/mcp-servers.json")
	);
}

function loadConfig(): Record<string, ServerConfig> {
	try {
		const raw = fs.readFileSync(configPath(), "utf-8");
		const parsed = JSON.parse(raw) as { servers?: unknown };
		if (parsed && typeof parsed === "object" && parsed.servers && typeof parsed.servers === "object") {
			return parsed.servers as Record<string, ServerConfig>;
		}
	} catch {
		// absent / unreadable → no servers
	}
	return {};
}

// Never leak a secret into output: only the variable NAME is reported when missing.
function expandVars(value: string, env: Record<string, string | undefined>): string {
	return value.replace(/\$\{([^}]+)\}/g, (whole, name: string) => {
		const v = env[name];
		if (v === undefined) {
			throw new Error(`config references ${whole} but environment variable ${name} is not set`);
		}
		return v;
	});
}

function expandRecord(
	record: Record<string, string> | undefined,
	env: Record<string, string | undefined>,
): Record<string, string> {
	const out: Record<string, string> = {};
	for (const key of Object.keys(record || {})) {
		out[key] = expandVars((record as Record<string, string>)[key], env);
	}
	return out;
}

// ---------------------------------------------------------------------------
// MCP transport clients
// ---------------------------------------------------------------------------

interface MCPClient {
	request(method: string, params: unknown, timeoutMs: number): Promise<unknown>;
	/** Fire-and-forget notification (no id, no response expected). */
	notify(method: string, params?: unknown): void;
	close(): void;
}

class StdioClient implements MCPClient {
	private proc: ReturnType<typeof spawn>;
	private buffer = "";
	private nextId = 1;
	private pending = new Map<number, { resolve: (v: unknown) => void; reject: (e: Error) => void }>();
	private stderrTail = "";

	constructor(cfg: ServerConfig, label: string) {
		const command = (cfg.command || "").trim();
		if (!command) throw new Error(`stdio server missing command`);
		let envBlock: Record<string, string>;
		try {
			envBlock = expandRecord(cfg.env, process.env);
		} catch (e) {
			throw new Error(`[${label}] ${(e as Error).message}`);
		}
		const env = { ...process.env, ...envBlock };
		this.proc = spawn(command, cfg.args || [], { env, stdio: ["pipe", "pipe", "pipe"] });
		this.proc.stdout?.on("data", (d: Buffer) => this.onData(d.toString()));
		this.proc.stderr?.on("data", (d: Buffer) => {
			this.stderrTail = (this.stderrTail + d.toString()).slice(-2000);
		});
		this.proc.on("error", (err: Error) => {
			this.failAll(new Error(`spawn ${command}: ${err.message}`));
		});
		this.proc.on("close", (code: number | null) => {
			const note = code ? ` (exit ${code})` : "";
			const tail = this.stderrTail.trim().slice(0, 300);
			this.failAll(new Error(`process ${command} closed${note}${tail ? `: ${tail}` : ""}`));
		});
	}

	private onData(text: string) {
		this.buffer += text;
		let idx: number;
		while ((idx = this.buffer.indexOf("\n")) >= 0) {
			const line = this.buffer.slice(0, idx).trim();
			this.buffer = this.buffer.slice(idx + 1);
			if (!line) continue;
			let msg: any;
			try {
				msg = JSON.parse(line);
			} catch {
				continue; // non-JSON log line from the server — ignore
			}
			if (msg && typeof msg.id === "number" && this.pending.has(msg.id)) {
				const p = this.pending.get(msg.id)!;
				this.pending.delete(msg.id);
				if (msg.error) {
					p.reject(new Error(`MCP error: ${msg.error.message || JSON.stringify(msg.error)}`));
				} else {
					p.resolve(msg.result);
				}
			}
		}
	}

	private failAll(err: Error) {
		for (const [, p] of this.pending) p.reject(err);
		this.pending.clear();
	}

	request(method: string, params: unknown, timeoutMs: number): Promise<unknown> {
		return new Promise((resolve, reject) => {
			const id = this.nextId++;
			this.pending.set(id, { resolve, reject });
			const timer = setTimeout(() => {
				if (this.pending.delete(id)) {
					reject(new Error(`timeout after ${timeoutMs / 1000}s waiting for ${method}`));
				}
			}, timeoutMs);
			const body: Record<string, unknown> = { jsonrpc: "2.0", id, method };
			if (params !== undefined) body.params = params;
			this.proc.stdin.write(JSON.stringify(body) + "\n", (err?: Error | null) => {
				if (err && this.pending.delete(id)) {
					clearTimeout(timer);
					reject(new Error(`write failed: ${err.message}`));
				} else {
					clearTimeout(timer);
				}
			});
		});
	}

	notify(method: string, params?: unknown): void {
		const body: Record<string, unknown> = { jsonrpc: "2.0", method };
		if (params !== undefined) body.params = params;
		try {
			this.proc.stdin.write(JSON.stringify(body) + "\n");
		} catch {
			/* best effort */
		}
	}

	close(): void {
		try {
			this.proc.stdin.end();
		} catch {
			/* ignore */
		}
		try {
			this.proc.kill("SIGTERM");
		} catch {
			/* ignore */
		}
	}
}

function parseSseOrJsonMessages(raw: string): unknown[] {
	const trimmed = raw.trim();
	if (!trimmed) return [];
	if (trimmed.startsWith("{")) {
		try {
			return [JSON.parse(trimmed)];
		} catch {
			// fall through to SSE
		}
	}
	const messages: unknown[] = [];
	let dataLines: string[] = [];
	const flush = () => {
		if (dataLines.length === 0) return;
		const data = dataLines.join("\n").trim();
		dataLines = [];
		if (!data || data === "[DONE]") return;
		try {
			messages.push(JSON.parse(data));
		} catch {
			/* ignore non-JSON frames */
		}
	};
	for (const line of raw.split(/\r?\n/)) {
		if (line.startsWith("data:")) {
			dataLines.push(line.slice(5).replace(/^ /, ""));
		} else if (line.trim() === "") {
			flush();
		}
	}
	flush();
	return messages;
}

class HttpClient implements MCPClient {
	private url: string;
	private headers: Record<string, string>;
	private nextId = 1;
	private sessionId?: string;

	constructor(cfg: ServerConfig, label: string) {
		const url = (cfg.url || "").trim();
		if (!url) throw new Error(`http server missing url`);
		if (!url.startsWith("http://") && !url.startsWith("https://")) {
			throw new Error(`http server url must start with http:// or https://`);
		}
		this.url = url;
		try {
			this.headers = expandRecord(cfg.headers, process.env);
		} catch (e) {
			throw new Error(`[${label}] ${(e as Error).message}`);
		}
	}

	async request(method: string, params: unknown, timeoutMs: number): Promise<unknown> {
		const controller = new AbortController();
		const timer = setTimeout(() => controller.abort(), timeoutMs);
		try {
			const headers: Record<string, string> = {
				"Content-Type": "application/json",
				Accept: "application/json, text/event-stream",
				...this.headers,
			};
			if (this.sessionId) headers["Mcp-Session-Id"] = this.sessionId;
			const body: Record<string, unknown> = { jsonrpc: "2.0", id: this.nextId++, method };
			if (params !== undefined) body.params = params;
			const res = await fetch(this.url, {
				method: "POST",
				headers,
				body: JSON.stringify(body),
				signal: controller.signal,
			});
			const sid = res.headers.get("Mcp-Session-Id") || res.headers.get("mcp-session-id");
			if (sid) this.sessionId = sid;
			const raw = await res.text();
			if (!res.ok) {
				throw new Error(`HTTP ${res.status} from ${this.url}: ${raw.replace(/\s+/g, " ").slice(0, 300)}`);
			}
			const messages = parseSseOrJsonMessages(raw);
			const payload = messages[messages.length - 1] as any;
			if (payload && payload.error) {
				throw new Error(`MCP error: ${payload.error.message || JSON.stringify(payload.error)}`);
			}
			return payload?.result;
		} catch (err: any) {
			if (err?.name === "AbortError") {
				throw new Error(`timeout after ${timeoutMs / 1000}s waiting for ${method}`);
			}
			throw err;
		} finally {
			clearTimeout(timer);
		}
	}

	notify(method: string, params?: unknown): void {
		const body: Record<string, unknown> = { jsonrpc: "2.0", method };
		if (params !== undefined) body.params = params;
		void fetch(this.url, {
			method: "POST",
			headers: { "Content-Type": "application/json", ...this.headers },
			body: JSON.stringify(body),
		}).catch(() => {});
	}

	close(): void {
		/* no per-request state to tear down */
	}
}

// ---------------------------------------------------------------------------
// Result formatting
// ---------------------------------------------------------------------------

function formatContent(content: unknown): string {
	if (content == null) return "";
	if (typeof content === "string") return content;
	if (Array.isArray(content)) {
		return content
			.map((item) => {
				if (typeof item === "string") return item;
				if (item && typeof item.text === "string") return item.text;
				if (item && item.type === "text" && typeof item.text === "string") return item.text;
				return JSON.stringify(item, null, 2);
			})
			.join("\n");
	}
	if (typeof content === "object") {
		const c = content as { text?: unknown };
		if (typeof c.text === "string") return c.text;
	}
	return JSON.stringify(content, null, 2);
}

function toolError(message: string) {
	return {
		content: [{ type: "text" as const, text: message }],
		details: { error: message },
		isError: true as const,
	};
}

function toolOk(text: string, details: Record<string, unknown> = {}) {
	return {
		content: [{ type: "text" as const, text }],
		details,
	};
}

// ---------------------------------------------------------------------------
// Extension
// ---------------------------------------------------------------------------

export default function (pi: ExtensionAPI) {
	const clients = new Map<string, MCPClient>();
	const registered = new Set<string>();
	const toolMap = new Map<string, { server: string; tool: string }>();

	pi.on("session_start", async () => {
		const config = loadConfig();
		for (const [name, cfg] of Object.entries(config)) {
			if (!cfg.enabled) continue;
			let client: MCPClient;
			try {
				client = cfg.transport === "http" ? new HttpClient(cfg, name) : new StdioClient(cfg, name);
			} catch (err) {
				// One broken server must not take down the others.
				console.error(`[pipiui-mcp] ${name}: ${(err as Error).message}`);
				continue;
			}
			try {
				await client.request(
					"initialize",
					{ protocolVersion: PROTOCOL_VERSION, capabilities: {}, clientInfo: CLIENT_INFO },
					INIT_TIMEOUT_MS,
				);
				client.notify("notifications/initialized");
				const result = (await client.request("tools/list", {}, INIT_TIMEOUT_MS)) as {
					tools?: Array<{ name: string; description?: string; inputSchema?: unknown }>;
				};
				const tools = result?.tools ?? [];
				const names: string[] = [];
				for (const tool of tools) {
					const toolName = `mcp_${name}_${tool.name}`;
					if (registered.has(toolName)) continue;
					registered.add(toolName);
					toolMap.set(toolName, { server: name, tool: tool.name });
					names.push(toolName);
					try {
						pi.registerTool({
							name: toolName,
							label: `${name}: ${tool.name}`,
							description: `MCP tool "${tool.name}" from server "${name}". ${tool.description || ""}`,
							// The remote inputSchema is translated through typebox structs by the
							// caller; fall back to a free-form object when absent.
							parameters: (tool.inputSchema as any) || Type.Object({}),
							async execute(_id, params, _signal, _onUpdate) {
								const mapping = toolMap.get(toolName);
								const client = mapping ? clients.get(mapping.server) : undefined;
								if (!mapping || !client) {
									return toolError(`mcp server unavailable for tool ${toolName}`);
								}
								try {
									const call = (await client.request(
										"tools/call",
										{ name: mapping.tool, arguments: params ?? {} },
										CALL_TIMEOUT_MS,
									)) as { content?: unknown; isError?: boolean };
									const text = formatContent(call?.content);
									if (call?.isError) {
										return toolError(text || `MCP server "${mapping.server}" returned isError=true`);
									}
									return toolOk(text, { server: mapping.server, tool: mapping.tool });
								} catch (err) {
									const message = err instanceof Error ? err.message : String(err);
									return toolError(`mcp_${name}_${tool.name} failed (${mapping.server}): ${message}`);
								}
							},
						});
					} catch (err) {
						// Duplicate / schema rejection — skip this tool, keep the rest.
						registered.delete(toolName);
						toolMap.delete(toolName);
						console.error(`[pipiui-mcp] ${name}: cannot register ${tool.name}: ${(err as Error).message}`);
					}
				}
				clients.set(name, client);
				// Make the new tools active in the current session.
				if (names.length > 0) {
					try {
						const active = pi.getActiveTools();
						pi.setActiveTools([...new Set([...active, ...names])]);
					} catch {
						/* tool-activation API may be unavailable outside a tui session */
					}
				}
			} catch (err) {
				client.close();
				console.error(`[pipiui-mcp] ${name}: init failed: ${(err as Error).message}`);
			}
		}
	});

	pi.on("session_shutdown", () => {
		for (const [, client] of clients) {
			try {
				client.close();
			} catch {
				/* ignore */
			}
		}
		clients.clear();
	});
}
"""#
}