import Foundation

/// Generated Pi extension for local PDF extraction. Installation and `-e`/env
/// routing deliberately remain a separate seam so this source can ship before
/// the feature router decides which main/subagent sessions receive the tool.
enum PDFExtractExtension {
    static let fileName = "pipiui-pdf-extract.ts"
    static let helperExecutableName = "pipiui-pdf-helper"
    static let helperEnvironmentKey = "PIPIUI_PDF_HELPER"

    /// The routing layer should inject this exact environment value alongside
    /// `-e <install(into:)>`; the extension emits a clear error when absent.
    static func helperPath(appBundleURL: URL = Bundle.main.bundleURL) -> String {
        appBundleURL
            .appendingPathComponent("Contents", isDirectory: true)
            .appendingPathComponent("Helpers", isDirectory: true)
            .appendingPathComponent(helperExecutableName)
            .path
    }

    static func helperEnvironment(appBundleURL: URL = Bundle.main.bundleURL) -> [String: String] {
        [helperEnvironmentKey: helperPath(appBundleURL: appBundleURL)]
    }

    static func install(into dir: URL) -> String? {
        let file = dir.appendingPathComponent(fileName)
        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try source.write(to: file, atomically: true, encoding: .utf8)
            return file.path
        } catch {
            return nil
        }
    }

    private static let source = #"""
// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Local PDF extraction: PDFKit text first, then on-device Vision OCR only for
// weak pages. No API key, cloud upload, runtime package installation, or model download is used.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { spawn } from "node:child_process";
import { constants } from "node:fs";
import { access, mkdtemp, open, realpath, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { isAbsolute, join } from "node:path";

const HELPER_ENV = "PIPIUI_PDF_HELPER";
const MAX_PDF_BYTES = 50 * 1024 * 1024;
const DOWNLOAD_TIMEOUT_MS = 30_000;
const HELPER_TIMEOUT_MS = 150_000;
const MAX_HELPER_STDOUT_BYTES = 1_500_000;
const MAX_HELPER_STDERR_BYTES = 4_000;
const MAX_OUTPUT_LENGTH = 100_000;

type PDFMode = "auto" | "text" | "ocr";
type HelperMetadata = {
  pageCount: number;
  selectedPages: number[];
  textPages: number[];
  ocrPages: number[];
  warnings: string[];
  truncated: boolean;
};
type HelperResponse = {
  ok: boolean;
  markdown?: string;
  metadata?: HelperMetadata;
  error?: { code?: string; message?: string };
};

function result(text: string, isError = false, details: Record<string, unknown> = {}) {
  return {
    content: [{ type: "text" as const, text }],
    details,
    ...(isError ? { isError: true } : {}),
  };
}

function parseMode(value: unknown): PDFMode {
  if (value === undefined || value === null || value === "") return "auto";
  if (value === "auto" || value === "text" || value === "ocr") return value;
  throw new Error("mode must be one of auto, text, or ocr.");
}

function parsePages(value: unknown): number[] | undefined {
  if (value === undefined || value === null) return undefined;
  if (!Array.isArray(value) || value.length === 0) throw new Error("pages must be a non-empty array of positive page numbers.");
  const pages = value.map((item) => Number(item));
  if (pages.some((page) => !Number.isInteger(page) || page < 1)) {
    throw new Error("pages must contain only positive integer page numbers.");
  }
  return [...new Set(pages)].sort((a, b) => a - b);
}

function parseMaxLength(value: unknown): number | undefined {
  if (value === undefined || value === null) return undefined;
  const max = Number(value);
  if (!Number.isInteger(max) || max < 1 || max > MAX_OUTPUT_LENGTH) {
    throw new Error(`max_length must be an integer from 1 to ${MAX_OUTPUT_LENGTH}.`);
  }
  return max;
}

function isPDFContentType(value: string): boolean {
  const type = value.split(";", 1)[0].trim().toLowerCase();
  return type === "application/pdf" || type === "application/x-pdf" || type === "application/octet-stream";
}

async function assertPDFSignature(filePath: string): Promise<void> {
  const handle = await open(filePath, "r");
  try {
    const header = Buffer.alloc(5);
    const { bytesRead } = await handle.read(header, 0, header.length, 0);
    if (bytesRead !== 5 || header.toString("ascii") !== "%PDF-") {
      throw new Error("file does not start with the %PDF- signature.");
    }
  } finally {
    await handle.close();
  }
}

async function validateLocalPDF(source: string): Promise<string> {
  if (!isAbsolute(source)) throw new Error("local PDF path must be absolute.");
  let canonical: string;
  try { canonical = await realpath(source); }
  catch { throw new Error("local PDF path does not exist or cannot be read."); }
  let info: Awaited<ReturnType<typeof stat>>;
  try { info = await stat(canonical); }
  catch { throw new Error("local PDF path cannot be inspected."); }
  if (!info.isFile()) throw new Error("local PDF path must name a regular file.");
  if (info.size <= 0) throw new Error("local PDF file is empty.");
  if (info.size > MAX_PDF_BYTES) throw new Error(`local PDF exceeds the ${MAX_PDF_BYTES / (1024 * 1024)} MB limit.`);
  await assertPDFSignature(canonical);
  return canonical;
}

type DownloadedPDF = { path: string; tempDir: string };

async function downloadPDF(source: URL, signal?: AbortSignal): Promise<DownloadedPDF> {
  const tempDir = await mkdtemp(join(tmpdir(), "pipiui-pdf-"));
  const filePath = join(tempDir, "download.pdf");
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), DOWNLOAD_TIMEOUT_MS);
  const abort = () => controller.abort();
  signal?.addEventListener("abort", abort, { once: true });
  try {
    const response = await fetch(source.href, {
      redirect: "follow",
      signal: controller.signal,
      headers: { Accept: "application/pdf,application/octet-stream;q=0.9,*/*;q=0.1" },
    });
    if (!response.ok) throw new Error(`download returned HTTP ${response.status}.`);
    const finalURL = new URL(response.url);
    if (finalURL.protocol !== "http:" && finalURL.protocol !== "https:") {
      throw new Error("download redirected outside HTTP(S).");
    }
    const contentType = response.headers.get("content-type") || "";
    if (contentType && !isPDFContentType(contentType)) {
      throw new Error(`download content-type is not PDF: ${contentType.split(";", 1)[0]}.`);
    }
    const declared = Number(response.headers.get("content-length") || 0);
    if (declared > MAX_PDF_BYTES) throw new Error(`download exceeds the ${MAX_PDF_BYTES / (1024 * 1024)} MB limit.`);
    if (!response.body) throw new Error("download returned no body.");

    const output = await open(filePath, "wx");
    let byteCount = 0;
    let magic = Buffer.alloc(0);
    try {
      const reader = response.body.getReader();
      try {
        while (true) {
          const next = await reader.read();
          if (next.done) break;
          const chunk = Buffer.from(next.value);
          byteCount += chunk.byteLength;
          if (byteCount > MAX_PDF_BYTES) throw new Error(`download exceeds the ${MAX_PDF_BYTES / (1024 * 1024)} MB limit.`);
          if (magic.length < 5) magic = Buffer.concat([magic, chunk]).subarray(0, 5);
          await output.write(chunk);
        }
      } finally {
        reader.releaseLock();
      }
    } finally {
      await output.close();
    }
    if (magic.length !== 5 || magic.toString("ascii") !== "%PDF-") {
      throw new Error("download does not start with the %PDF- signature.");
    }
    return { path: filePath, tempDir };
  } catch (error: any) {
    await rm(tempDir, { recursive: true, force: true });
    if (error?.name === "AbortError") throw new Error("PDF download timed out after 30s.");
    throw error;
  } finally {
    clearTimeout(timeout);
    signal?.removeEventListener("abort", abort);
  }
}

async function resolvePDFSource(source: string, signal?: AbortSignal): Promise<{ path: string; cleanup?: () => Promise<void> }> {
  let parsed: URL | undefined;
  try { parsed = new URL(source); } catch { /* absolute path is handled below */ }
  if (parsed) {
    if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
      throw new Error("URL source must use http:// or https://.");
    }
    const downloaded = await downloadPDF(parsed, signal);
    return {
      path: downloaded.path,
      cleanup: async () => { await rm(downloaded.tempDir, { recursive: true, force: true }); },
    };
  }
  return { path: await validateLocalPDF(source) };
}

function runHelper(helper: string, payload: Record<string, unknown>, signal?: AbortSignal): Promise<HelperResponse> {
  return new Promise((resolvePromise, reject) => {
    const child = spawn(helper, [], {
      shell: false,
      stdio: ["pipe", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    let settled = false;
    const finish = (callback: () => void) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      signal?.removeEventListener("abort", abort);
      callback();
    };
    const abort = () => { try { child.kill("SIGTERM"); } catch { /* already stopped */ } };
    const timeout = setTimeout(() => {
      try { child.kill("SIGTERM"); } catch { /* already stopped */ }
      setTimeout(() => { try { child.kill("SIGKILL"); } catch { /* already stopped */ } }, 1_000).unref?.();
    }, HELPER_TIMEOUT_MS);
    signal?.addEventListener("abort", abort, { once: true });

    child.stdout?.on("data", (chunk: Buffer) => {
      stdout += chunk.toString();
      if (stdout.length > MAX_HELPER_STDOUT_BYTES) child.kill("SIGTERM");
    });
    child.stderr?.on("data", (chunk: Buffer) => {
      stderr = (stderr + chunk.toString()).slice(-MAX_HELPER_STDERR_BYTES);
    });
    child.once("error", (error) => finish(() => reject(new Error(`cannot start local PDF helper: ${error.message}`))));
    child.once("close", (code) => finish(() => {
      let response: HelperResponse | undefined;
      try { response = JSON.parse(stdout.trim()) as HelperResponse; }
      catch {
        reject(new Error(`local PDF helper returned invalid JSON${stderr.trim() ? `: ${stderr.trim()}` : ""}`));
        return;
      }
      if (response.ok && code === 0) {
        resolvePromise(response);
        return;
      }
      const message = response.error?.message || stderr.trim() || `local PDF helper exited ${code ?? "without a status"}.`;
      reject(new Error(message));
    }));
    try {
      child.stdin.end(JSON.stringify(payload) + "\n");
    } catch (error: any) {
      finish(() => reject(new Error(`cannot send request to local PDF helper: ${error?.message || String(error)}`)));
    }
  });
}

async function helperPath(): Promise<string> {
  const helper = (process.env[HELPER_ENV] || "").trim();
  if (!helper) {
    throw new Error(`pdf_extract is unavailable: ${HELPER_ENV} is not set. Restart PipiUI after installing its bundled PDF helper.`);
  }
  try {
    await access(helper, constants.X_OK);
  } catch {
    throw new Error(`pdf_extract is unavailable: ${HELPER_ENV} does not name an executable helper.`);
  }
  return helper;
}

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "pdf_extract",
    label: "Extract PDF",
    description:
      "Extract page-by-page Markdown from a local PDF path or HTTP(S) PDF URL. In auto mode, " +
      "uses PDF text first and on-device Vision OCR only for weak pages; no cloud upload or API key.",
    promptSnippet: "Extract text from a local PDF path or HTTP(S) PDF URL",
    promptGuidelines: [
      "Use pdf_extract for PDF text, keeping the original PDF as the visual truth for complex tables, formulas, charts, and layout.",
      "Prefer mode=auto. Use text only to inspect the embedded layer, or ocr to force local OCR on selected pages.",
      "The URL downloader accepts only HTTP(S), has a 30s / 50 MB boundary, validates content type and %PDF-, and removes its temporary file after the helper exits.",
    ],
    parameters: Type.Object({
      source: Type.String({ description: "Absolute local PDF path, or an http:// or https:// PDF URL." }),
      mode: Type.Optional(Type.Union([
        Type.Literal("auto"), Type.Literal("text"), Type.Literal("ocr"),
      ], { description: "auto (default), text, or ocr." })),
      pages: Type.Optional(Type.Array(Type.Integer({ minimum: 1 }), {
        description: "Optional 1-based page numbers. Only selected pages are extracted.",
      })),
      max_length: Type.Optional(Type.Integer({ minimum: 1, maximum: MAX_OUTPUT_LENGTH, description: "Maximum Markdown characters returned." })),
    }),
    async execute(_id, params, signal) {
      try {
        const source = String(params.source || "").trim();
        if (!source) return result("pdf_extract: source is required.", true);
        const mode = parseMode(params.mode);
        const pages = parsePages(params.pages);
        const maxLength = parseMaxLength(params.max_length);
        // Fail before downloading a URL when the App has not injected its signed helper.
        const helper = await helperPath();
        const resolved = await resolvePDFSource(source, signal);
        try {
          const response = await runHelper(helper, {
            path: resolved.path,
            mode,
            ...(pages ? { pages } : {}),
            ...(maxLength ? { max_length: maxLength } : {}),
          }, signal);
          const metadata = response.metadata;
          if (!metadata || typeof response.markdown !== "string") {
            return result("pdf_extract: helper returned an incomplete success response.", true);
          }
          // The helper places the same diagnostics in its Markdown metadata
          // block; keep this tool result within max_length and expose the
          // structured copy through details for UI/debug consumers.
          return result(response.markdown, false, { ...metadata });
        } finally {
          await resolved.cleanup?.();
        }
      } catch (error: any) {
        return result(`pdf_extract failed: ${error?.message || String(error)}`, true);
      }
    },
  });
}
"""#
}
