import Foundation

/// Pi extension: structured plan runtime for the main bridged session.
///
/// Registers `plan_publish` and `plan_task_update` so the main agent can feed a
/// task list to the App. Payloads are validated here, then POSTed as authenticated
/// `plan_event` bodies through the loopback bridge
/// (`PIPIUI_BRIDGE_PORT` + `PIPIUI_SESSION_KEY`).
///
/// Revision sequencing is store-owned: tools never send a client revision. The
/// bridge response must report `applied: true` with the assigned revision before
/// the tool claims success — ignored/rejected/delivery failures are tool errors.
///
/// Main bridged session only — never re-exported to dispatched workers.
enum PlanRuntimeExtension {
    static let fileName = "pipiui-plan-runtime.ts"

    static func install(into dir: URL) -> String? {
        let file = dir.appendingPathComponent(fileName)
        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try source.write(to: file, atomically: true, encoding: .utf8)
            return file.path
        } catch {
            return nil
        }
    }

    private static let source = #"""
// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Main-session plan runtime: validate + POST plan_event through the App bridge.
// Revision is assigned by PlanStore; tools never claim success without applied:true.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

const SCHEMA_VERSION = 1;
const MAX_TASKS = 100;
const KNOWN_STATES = new Set([
  "pending",
  "running",
  "completed",
  "failed",
  "blocked",
  "skipped",
]);
const BRIDGE_TIMEOUT_MS = 3_000;

const PORT = process.env.PIPIUI_BRIDGE_PORT;
const KEY = process.env.PIPIUI_SESSION_KEY;

type TaskState = "pending" | "running" | "completed" | "failed" | "blocked" | "skipped";

interface PlanTask {
  id: string;
  title: string;
  state: TaskState;
  detail?: string;
  error?: string;
}

interface PlanBody {
  id: string;
  title: string;
  summary?: string;
  tasks: PlanTask[];
}

interface BridgeResult {
  delivered: boolean;
  applied: boolean;
  revision?: number;
  currentRevision?: number;
  deliveryNote?: string;
  error?: string;
}

function textResult(text: string, details: Record<string, unknown> = {}, isError = false) {
  return {
    content: [{ type: "text" as const, text }],
    details,
    ...(isError ? { isError: true } : {}),
  };
}

function asNonEmptyString(value: unknown, field: string): string | { error: string } {
  if (typeof value !== "string") return { error: `${field} must be a string` };
  const trimmed = value.trim();
  if (!trimmed) return { error: `${field} must be a non-empty string` };
  return trimmed;
}

function asOptionalString(value: unknown, field: string): string | undefined | { error: string } {
  // Omitted (undefined) is OK; explicit null is not a string and must be rejected.
  if (value === undefined) return undefined;
  if (value === null) return { error: `${field} must be a string when present` };
  if (typeof value !== "string") return { error: `${field} must be a string when present` };
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

/** Empty string is preserved so the store can clear detail/error explicitly. Null is rejected. */
function asOptionalClearableString(
  value: unknown,
  field: string,
): string | undefined | { error: string } {
  if (value === undefined) return undefined;
  if (value === null) return { error: `${field} must be a string when present` };
  if (typeof value !== "string") return { error: `${field} must be a string when present` };
  return value;
}

function asSchemaVersion(value: unknown): number | { error: string } {
  if (typeof value !== "number" || !Number.isInteger(value)) {
    return { error: "schemaVersion must be an integer" };
  }
  if (value !== SCHEMA_VERSION) {
    return { error: `unsupported schemaVersion ${value}; expected ${SCHEMA_VERSION}` };
  }
  return value;
}

function asState(value: unknown, field: string, required: boolean): TaskState | undefined | { error: string } {
  if (value === undefined) {
    if (required) return { error: `${field} is required` };
    return undefined;
  }
  if (value === null) {
    return { error: required ? `${field} must be a string` : `${field} must be a string when present` };
  }
  if (typeof value !== "string" || !KNOWN_STATES.has(value)) {
    return {
      error: `${field} must be one of ${[...KNOWN_STATES].join(", ")}`,
    };
  }
  return value as TaskState;
}

function normalizeTask(raw: unknown, index: number): PlanTask | { error: string } {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    return { error: `tasks[${index}] must be an object` };
  }
  const obj = raw as Record<string, unknown>;
  const id = asNonEmptyString(obj.id, `tasks[${index}].id`);
  if (typeof id === "object") return id;
  const title = asNonEmptyString(obj.title, `tasks[${index}].title`);
  if (typeof title === "object") return title;
  const state = asState(obj.state, `tasks[${index}].state`, false);
  if (state && typeof state === "object" && "error" in state) return state;
  const detail = asOptionalClearableString(obj.detail, `tasks[${index}].detail`);
  if (detail && typeof detail === "object" && "error" in detail) return detail;
  const errorText = asOptionalClearableString(obj.error, `tasks[${index}].error`);
  if (errorText && typeof errorText === "object" && "error" in errorText) return errorText;
  const task: PlanTask = {
    id,
    title,
    state: (state as TaskState | undefined) ?? "pending",
  };
  if (typeof detail === "string") task.detail = detail;
  if (typeof errorText === "string") task.error = errorText;
  return task;
}

function normalizePlan(raw: unknown): PlanBody | { error: string } {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    return { error: "plan must be an object" };
  }
  const obj = raw as Record<string, unknown>;
  const id = asNonEmptyString(obj.id, "plan.id");
  if (typeof id === "object") return id;
  const title = asNonEmptyString(obj.title, "plan.title");
  if (typeof title === "object") return title;
  const summary = asOptionalString(obj.summary, "plan.summary");
  if (summary && typeof summary === "object" && "error" in summary) return summary;
  if (!Array.isArray(obj.tasks)) return { error: "plan.tasks must be an array" };
  if (obj.tasks.length > MAX_TASKS) {
    return { error: `plan.tasks exceeds max of ${MAX_TASKS}` };
  }
  const tasks: PlanTask[] = [];
  const seen = new Set<string>();
  for (let i = 0; i < obj.tasks.length; i++) {
    const task = normalizeTask(obj.tasks[i], i);
    if ("error" in task) return task;
    if (seen.has(task.id)) {
      return { error: `duplicate task id ${JSON.stringify(task.id)}` };
    }
    seen.add(task.id);
    tasks.push(task);
  }
  const plan: PlanBody = { id, title, tasks };
  if (typeof summary === "string") plan.summary = summary;
  return plan;
}

function normalizeTaskUpdate(raw: unknown): {
  id: string;
  state: TaskState;
  title?: string;
  detail?: string;
  error?: string;
  detailProvided: boolean;
  errorProvided: boolean;
} | { error: string } {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    return { error: "task must be an object" };
  }
  const obj = raw as Record<string, unknown>;
  const id = asNonEmptyString(obj.id, "task.id");
  if (typeof id === "object") return id;
  const state = asState(obj.state, "task.state", true);
  if (!state || (typeof state === "object" && "error" in state)) {
    return (state as { error: string }) ?? { error: "task.state is required" };
  }
  const title = asOptionalString(obj.title, "task.title");
  if (title && typeof title === "object" && "error" in title) return title;
  const detailProvided = Object.prototype.hasOwnProperty.call(obj, "detail");
  const errorProvided = Object.prototype.hasOwnProperty.call(obj, "error");
  let detail: string | undefined;
  if (detailProvided) {
    const d = asOptionalClearableString(obj.detail, "task.detail");
    if (d && typeof d === "object" && "error" in d) return d;
    detail = d as string | undefined;
  }
  let errorText: string | undefined;
  if (errorProvided) {
    const e = asOptionalClearableString(obj.error, "task.error");
    if (e && typeof e === "object" && "error" in e) return e;
    errorText = e as string | undefined;
  }
  const task: {
    id: string;
    state: TaskState;
    title?: string;
    detail?: string;
    error?: string;
    detailProvided: boolean;
    errorProvided: boolean;
  } = {
    id,
    state: state as TaskState,
    detailProvided,
    errorProvided,
  };
  if (typeof title === "string") task.title = title;
  if (detailProvided) task.detail = detail ?? "";
  if (errorProvided) task.error = errorText ?? "";
  return task;
}

async function postPlanEvent(payload: Record<string, unknown>): Promise<BridgeResult> {
  if (!PORT || !KEY) {
    return {
      delivered: false,
      applied: false,
      deliveryNote: "bridge unavailable: missing PIPIUI_BRIDGE_PORT or PIPIUI_SESSION_KEY",
    };
  }
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), BRIDGE_TIMEOUT_MS);
  try {
    const res = await fetch(`http://127.0.0.1:${PORT}/rpc`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      signal: controller.signal,
      body: JSON.stringify({
        sessionKey: KEY,
        action: "plan_event",
        ...payload,
      }),
    });
    let body: any = null;
    try {
      body = await res.json();
    } catch {
      body = null;
    }
    if (!res.ok) {
      return {
        delivered: false,
        applied: false,
        deliveryNote: `bridge HTTP ${res.status}${body?.error ? `: ${body.error}` : ""}`,
        error: body?.error ? String(body.error) : undefined,
        currentRevision:
          typeof body?.currentRevision === "number" ? body.currentRevision : undefined,
      };
    }
    // Store contract: ok+applied must both be true AND revision must be an integer.
    // Never treat silence or a missing revision as success.
    const revisionRaw = body && typeof body === "object" ? body.revision : undefined;
    const revision =
      typeof revisionRaw === "number" && Number.isInteger(revisionRaw) ? revisionRaw : undefined;
    const currentRevision =
      typeof body?.currentRevision === "number" && Number.isInteger(body.currentRevision)
        ? body.currentRevision
        : undefined;
    const applied = !!(body && typeof body === "object" && body.ok === true && body.applied === true && revision != null);
    if (!applied) {
      let err =
        body && typeof body === "object" && body.error
          ? String(body.error)
          : body && typeof body === "object" && body.reason
            ? String(body.reason)
            : "plan event was not applied";
      if (body && typeof body === "object" && body.ok === true && body.applied === true && revision == null) {
        err = "plan event acknowledgement missing integer revision";
      }
      return {
        delivered: true,
        applied: false,
        revision,
        currentRevision,
        error: err,
        deliveryNote: err,
      };
    }
    return {
      delivered: true,
      applied: true,
      revision,
      currentRevision,
    };
  } catch (err) {
    const message =
      controller.signal.aborted
        ? "bridge request timed out"
        : err instanceof Error
          ? err.message
          : String(err);
    return { delivered: false, applied: false, deliveryNote: message };
  } finally {
    clearTimeout(timer);
  }
}

function formatFailure(delivery: BridgeResult): string {
  const parts = [
    delivery.error || delivery.deliveryNote || "unknown error",
    delivery.currentRevision != null ? `currentRevision=${delivery.currentRevision}` : null,
  ].filter(Boolean);
  return parts.join("; ");
}

async function changeLifecycle(event: "approve" | "cancel", planId: unknown) {
  const normalizedPlanId = asNonEmptyString(planId, "planId");
  if (typeof normalizedPlanId === "object") {
    return textResult(normalizedPlanId.error, { ok: false, event }, true);
  }
  const at = new Date().toISOString();
  const delivery = await postPlanEvent({ event, planId: normalizedPlanId, at });
  if (!delivery.delivered || !delivery.applied || delivery.revision == null) {
    return textResult(`Plan ${event} failed: ${formatFailure(delivery)}`, {
      ok: false, event, planId: normalizedPlanId, at, delivered: delivery.delivered,
      applied: false, deliveryNote: delivery.deliveryNote, error: delivery.error,
      currentRevision: delivery.currentRevision,
    }, true);
  }
  return textResult(`Plan ${event}d (rev ${delivery.revision}).`, {
    ok: true, event, planId: normalizedPlanId, at, delivered: true, applied: true,
    revision: delivery.revision,
  });
}

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "plan_publish",
    label: "Plan Publish",
    description: [
      "Publish or replace this session's structured execution plan for the App plan card.",
      "Call after the detailed plan is ready in assistant prose. One active plan per session.",
      "plan.id is mandatory: choose a stable unique id and reuse it on every plan_task_update.",
      "Revision is assigned by the App — do not send a client revision.",
      "Tasks are ordered, unique by id, and capped at 100.",
      "Known task states: pending, running, completed, failed, blocked, skipped.",
      "After publishing, stop at the approval boundary. In user-visible plan copy, use a concise invitation in the user's language; never require the user to type Execute, Adjust, Ignore, or any English token.",
      "For Chinese, say: 如果批准，请回复“批准”；如果需要调整计划或不执行，直接告诉我。",
    ].join(" "),
    parameters: Type.Object({
      schemaVersion: Type.Integer({ description: `Must be ${SCHEMA_VERSION}.` }),
      plan: Type.Object({
        id: Type.String({ description: "Stable unique plan id for this session (required)." }),
        title: Type.String({ description: "Short plan title." }),
        summary: Type.Optional(Type.String({ description: "Optional one-line summary." })),
        tasks: Type.Array(
          Type.Object({
            id: Type.String({ description: "Stable unique task id." }),
            title: Type.String({ description: "Task title." }),
            state: Type.Optional(
              Type.String({
                description: "pending|running|completed|failed|blocked|skipped (default pending).",
              }),
            ),
            detail: Type.Optional(Type.String({ description: "Optional status detail (empty clears)." })),
            error: Type.Optional(Type.String({ description: "Optional error text (empty clears)." })),
          }),
        ),
      }),
    }),
    async execute(_id, params) {
      const schemaVersion = asSchemaVersion(params.schemaVersion);
      if (typeof schemaVersion === "object") {
        return textResult(schemaVersion.error, { ok: false }, true);
      }
      const plan = normalizePlan(params.plan);
      if ("error" in plan) {
        return textResult(plan.error, { ok: false }, true);
      }
      const at = new Date().toISOString();
      const event = {
        event: "publish" as const,
        schemaVersion,
        plan,
        at,
      };
      const delivery = await postPlanEvent(event);
      if (!delivery.delivered || !delivery.applied || delivery.revision == null) {
        return textResult(`Plan publish failed: ${formatFailure(delivery)}`, {
          ok: false,
          event: "publish",
          schemaVersion,
          plan,
          at,
          delivered: delivery.delivered,
          applied: false,
          deliveryNote: delivery.deliveryNote,
          error: delivery.error,
          currentRevision: delivery.currentRevision,
        }, true);
      }
      const rev = delivery.revision;
      const summary = `Published plan rev ${rev}: ${plan.title} (${plan.tasks.length} tasks).`;
      return textResult(summary, {
        ok: true,
        event: "publish",
        schemaVersion,
        revision: rev,
        plan,
        at,
        delivered: true,
        applied: true,
      });
    },
  });

  pi.registerTool({
    name: "plan_approve",
    label: "Plan Approve",
    description: [
      "Approve the formally published plan only after the user has naturally approved it in their own language.",
      "For Chinese, treat 批准, 开始执行, or 执行计划 as Execute.",
      "Only then may execution begin.",
    ].join(" "),
    parameters: Type.Object({
      planId: Type.String({ description: "Must match the awaiting plan.id." }),
    }),
    async execute(_id, params) {
      return changeLifecycle("approve", params.planId);
    },
  });

  pi.registerTool({
    name: "plan_cancel",
    label: "Plan Cancel",
    description: [
      "Cancel the current plan after a natural-language refusal/cancellation or before a requested replacement.",
      "For Chinese, treat 忽略, 取消, or 不执行 as Ignore; treat 调整 or 修改计划 with feedback as Adjust and cancel before republishing.",
      "Never require the user to type the internal Ignore or Adjust labels.",
    ].join(" "),
    parameters: Type.Object({
      planId: Type.String({ description: "Must match the current plan.id." }),
    }),
    async execute(_id, params) {
      return changeLifecycle("cancel", params.planId);
    },
  });

  pi.registerTool({
    name: "plan_task_update",
    label: "Plan Task Update",
    description: [
      "Update one task on the session's published plan (state and optional detail/error).",
      "Use during authorized execution. Revision is assigned by the App.",
      "planId is always required and must match the published plan.id.",
      "Pass detail/error as empty string to clear. Known states:",
      "pending, running, completed, failed, blocked, skipped.",
    ].join(" "),
    parameters: Type.Object({
      schemaVersion: Type.Integer({ description: `Must be ${SCHEMA_VERSION}.` }),
      planId: Type.String({ description: "Must match the published plan.id." }),
      task: Type.Object({
        id: Type.String({ description: "Existing task id." }),
        state: Type.String({ description: "pending|running|completed|failed|blocked|skipped." }),
        title: Type.Optional(Type.String({ description: "Optional title correction." })),
        detail: Type.Optional(Type.String({ description: "Status detail; empty string clears." })),
        error: Type.Optional(Type.String({ description: "Error text; empty string clears." })),
      }),
    }),
    async execute(_id, params) {
      const schemaVersion = asSchemaVersion(params.schemaVersion);
      if (typeof schemaVersion === "object") {
        return textResult(schemaVersion.error, { ok: false }, true);
      }
      const planId = asNonEmptyString(params.planId, "planId");
      if (typeof planId === "object") {
        return textResult(planId.error, { ok: false }, true);
      }
      const task = normalizeTaskUpdate(params.task);
      if ("error" in task) {
        return textResult(task.error, { ok: false }, true);
      }
      const at = new Date().toISOString();
      const taskPayload: Record<string, unknown> = {
        id: task.id,
        state: task.state,
      };
      if (typeof task.title === "string") taskPayload.title = task.title;
      if (task.detailProvided) taskPayload.detail = task.detail ?? "";
      if (task.errorProvided) taskPayload.error = task.error ?? "";
      const event: Record<string, unknown> = {
        event: "task_update",
        schemaVersion,
        planId,
        task: taskPayload,
        at,
      };
      const delivery = await postPlanEvent(event);
      if (!delivery.delivered || !delivery.applied || delivery.revision == null) {
        return textResult(`Plan task update failed: ${formatFailure(delivery)}`, {
          ok: false,
          event: "task_update",
          schemaVersion,
          planId,
          task: taskPayload,
          at,
          delivered: delivery.delivered,
          applied: false,
          deliveryNote: delivery.deliveryNote,
          error: delivery.error,
          currentRevision: delivery.currentRevision,
        }, true);
      }
      const rev = delivery.revision;
      const summary = `Updated task ${task.id} → ${task.state} (rev ${rev}).`;
      return textResult(summary, {
        ok: true,
        event: "task_update",
        schemaVersion,
        revision: rev,
        planId,
        task: taskPayload,
        at,
        delivered: true,
        applied: true,
      });
    },
  });
}
"""#
}
