import Foundation

/// Pi extension: internal `pipiui_reload` command that calls `ctx.reload()`.
/// GUI builtin `/reload` prompts this command (RPC has no dedicated reload type).
enum ReloadExtension {
    static func install(into dir: URL) -> String? {
        let file = dir.appendingPathComponent("pipiui-reload.ts")
        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try source.write(to: file, atomically: true, encoding: .utf8)
            return file.path
        } catch {
            return nil
        }
    }

    private static let source = #"""
// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

export default function (pi: ExtensionAPI) {
  pi.registerCommand("pipiui_reload", {
    description: "Reload extensions, skills, prompts, themes, and context files (PipiUI internal)",
    handler: async (_args, ctx) => {
      await ctx.reload();
      ctx.ui.notify("Reloaded extensions, skills, prompts, and context files", "info");
    },
  });
}
"""#
}
