import Foundation

/// Pi extension: injects the Superpowers instructions that match the active model's tier,
/// and gates the first dispatch of a weak-model session until an SOP has been read.
///
/// Why `before_agent_start` may rewrite the system prompt here (unlike `GitExtension`):
/// the injected text is a pure function of the active model, so it is byte-identical turn
/// after turn and the cached prefix survives. It only changes when the user switches model
/// — and a model switch already invalidates the cache on its own, so the swap is free.
enum SkillTierExtension {
    static func install(into dir: URL) -> String? {
        let file = dir.appendingPathComponent("pipiui-skilltier.ts")
        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try source.write(to: file, atomically: true, encoding: .utf8)
            return file.path
        } catch {
            return nil
        }
    }

    private static let source = #"""
// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Model-tier aware Superpowers enforcement. Tiers come from Settings → 模型 (opt-in
// denylist of weak model ids); there is deliberately no built-in model table here.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

const STRONG_BLOCK = `

## Superpowers (reference)
The skill library is available but secondary. Consult a skill when you actually want its
SOP; do not pull T0/T1 work into brainstorming / writing-plans / subagent-driven-development.
verification-before-completion still binds at every level: no "done" without fresh evidence
from this round.`;

const WEAK_BLOCK = `

## Superpowers (mandatory for this model)
This session runs the skill library as a hard SOP, not a reference. Your own difficulty
triage tends to run low, so when in doubt, treat the task as the harder case.

- Anything past T1 — several files, unclear current state, a bug hunt, or work you cannot
  finish with one worker — requires reading the matching skill BEFORE you dispatch:
  vague requirement → brainstorming; multi-step work → writing-plans; execution →
  subagent-driven-development; defect → systematic-debugging; independent problems →
  dispatching-parallel-agents.
- Read the skill file itself; its path is listed in <available_skills>. Do not act on your
  recollection of what a skill says.
- Reading a skill costs one tool call. Skipping it costs a failed dispatch you then have to
  redo — when unsure whether a skill applies, read it.
- verification-before-completion binds every level: never claim or relay done / fixed /
  passing without fresh evidence you checked this round.
- Where skill docs say "dispatch subagent / Task tool", that is the \`subagent\` tool here
  (implementer → general-purpose, code review → reviewer).`;

/** Hot-read so a Settings toggle applies without restarting the session. */
function weakModelIds(): Set<string> {
  const file =
    process.env.PIPIUI_MODEL_TIERS_FILE ||
    path.join(os.homedir(), "Library/Application Support/PipiUI/model-tiers.json");
  try {
    const parsed = JSON.parse(fs.readFileSync(file, "utf-8")) as { weakModels?: unknown };
    const list = Array.isArray(parsed.weakModels)
      ? parsed.weakModels.filter((x): x is string => typeof x === "string")
      : [];
    return new Set(list);
  } catch {
    return new Set();
  }
}

/** Composite `provider/id`, matching Swift `ModelInfo.id` and what Settings stores. */
function modelKey(model: { provider?: string; id?: string } | undefined | null): string | null {
  if (!model?.provider || !model?.id) return null;
  return `${model.provider}/${model.id}`;
}

function isWeak(model: { provider?: string; id?: string } | undefined | null): boolean {
  const key = modelKey(model);
  return key !== null && weakModelIds().has(key);
}

/** Skills live in `.../skills/<name>/SKILL.md`; a read of one counts as consulting it. */
function looksLikeSkillRead(toolName: string, input: unknown): boolean {
  if (toolName !== "read") return false;
  const p = (input as { path?: unknown } | undefined)?.path;
  if (typeof p !== "string") return false;
  return p.includes("/skills/") || p.endsWith("SKILL.md");
}

export default function (pi: ExtensionAPI) {
  let skillWasRead = false;
  let gateFired = false;

  pi.on("before_agent_start", (event, ctx) => {
    const block = isWeak(ctx.model) ? WEAK_BLOCK : STRONG_BLOCK;
    // Stable per model ⇒ cache-safe. Guard anyway so a re-entrant call cannot double it.
    if (event.systemPrompt.endsWith(block)) return;
    return { systemPrompt: `${event.systemPrompt}${block}` };
  });

  pi.on("tool_call", (event, ctx) => {
    if (looksLikeSkillRead(event.toolName, event.input)) {
      skillWasRead = true;
      return;
    }
    if (event.toolName !== "subagent") return;
    if (gateFired || skillWasRead || !isWeak(ctx.model)) return;
    // One shot only: the cost of a wrong guess is capped at a single round trip.
    gateFired = true;
    return {
      block: true,
      reason:
        "Blocked once (weak-model guard): this model is marked as a weak model in PipiUI and " +
        "no skill has been read in this session yet. Read the SOP that fits this task first — " +
        "paths are in <available_skills> (subagent-driven-development for implementation, " +
        "brainstorming or writing-plans for a vague requirement, systematic-debugging for a " +
        "defect). Then dispatch again: this guard fires once per session and will not block you " +
        "a second time.",
    };
  });
}
"""#
}
