import Foundation

/// Pi extension: injects the planning and verification guardrails that match the active
/// model's tier.
///
/// Why `before_agent_start` may rewrite the system prompt here (unlike `GitExtension`):
/// the injected text is a pure function of the active model, so it is byte-identical turn
/// after turn and the cached prefix survives. It only changes when the user switches model
/// — and a model switch already invalidates the cache on its own, so the swap is free.
enum SkillTierExtension {
    static func install(into dir: URL) -> String? {
        let file = dir.appendingPathComponent("pipiui-skilltier.ts")
        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try source.write(to: file, atomically: true, encoding: .utf8)
            return file.path
        } catch {
            return nil
        }
    }

    private static let source = #"""
// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Model-tier aware Superpowers enforcement. Tiers come from Settings → 模型 (opt-in
// denylist of weak model ids); there is deliberately no built-in model table here.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

const STRONG_BLOCK = `

## Superpowers (reference)
The skill library is available but secondary. Consult a skill when you actually want its
SOP; do not pull T0/T1 work into brainstorming / writing-plans / subagent-driven-development.
For code-changing T2/T3, the main Boss may either use writing-plans itself or dispatch the
existing lightweight plan subagent; choose whichever route is proportionate, review the
resulting plan, then automatically dispatch the appropriate general-purpose worker(s)
and validation/review. Never present an execution-mode menu or wait for user confirmation
about subagent versus current-session execution. verification-before-completion still
binds at every level: no "done" without fresh evidence from this round.`;

const WEAK_BLOCK = `

## Superpowers (weak-model guardrails)
Use these planning and verification guardrails; do not turn the entire skill library into
a mandatory SOP.

- For code-changing T2/T3, the main Boss MUST NOT read or invoke \`writing-plans\` or
  \`brainstorming\`. It MUST dispatch the existing lightweight \`plan\` subagent, review
  that result, then automatically dispatch the appropriate general-purpose worker(s)
  and validation/review. Never present an execution-mode menu or wait for user
  confirmation about subagent versus current-session execution.
- Other skills remain available when their specific SOP is genuinely useful; there is no
  first-dispatch skill-read gate.
- verification-before-completion binds every level: never claim or relay done / fixed /
  passing without fresh evidence you checked this round.
- Where skill docs say "dispatch subagent / Task tool", that is the \`subagent\` tool here
  (implementer → general-purpose, code review → reviewer).`;

/** Hot-read so a Settings toggle applies without restarting the session. */
function weakModelIds(): Set<string> {
  const file =
    process.env.PIPIUI_MODEL_TIERS_FILE ||
    path.join(os.homedir(), "Library/Application Support/PipiUI/model-tiers.json");
  try {
    const parsed = JSON.parse(fs.readFileSync(file, "utf-8")) as { weakModels?: unknown };
    const list = Array.isArray(parsed.weakModels)
      ? parsed.weakModels.filter((x): x is string => typeof x === "string")
      : [];
    return new Set(list);
  } catch {
    return new Set();
  }
}

/** Composite `provider/id`, matching Swift `ModelInfo.id` and what Settings stores. */
function modelKey(model: { provider?: string; id?: string } | undefined | null): string | null {
  if (!model?.provider || !model?.id) return null;
  return `${model.provider}/${model.id}`;
}

function isWeak(model: { provider?: string; id?: string } | undefined | null): boolean {
  const key = modelKey(model);
  return key !== null && weakModelIds().has(key);
}

export default function (pi: ExtensionAPI) {
  pi.on("before_agent_start", (event, ctx) => {
    const block = isWeak(ctx.model) ? WEAK_BLOCK : STRONG_BLOCK;
    // Stable per model ⇒ cache-safe. Guard anyway so a re-entrant call cannot double it.
    if (event.systemPrompt.endsWith(block)) return;
    return { systemPrompt: `${event.systemPrompt}${block}` };
  });
}
"""#
}
