import Foundation

/// Pi extension: `web_search` (Firecrawl keyless search) + `web_fetch` (URL content extraction).
/// Written to Application Support at launch and loaded via `pi -e <path>`.
enum WebSearchExtension {
    static func install(into dir: URL) -> String? {
        let file = dir.appendingPathComponent("pipiui-websearch.ts")
        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try source.write(to: file, atomically: true, encoding: .utf8)
            return file.path
        } catch {
            return nil
        }
    }

    private static let source = #"""
// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Universal web search + fetch tools for models without native internet access.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

interface WebSearchConfig {
  backend: string;
}

// Firecrawl keyless search is the only backend (api.firecrawl.dev/v2/search,
// no API key required). The legacy config file is kept read for compatibility
// but its backend value is ignored — always "firecrawl".
function loadConfig(): WebSearchConfig {
  return { backend: "firecrawl" };
}

// ---------------------------------------------------------------------------
// Native search gating
// ---------------------------------------------------------------------------

function hasNativeSearch(model: { provider?: string; id?: string } | undefined): boolean {
  const p = (model?.provider || "").toLowerCase();
  const id = (model?.id || "").toLowerCase();
  if (p === "xai" || p.includes("grok") || id.includes("grok")) return true;
  if (p.includes("zai") || p.includes("zhipu") || p.includes("bigmodel") || id.includes("glm")) return true;
  // Official ChatGPT Codex Responses — hosted web_search via CodexServerToolsExtension.
  if (p === "openai-codex" || p.includes("openai-codex")) return true;
  // Official Anthropic Claude — server web_search via ClaudeServerToolsExtension.
  if (p === "anthropic" || p.includes("anthropic") || p.includes("claude")) return true;
  return false;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function text(t: string, isError = false) {
  return {
    content: [{ type: "text" as const, text: t }],
    details: {},
    ...(isError ? { isError: true } : {}),
  };
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  const cut = s.slice(0, max);
  const nl = cut.lastIndexOf("\n");
  return (nl > max * 0.8 ? cut.slice(0, nl) : cut) + "\n\n[truncated]";
}

interface SearchResult {
  title: string;
  url: string;
  snippet: string;
}

// ---------------------------------------------------------------------------
// Search backend: Firecrawl (keyless)
// ---------------------------------------------------------------------------

async function searchFirecrawl(query: string, maxResults: number): Promise<SearchResult[]> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 30000);
  try {
    const res = await fetch("https://api.firecrawl.dev/v2/search", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ query, limit: maxResults }),
      signal: controller.signal,
    });
    if (!res.ok) {
      throw new Error(`HTTP ${res.status}: ${(await res.text()).slice(0, 200)}`);
    }
    const data = (await res.json()) as any;
    if (!data || data.success !== true) {
      const msg = data?.error ? String(data.error) : "unexpected response shape";
      throw new Error(msg);
    }
    const web = data.data?.web;
    if (!Array.isArray(web)) return [];
    return web.slice(0, maxResults).map((r: any) => ({
      title: r.title || "",
      url: r.url || "",
      snippet: r.description || r.snippet || "",
    }));
  } catch (err: any) {
    throw new Error(err?.name === "AbortError" ? "request timed out (30s)" : err?.message || String(err));
  } finally {
    clearTimeout(timeout);
  }
}

// ---------------------------------------------------------------------------
// HTML utilities (for web_fetch). This deliberately small DOM-lite converter is
// a seam: a future bundled readability parser can replace extractMainContent.
// ---------------------------------------------------------------------------

const MAX_RESPONSE_BYTES = 5 * 1024 * 1024;
const VOID_TAGS = new Set(["area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"]);
const NOISE_TAGS = new Set(["script", "style", "noscript", "svg", "nav", "header", "footer", "aside"]);

function decodeEntities(s: string): string {
  return s.replace(/&(amp|lt|gt|quot|nbsp);|&#(x[0-9a-f]+|[0-9]+);/gi, (_all, named, numeric) => {
    if (named) return ({ amp: "&", lt: "<", gt: ">", quot: '"', nbsp: " " } as Record<string, string>)[named.toLowerCase()] || " ";
    const n = String(numeric).toLowerCase();
    const code = n.startsWith("x") ? parseInt(n.slice(1), 16) : parseInt(n, 10);
    return Number.isFinite(code) ? String.fromCodePoint(code) : " ";
  });
}

function tagName(token: string): string {
  return (token.match(/^<\/?\s*([a-z0-9:-]+)/i)?.[1] || "").toLowerCase();
}

function findContainer(html: string, matches: (token: string, name: string) => boolean): string | null {
  const tokens = /<!--[\s\S]*?-->|<[^>]*>/g;
  let match: RegExpExecArray | null;
  while ((match = tokens.exec(html))) {
    const token = match[0];
    const name = tagName(token);
    if (!name || /^<\//.test(token) || VOID_TAGS.has(name) || !matches(token, name)) continue;
    const start = tokens.lastIndex;
    let depth = 1;
    while ((match = tokens.exec(html))) {
      const nested = match[0];
      const nestedName = tagName(nested);
      if (!nestedName || VOID_TAGS.has(nestedName) || /^<!--/.test(nested)) continue;
      if (/^<\//.test(nested)) depth--;
      else if (!/\/>$/.test(nested)) depth++;
      if (depth === 0) return html.slice(start, match.index);
    }
    return null;
  }
  return null;
}

function htmlToMarkdown(fragment: string): string {
  const tokens = /<!--[\s\S]*?-->|<[^>]*>/g;
  let output = "";
  let cursor = 0;
  let suppressed = 0;
  let preDepth = 0;
  let codeDepth = 0;
  const lists: string[] = [];
  const links: string[] = [];
  const add = (s: string) => { output += s; };
  const block = () => { if (!output.endsWith("\n\n")) add("\n\n"); };
  const appendText = (value: string) => {
    if (suppressed) return;
    const decoded = decodeEntities(value);
    add(preDepth ? decoded : decoded.replace(/\s+/g, " "));
  };
  let match: RegExpExecArray | null;
  while ((match = tokens.exec(fragment))) {
    appendText(fragment.slice(cursor, match.index));
    cursor = tokens.lastIndex;
    const token = match[0];
    if (/^<!--/.test(token)) continue;
    const closing = /^<\//.test(token);
    const name = tagName(token);
    if (!name) continue;
    if (NOISE_TAGS.has(name)) { suppressed += closing ? -1 : 1; continue; }
    if (suppressed) continue;
    if (closing) {
      if (/^h[1-6]$/.test(name) || ["p", "div", "section", "article", "li", "blockquote"].includes(name)) block();
      if (name === "pre") { preDepth--; block(); }
      if (name === "code") codeDepth--;
      if (name === "ul" || name === "ol") lists.pop();
      if (name === "a") { const href = links.pop(); if (href) add(` (${href})`); }
      continue;
    }
    if (/^h[1-6]$/.test(name)) { block(); add("#".repeat(Number(name[1])) + " "); }
    else if (["p", "div", "section", "article"].includes(name)) block();
    else if (name === "br") add("\n");
    else if (name === "ul" || name === "ol") { block(); lists.push(name); }
    else if (name === "li") { add(`\n${lists[lists.length - 1] === "ol" ? "1." : "-"} `); }
    else if (name === "blockquote") { block(); add("> "); }
    else if (name === "pre") { block(); add("```\n"); preDepth++; }
    else if (name === "code" && !preDepth) { add("`"); codeDepth++; }
    else if (name === "a") { const href = token.match(/\bhref\s*=\s*["']([^"']+)["']/i)?.[1]; links.push(href || ""); }
  }
  appendText(fragment.slice(cursor));
  while (codeDepth-- > 0) add("`");
  while (preDepth-- > 0) add("\n```");
  return output.replace(/[ \t]+\n/g, "\n").replace(/\n{3,}/g, "\n\n").trim();
}

function extractRSCText(html: string): string {
  const chunks: string[] = [];
  const pushes = /self\.__next_f\.push\(([\s\S]*?)\);/g;
  let push: RegExpExecArray | null;
  while ((push = pushes.exec(html))) {
    const quoted = /"(?:\\.|[^"\\])*"/g;
    let item: RegExpExecArray | null;
    while ((item = quoted.exec(push[1]))) {
      try {
        const value = JSON.parse(item[0]) as string;
        const plain = htmlToMarkdown(value.replace(/\\n/g, "\n")).trim();
        if (plain.length > 2 && /[A-Za-z\u4e00-\u9fff]/.test(plain) &&
            !/(^|\s)(?:_next|webpack|static|chunk|layout|page|[a-f0-9]{16,})(\s|$)/i.test(plain) &&
            !/^[/\\$]/.test(plain)) chunks.push(plain);
      } catch { /* Ignore malformed payload fragments. */ }
    }
  }
  return [...new Set(chunks)].join("\n\n").replace(/\n{3,}/g, "\n\n").trim();
}

function extractMainContent(html: string): string {
  const titleMatch = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  const title = titleMatch ? htmlToMarkdown(titleMatch[1]) : "";
  const content =
    findContainer(html, (_token, name) => name === "article") ||
    findContainer(html, (_token, name) => name === "main") ||
    findContainer(html, (token) => /\brole\s*=\s*["']main["']/i.test(token)) ||
    html;
  let body = htmlToMarkdown(content);
  if (body.replace(/\s/g, "").length < 80) body = extractRSCText(html) || body;
  if (!body) return "";
  return title && !body.startsWith(`# ${title}`) ? `# ${title}\n\n${body}` : body;
}

async function readTextWithLimit(res: Response): Promise<string> {
  const declared = Number(res.headers.get("content-length") || 0);
  if (declared > MAX_RESPONSE_BYTES) throw new Error(`response exceeds ${MAX_RESPONSE_BYTES} byte limit`);
  if (!res.body) return "";
  const reader = res.body.getReader();
  const chunks: Uint8Array[] = [];
  let size = 0;
  try {
    while (true) {
      const next = await reader.read();
      if (next.done) break;
      size += next.value.byteLength;
      if (size > MAX_RESPONSE_BYTES) throw new Error(`response exceeds ${MAX_RESPONSE_BYTES} byte limit`);
      chunks.push(next.value);
    }
  } finally { reader.releaseLock(); }
  const joined = new Uint8Array(size);
  let offset = 0;
  for (const chunk of chunks) { joined.set(chunk, offset); offset += chunk.byteLength; }
  return new TextDecoder().decode(joined);
}

async function fetchGenericWebURL(parsed: URL, maxLength: number): Promise<string> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 30000);
  try {
    const res = await fetch(parsed.href, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
        Accept: "text/html,application/xhtml+xml,application/json,application/xml,text/plain;q=0.9,*/*;q=0.8",
      }, signal: controller.signal, redirect: "follow",
    });
    if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText || "response"}`);
    const raw = await readTextWithLimit(res);
    const extracted = /(?:text\/html|application\/xhtml\+xml)/i.test(res.headers.get("content-type") || "")
      ? extractMainContent(raw)
      : raw; // text/plain, JSON, and XML are intentionally returned directly in phase one.
    if (!extracted.trim()) throw new Error("page returned no extractable text content (possibly JS-rendered)");
    return truncate(extracted, maxLength);
  } catch (err: any) {
    throw new Error(err?.name === "AbortError" ? "request timed out (30s)" : err?.message || String(err));
  } finally { clearTimeout(timeout); }
}

// ---------------------------------------------------------------------------
// Tool registration
// ---------------------------------------------------------------------------

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "web_search",
    label: "Web Search",
    description:
      "Search the internet for current information, recent events, documentation, or any facts " +
      "beyond the local codebase. Uses Firecrawl keyless search (no API key required). " +
      "Returns titles, URLs, and snippets. Use web_fetch to read a specific result in full.",
    promptSnippet: "Search the web for current/external information",
    promptGuidelines: [
      "Use web_search when the user asks about recent events, external facts, or documentation not in the repo.",
      "Cite source URLs in your response after using web_search.",
      "Do not call web_search if your model already has native/built-in web search — use that instead.",
      "If your model has no native web search, prefer delegating the search to an explore subagent first; call web_search directly only when delegation is unavailable or has failed — it is the Firecrawl fallback.",
    ],
    parameters: Type.Object({
      query: Type.String({ description: "Search query (be specific for better results)." }),
      max_results: Type.Optional(
        Type.Number({ description: "Maximum number of results to return (default 5, max 100)." }),
      ),
      force: Type.Optional(
        Type.Boolean({
          description:
            "Run this tool even if your model is expected to have native search. Set it when a first call came back skipped and you have no working built-in search — that expectation is a guess from the model name and it can be wrong.",
        }),
      ),
    }),
    async execute(_id, params, _signal, _onUpdate, ctx) {
      // Gate: skip when the model is expected to carry native search, so a redundant generic
      // search is not paid for. The expectation is inferred from the provider and model name,
      // which is a guess: a relay that fronts grok or codex matches the name while the hosted
      // tools that would serve the search are not actually loaded. So the skip must never be
      // final — a caller that finds it has no built-in search retries with force and gets a
      // real answer, turning a wrong guess into one wasted round-trip rather than a worker with
      // no search at all that was told it had one.
      const model = ctx.model as { provider?: string; id?: string } | undefined;
      if (hasNativeSearch(model) && !params.force) {
        return text(
          "web_search skipped: this model is expected to have native server-side web search, " +
          "so use your built-in search first. That expectation is inferred from the model name " +
          "and can be wrong — if you have no working built-in search, call web_search again " +
          "with force: true and this tool will run.",
          true,
        );
      }

      const maxResults = Math.min(Math.max(Math.round(params.max_results || 5), 1), 100);
      const query = (params.query || "").trim();
      if (!query) return text("web_search: query is empty.", true);

      try {
        const results = await searchFirecrawl(query, maxResults);
        if (results.length === 0) {
          return text(`No results found for: ${query}`);
        }
        const lines = results.map(
          (r, i) => `${i + 1}. ${r.title}\n   ${r.url}\n   ${r.snippet}`,
        );
        return text(`Search results for "${query}" (firecrawl, ${results.length} results):\n\n${lines.join("\n\n")}`);
      } catch (err: any) {
        return text(`web_search failed (firecrawl): ${err?.message || String(err)}`, true);
      }
    },
  });

  pi.registerTool({
    name: "web_fetch",
    label: "Web Fetch",
    description:
      "Fetch a URL and return its main text content with navigation, ads, scripts, and other " +
      "non-content elements stripped. Useful for reading articles, documentation pages, GitHub " +
      "issues/PRs/discussions/wikis/releases, or any web page in full after finding it via web_search. " +
      "Use github_fetch instead for GitHub repository roots and /blob/ or /tree/ URLs.",
    promptSnippet: "Fetch a URL and extract its main text content",
    promptGuidelines: [
      "Use web_fetch to read a specific page found via web_search or provided by the user.",
      "Use github_fetch for GitHub repository roots and /blob/ or /tree/ URLs; use web_fetch for GitHub issues, pull requests, discussions, wikis, releases, and other rendered GitHub pages.",
      "The output is plain text with scripts/ads/nav removed; images are not included.",
    ],
    parameters: Type.Object({
      url: Type.String({ description: "Absolute URL to fetch (must start with http:// or https://)." }),
      max_length: Type.Optional(
        Type.Number({ description: "Maximum characters to return (default 20000)." }),
      ),
    }),
    async execute(_id, params) {
      const url = (params.url || "").trim();
      let parsed: URL;
      try { parsed = new URL(url); } catch { return text("web_fetch: url must be an absolute HTTP(S) URL.", true); }
      if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
        return text("web_fetch: url must be an absolute HTTP(S) URL.", true);
      }
      const maxLength = Math.min(Math.max(Math.round(params.max_length || 20000), 1000), 100000);
      try { return text(await fetchGenericWebURL(parsed, maxLength)); }
      catch (err: any) { return text(`web_fetch failed: ${err?.message || String(err)}`, true); }
    },
  });
}
"""#
}