import Foundation

/// Pi extension: `web_search` (Firecrawl keyless search) + `web_fetch` (URL content extraction).
/// Written to Application Support at launch and loaded via `pi -e <path>`.
enum WebSearchExtension {
    static func install(into dir: URL) -> String? {
        let file = dir.appendingPathComponent("pipiui-websearch.ts")
        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try source.write(to: file, atomically: true, encoding: .utf8)
            return file.path
        } catch {
            return nil
        }
    }

    private static let source = #"""
// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Universal web search + fetch tools for models without native internet access.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

interface WebSearchConfig {
  backend: string;
}

// Firecrawl keyless search is the only backend (api.firecrawl.dev/v2/search,
// no API key required). The legacy config file is kept read for compatibility
// but its backend value is ignored — always "firecrawl".
function loadConfig(): WebSearchConfig {
  return { backend: "firecrawl" };
}

// ---------------------------------------------------------------------------
// Native search gating
// ---------------------------------------------------------------------------

function hasNativeSearch(model: { provider?: string; id?: string } | undefined): boolean {
  const p = (model?.provider || "").toLowerCase();
  const id = (model?.id || "").toLowerCase();
  if (p === "xai" || p.includes("grok") || id.includes("grok")) return true;
  if (p.includes("zai") || p.includes("zhipu") || p.includes("bigmodel") || id.includes("glm")) return true;
  // Official ChatGPT Codex Responses — hosted web_search via CodexServerToolsExtension.
  if (p === "openai-codex" || p.includes("openai-codex")) return true;
  // Official Anthropic Claude — server web_search via ClaudeServerToolsExtension.
  if (p === "anthropic" || p.includes("anthropic") || p.includes("claude")) return true;
  return false;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function text(t: string, isError = false) {
  return {
    content: [{ type: "text" as const, text: t }],
    details: {},
    ...(isError ? { isError: true } : {}),
  };
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  const cut = s.slice(0, max);
  const nl = cut.lastIndexOf("\n");
  return (nl > max * 0.8 ? cut.slice(0, nl) : cut) + "\n\n[truncated]";
}

interface SearchResult {
  title: string;
  url: string;
  snippet: string;
}

// ---------------------------------------------------------------------------
// Search backend: Firecrawl (keyless)
// ---------------------------------------------------------------------------

async function searchFirecrawl(query: string, maxResults: number): Promise<SearchResult[]> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 30000);
  try {
    const res = await fetch("https://api.firecrawl.dev/v2/search", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ query, limit: maxResults }),
      signal: controller.signal,
    });
    if (!res.ok) {
      throw new Error(`HTTP ${res.status}: ${(await res.text()).slice(0, 200)}`);
    }
    const data = (await res.json()) as any;
    if (!data || data.success !== true) {
      const msg = data?.error ? String(data.error) : "unexpected response shape";
      throw new Error(msg);
    }
    const web = data.data?.web;
    if (!Array.isArray(web)) return [];
    return web.slice(0, maxResults).map((r: any) => ({
      title: r.title || "",
      url: r.url || "",
      snippet: r.description || r.snippet || "",
    }));
  } catch (err: any) {
    throw new Error(err?.name === "AbortError" ? "request timed out (30s)" : err?.message || String(err));
  } finally {
    clearTimeout(timeout);
  }
}

// ---------------------------------------------------------------------------
// HTML utilities (for web_fetch)
// ---------------------------------------------------------------------------

function stripTags(html: string): string {
  return html.replace(/<[^>]*>/g, "");
}

function decodeEntities(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#x27;/g, "'")
    .replace(/&#x2F;/g, "/")
    .replace(/&nbsp;/g, " ");
}

function extractMainContent(html: string): string {
  // Remove non-content elements
  let cleaned = html
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<style[\s\S]*?<\/style>/gi, "")
    .replace(/<noscript[\s\S]*?<\/noscript>/gi, "")
    .replace(/<svg[\s\S]*?<\/svg>/gi, "")
    .replace(/<nav[\s\S]*?<\/nav>/gi, "")
    .replace(/<footer[\s\S]*?<\/footer>/gi, "")
    .replace(/<header[\s\S]*?<\/header>/gi, "")
    .replace(/<aside[\s\S]*?<\/aside>/gi, "")
    .replace(/<!--[\s\S]*?-->/g, "");

  // Try to find main content container
  const articleMatch = cleaned.match(/<article[^>]*>([\s\S]*?)<\/article>/i);
  const mainMatch = cleaned.match(/<main[^>]*>([\s\S]*?)<\/main>/i);
  const roleMainMatch = cleaned.match(/<[^>]+role="main"[^>]*>([\s\S]*?)<\/(?:div|section|article)>/i);

  const content = articleMatch?.[1] || mainMatch?.[1] || roleMainMatch?.[1] || cleaned;

  // Extract title
  const titleMatch = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  const title = titleMatch ? stripTags(titleMatch[1]).trim() : "";

  // Convert to text: preserve block structure
  let text = content
    .replace(/<\/(?:p|div|h[1-6]|li|tr|blockquote|section|article|pre)>/gi, "\n")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<[^>]*>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#x27;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/[ \t]+/g, " ")
    .replace(/\n[ \t]+/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  if (title) text = `# ${title}\n\n${text}`;
  return text;
}

// ---------------------------------------------------------------------------
// Tool registration
// ---------------------------------------------------------------------------

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "web_search",
    label: "Web Search",
    description:
      "Search the internet for current information, recent events, documentation, or any facts " +
      "beyond the local codebase. Uses Firecrawl keyless search (no API key required). " +
      "Returns titles, URLs, and snippets. Use web_fetch to read a specific result in full.",
    promptSnippet: "Search the web for current/external information",
    promptGuidelines: [
      "Use web_search when the user asks about recent events, external facts, or documentation not in the repo.",
      "Cite source URLs in your response after using web_search.",
      "Do not call web_search if your model already has native/built-in web search — use that instead.",
    ],
    parameters: Type.Object({
      query: Type.String({ description: "Search query (be specific for better results)." }),
      max_results: Type.Optional(
        Type.Number({ description: "Maximum number of results to return (default 5, max 100)." }),
      ),
      force: Type.Optional(
        Type.Boolean({
          description:
            "Run this tool even if your model is expected to have native search. Set it when a first call came back skipped and you have no working built-in search — that expectation is a guess from the model name and it can be wrong.",
        }),
      ),
    }),
    async execute(_id, params, _signal, _onUpdate, ctx) {
      // Gate: skip when the model is expected to carry native search, so a redundant generic
      // search is not paid for. The expectation is inferred from the provider and model name,
      // which is a guess: a relay that fronts grok or codex matches the name while the hosted
      // tools that would serve the search are not actually loaded. So the skip must never be
      // final — a caller that finds it has no built-in search retries with force and gets a
      // real answer, turning a wrong guess into one wasted round-trip rather than a worker with
      // no search at all that was told it had one.
      const model = ctx.model as { provider?: string; id?: string } | undefined;
      if (hasNativeSearch(model) && !params.force) {
        return text(
          "web_search skipped: this model is expected to have native server-side web search, " +
          "so use your built-in search first. That expectation is inferred from the model name " +
          "and can be wrong — if you have no working built-in search, call web_search again " +
          "with force: true and this tool will run.",
          true,
        );
      }

      const maxResults = Math.min(Math.max(Math.round(params.max_results || 5), 1), 100);
      const query = (params.query || "").trim();
      if (!query) return text("web_search: query is empty.", true);

      try {
        const results = await searchFirecrawl(query, maxResults);
        if (results.length === 0) {
          return text(`No results found for: ${query}`);
        }
        const lines = results.map(
          (r, i) => `${i + 1}. ${r.title}\n   ${r.url}\n   ${r.snippet}`,
        );
        return text(`Search results for "${query}" (firecrawl, ${results.length} results):\n\n${lines.join("\n\n")}`);
      } catch (err: any) {
        return text(`web_search failed (firecrawl): ${err?.message || String(err)}`, true);
      }
    },
  });

  pi.registerTool({
    name: "web_fetch",
    label: "Web Fetch",
    description:
      "Fetch a URL and return its main text content with navigation, ads, scripts, and other " +
      "non-content elements stripped. Useful for reading articles, documentation pages, or any " +
      "web page in full after finding it via web_search. Returns plain text (markdown-like).",
    promptSnippet: "Fetch a URL and extract its main text content",
    promptGuidelines: [
      "Use web_fetch to read a specific page found via web_search or provided by the user.",
      "The output is plain text with scripts/ads/nav removed; images are not included.",
    ],
    parameters: Type.Object({
      url: Type.String({ description: "Absolute URL to fetch (must start with http:// or https://)." }),
      max_length: Type.Optional(
        Type.Number({ description: "Maximum characters to return (default 20000)." }),
      ),
    }),
    async execute(_id, params) {
      const url = (params.url || "").trim();
      if (!url || (!url.startsWith("http://") && !url.startsWith("https://"))) {
        return text("web_fetch: url must be an absolute HTTP(S) URL.", true);
      }
      const maxLength = Math.min(Math.max(Math.round(params.max_length || 20000), 1000), 100000);

      try {
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 30000);
        const res = await fetch(url, {
          headers: {
            "User-Agent":
              "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
            Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
          },
          signal: controller.signal,
          redirect: "follow",
        });
        clearTimeout(timeout);

        if (!res.ok) {
          return text(`web_fetch failed: HTTP ${res.status} ${res.statusText}`, true);
        }

        const contentType = res.headers.get("content-type") || "";
        if (!contentType.includes("text/html") && !contentType.includes("text/plain") && !contentType.includes("application/xhtml")) {
          // For non-HTML (JSON, XML, etc.) return raw text
          const raw = await res.text();
          return text(truncate(raw, maxLength));
        }

        const html = await res.text();
        const extracted = extractMainContent(html);
        if (!extracted.trim()) {
          return text("web_fetch: page returned no extractable text content.", true);
        }
        return text(truncate(extracted, maxLength));
      } catch (err: any) {
        const msg = err?.name === "AbortError" ? "request timed out (30s)" : err?.message || String(err);
        return text(`web_fetch failed: ${msg}`, true);
      }
    },
  });
}
"""#
}