import Foundation

/// The pi extension that exposes the in-app WebView as browser_* tools.
/// Written to Application Support at launch and loaded via `pi -e <path>`.
enum WebviewExtension {
    static func install(into dir: URL) -> String? {
        let file = dir.appendingPathComponent("pipiui-webview.ts")
        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try source.write(to: file, atomically: true, encoding: .utf8)
            return file.path
        } catch {
            return nil
        }
    }

    private static let source = #"""
// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Exposes the Pipi UI in-app WebView as browser_* tools via a local HTTP bridge.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

const PORT = process.env.PIPIUI_BRIDGE_PORT;
const KEY = process.env.PIPIUI_SESSION_KEY;

async function bridge(action: string, params: Record<string, unknown> = {}): Promise<any> {
  const res = await fetch(`http://127.0.0.1:${PORT}/rpc`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ sessionKey: KEY, action, ...params }),
  });
  const json: any = await res.json();
  if (!json.ok) throw new Error(json.error || `bridge action ${action} failed`);
  return json;
}

function text(t: string) {
  return { content: [{ type: "text" as const, text: t }], details: {} };
}

// Full parameter docs live here, not in the tool schema: help text is delivered as a
// tool result, which appends to the conversation instead of rewriting the cached
// prefix. See docs/progressive-disclosure.md.
const HELP = [
  "browser actions:",
  "",
  "navigate {url}          Open a URL in the panel and wait for load. Scheme optional;",
  "                        localhost defaults to http. Returns final URL + title.",
  "content {mode?}         Page content. mode='text' (default) visible text, 'html' full DOM.",
  "eval {js}               Evaluate JS in the current page; returns the JSON-stringified result.",
  "                        Use for DOM inspection, triggering clicks, reading state.",
  "console {clear?}        Console output (log/info/warn/error), JS exceptions and failed",
  "                        navigations since the last clear. clear=true empties the buffer.",
  "screenshot              Screenshot of the current page, returned as an image you can look at.",
  "help                    This text.",
].join("\n");

export default function (pi: ExtensionAPI) {
  if (!PORT || !KEY) return; // Not running inside Pipi UI; stay dormant.

  // One stable tool instead of five browser_* tools. The tool set never changes, so the
  // prompt prefix stays cached, and the per-request schema cost drops ~400 tokens.
  pi.registerTool({
    name: "browser",
    label: "Browser",
    description:
      "Drive the built-in WebView panel to test web pages. " +
      "actions: navigate{url}, content{mode?}, eval{js}, console{clear?}, screenshot, help. " +
      'Call with action:"help" for full parameter docs.',
    parameters: Type.Object({
      action: Type.String({
        description: "navigate | content | eval | console | screenshot | help",
      }),
      url: Type.Optional(Type.String()),
      js: Type.Optional(Type.String()),
      mode: Type.Optional(Type.Union([Type.Literal("text"), Type.Literal("html")])),
      clear: Type.Optional(Type.Boolean()),
    }),
    async execute(_id, params) {
      switch (params.action) {
        case "navigate": {
          if (!params.url) return text('browser navigate requires "url".\n\n' + HELP);
          const r = await bridge("navigate", { url: params.url });
          const note = r.note ? `\nnote: ${r.note}` : "";
          return text(`Loaded: ${r.url}\nTitle: ${r.title}${note}`);
        }
        case "content": {
          const r = await bridge("content", { mode: params.mode ?? "text" });
          const suffix = r.truncated ? "\n\n[content truncated at 100000 chars]" : "";
          return text((r.content || "(empty page)") + suffix);
        }
        case "eval": {
          if (!params.js) return text('browser eval requires "js".\n\n' + HELP);
          const r = await bridge("eval", { js: params.js });
          return text(String(r.result ?? "undefined"));
        }
        case "console": {
          const r = await bridge("console", { clear: params.clear ?? false });
          const logs: string[] = r.logs || [];
          return text(logs.length ? logs.join("\n") : "(console is empty)");
        }
        case "screenshot": {
          const r = await bridge("screenshot");
          return {
            content: [{ type: "image" as const, data: r.base64, mimeType: r.mimeType || "image/png" }],
            details: {},
          };
        }
        case "help":
          return text(HELP);
        default:
          return text(`Unknown browser action "${params.action}".\n\n${HELP}`);
      }
    },
  });
}
"""#
}
