import Foundation

/// The pi extension that exposes the in-app WebView as browser_* tools.
/// Written to Application Support at launch and loaded via `pi -e <path>`.
enum WebviewExtension {
    static func install(into dir: URL) -> String? {
        let file = dir.appendingPathComponent("pipiui-webview.ts")
        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try source.write(to: file, atomically: true, encoding: .utf8)
            return file.path
        } catch {
            return nil
        }
    }

    private static let source = #"""
// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Exposes the Pipi UI in-app WebView as browser_* tools via a local HTTP bridge.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

const PORT = process.env.PIPIUI_BRIDGE_PORT;
const KEY = process.env.PIPIUI_SESSION_KEY;

async function bridge(action: string, params: Record<string, unknown> = {}): Promise<any> {
  const res = await fetch(`http://127.0.0.1:${PORT}/rpc`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ sessionKey: KEY, action, ...params }),
  });
  const json: any = await res.json();
  if (!json.ok) throw new Error(json.error || `bridge action ${action} failed`);
  return json;
}

function text(t: string) {
  return { content: [{ type: "text" as const, text: t }], details: {} };
}

export default function (pi: ExtensionAPI) {
  if (!PORT || !KEY) return; // Not running inside Pipi UI; stay dormant.

  pi.registerTool({
    name: "browser_navigate",
    label: "Browser Navigate",
    description:
      "Navigate the built-in WebView panel to a URL and wait for the page to load. " +
      "Use this to open a local dev server (e.g. http://localhost:3000) or any page you need to test. " +
      "Returns the final URL and page title.",
    parameters: Type.Object({
      url: Type.String({ description: "URL to open. Scheme optional; localhost defaults to http." }),
    }),
    async execute(_id, params) {
      const r = await bridge("navigate", { url: params.url });
      const note = r.note ? `\nnote: ${r.note}` : "";
      return text(`Loaded: ${r.url}\nTitle: ${r.title}${note}`);
    },
  });

  pi.registerTool({
    name: "browser_eval",
    label: "Browser Eval JS",
    description:
      "Execute JavaScript in the built-in WebView's current page and return the result " +
      "(JSON-stringified when possible). Use for DOM inspection, triggering clicks, reading state.",
    parameters: Type.Object({
      js: Type.String({ description: "JavaScript expression or IIFE to evaluate in the page" }),
    }),
    async execute(_id, params) {
      const r = await bridge("eval", { js: params.js });
      return text(String(r.result ?? "undefined"));
    },
  });

  pi.registerTool({
    name: "browser_content",
    label: "Browser Page Content",
    description:
      "Get the built-in WebView's current page content. mode='text' returns visible text (default), " +
      "mode='html' returns the full serialized DOM.",
    parameters: Type.Object({
      mode: Type.Optional(Type.Union([Type.Literal("text"), Type.Literal("html")])),
    }),
    async execute(_id, params) {
      const r = await bridge("content", { mode: params.mode ?? "text" });
      const suffix = r.truncated ? "\n\n[content truncated at 100000 chars]" : "";
      return text((r.content || "(empty page)") + suffix);
    },
  });

  pi.registerTool({
    name: "browser_console",
    label: "Browser Console Logs",
    description:
      "Read console output (log/info/warn/error), JS exceptions and failed navigations captured from " +
      "the built-in WebView since the last clear. Set clear=true to clear the buffer after reading.",
    parameters: Type.Object({
      clear: Type.Optional(Type.Boolean()),
    }),
    async execute(_id, params) {
      const r = await bridge("console", { clear: params.clear ?? false });
      const logs: string[] = r.logs || [];
      return text(logs.length ? logs.join("\n") : "(console is empty)");
    },
  });

  pi.registerTool({
    name: "browser_screenshot",
    label: "Browser Screenshot",
    description:
      "Take a screenshot of the built-in WebView's current page and return it as an image " +
      "you can look at. Use to visually verify layout and styling.",
    parameters: Type.Object({}),
    async execute() {
      const r = await bridge("screenshot");
      return {
        content: [{ type: "image" as const, data: r.base64, mimeType: r.mimeType || "image/png" }],
        details: {},
      };
    },
  });
}
"""#
}
