import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { MemoryCatalog } from "../src/memory-catalog.ts";
import { MemoryCurator } from "../src/memory-curator.ts";

async function fixture() { return mkdtemp(join(tmpdir(), "pipiui-curator-")); }
const hermes = { add: async () => ({ id: "h" }), verify: async () => true };
async function candidate(c: MemoryCatalog, claim = "Repository rule: run tests before merge", kind: "semantic" | "procedural" = "semantic") { return c.upsert({ kind, claim, scope: { kind: "project", project: "/repo" }, evidence: [{ summary: kind === "procedural" ? "conditions: clean tree; steps: run test; pitfalls: stale build; verification: tests passed" : "authoritative repo rule with verified command evidence" }], sourceRuns: kind === "procedural" ? ["verified:a", "verified:b"] : ["verified:a"] }); }
function reviewer(decision: unknown) { return { review: async () => decision }; }
const approved = (decision: string, targetID?: string) => ({ decision, kind: "semantic", claim: "Repository rule: run tests before merge", confidence: .9, reason: "authoritative rule and verified command evidence", evidenceRefs: ["e1"], ...(targetID ? { targetID } : {}) });

test("Main-only, strict review schema, timeout, Computer, and audit redaction fail closed", async () => { const dir = await fixture(); try { const c = await MemoryCatalog.open(dir); const r = await candidate(c); assert.equal(MemoryCurator.create({ mode: "worker", catalog: c, hermes, reviewer: reviewer(approved("promote")) }), undefined); const invalid = MemoryCurator.create({ mode: "main", catalog: c, hermes, reviewer: reviewer({ decision: "promote" }) })!; await invalid.runBatch(); assert.equal(c.get(r.id)?.status, "candidate"); const slow = MemoryCurator.create({ mode: "main", catalog: c, hermes, reviewer: { review: async () => new Promise(() => {}) }, timeoutMs: 1 })!; await slow.runBatch(); assert.equal(c.get(r.id)?.status, "candidate"); const computer = await c.upsert({ kind: "semantic", claim: "Computer recipe", scope: { kind: "project", project: "/repo" }, evidence: [{ summary: "safe", computer: { actionKinds: ["click"] } }], sourceRuns: ["verified:c"] }); await invalid.runBatch(); assert.equal(c.get(computer.id)?.status, "candidate"); } finally { await rm(dir, { recursive: true }); } });

test("promote, merge, supersede, tombstone, and bounded batches preserve lifecycle history", async () => { const dir = await fixture(); try { const c = await MemoryCatalog.open(dir); const first = await candidate(c); const curator = MemoryCurator.create({ mode: "main", catalog: c, hermes, reviewer: reviewer(approved("promote")), batchSize: 99 })!; await curator.runBatch(); assert.equal(c.get(first.id)?.status, "active"); const duplicate = await c.upsert({ kind: "semantic", claim: "Another verified rule", scope: { kind: "project", project: "/repo" }, evidence: [{ summary: "evidence" }], sourceRuns: ["run-b"] }); const merge = MemoryCurator.create({ mode: "main", catalog: c, hermes, reviewer: reviewer(approved("merge", first.id)) })!; await merge.runBatch(); assert.deepEqual(c.get(first.id)?.sourceRuns, ["run-b", "verified:a"]); assert.equal(c.get(duplicate.id)?.status, "rejected"); const successor = await c.upsert({ kind: "semantic", claim: "New verified rule", scope: { kind: "project", project: "/repo" }, evidence: [{ summary: "evidence" }], sourceRuns: ["verified:new"] }); const supersede = MemoryCurator.create({ mode: "main", catalog: c, hermes, reviewer: reviewer(approved("supersede", first.id)) })!; await supersede.runBatch(); assert.equal(c.get(successor.id)?.status, "active"); assert.equal(c.get(first.id)?.status, "superseded"); await c.transition(successor.id, "deleted"); assert.equal((await c.upsert({ kind: "semantic", claim: successor.claim, scope: successor.scope })).status, "deleted"); } finally { await rm(dir, { recursive: true }); } });
