// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Chat-mode image tools: image_gen + image_edit (Grok Imagine REST / Coding Relay).
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

const OFFICIAL_V1 = "https://api.x.ai/v1";
const OFFICIAL_MODEL = "grok-imagine-image-2.0";
const RELAY_MODEL = "grok-imagine-image-quality";

const ALLOWED_ASPECT = new Set([
  "1:1",
  "16:9",
  "9:16",
  "4:3",
  "3:4",
  "3:2",
  "2:3",
  "2:1",
  "1:2",
  "19.5:9",
  "9:19.5",
  "20:9",
  "9:20",
  "auto",
]);

const CONFIRM_REFUSAL = [
  "refused: confirmed=false.",
  "",
  "How this tool is meant to be used:",
  "1. Confirm subject, style, and any reference images in chat first. Only then call again with confirmed=true.",
  "2. Tables, exact text, diagrams, and data charts should be generated with code — do not render them as images.",
  "3. If a safety review blocks the request, stop. Do not rewrite the prompt to bypass the review.",
  "4. For real people, use image_edit with a real reference photo. Do not use image_gen alone.",
  "5. Look up real-world facts first, then write them into the prompt. Do not invent them.",
  "6. Attachments live under .pi/attachments/. Never invent a path.",
].join("\n");

type ActiveModel = { provider?: string; id?: string; name?: string } | undefined;

type HttpError = Error & { status?: number };

type ImagineResult = {
  data: Buffer;
  mime: string;
  filePath: string;
  backend: string;
  model: string;
};

function clean(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim();
  return trimmed || undefined;
}

function asObject(value: unknown): Record<string, unknown> | undefined {
  return typeof value === "object" && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;
}

function isExpiredTimestamp(value: unknown): boolean {
  if (typeof value !== "number" || !Number.isFinite(value)) return false;
  const ms = value < 1e12 ? value * 1000 : value;
  return ms < Date.now();
}

function tokenFromXaiEntry(entry: Record<string, unknown> | undefined): string | undefined {
  if (!entry) return undefined;
  const access = clean(entry.access) ?? clean(entry.access_token);
  const key = clean(entry.key);
  if (access) {
    if (!isExpiredTimestamp(entry.expires)) return access;
    return key;
  }
  return key;
}

function readXaiTokenFromAuthFile(filePath: string): string | undefined {
  try {
    const root = asObject(JSON.parse(fs.readFileSync(filePath, "utf8")));
    return tokenFromXaiEntry(asObject(root?.xai));
  } catch {
    return undefined;
  }
}

/** Env key → PI_CODING_AGENT_DIR/auth.json → ~/.pi/agent/auth.json. Never log the value. */
function resolveXaiToken(): string | undefined {
  const fromEnv = clean(process.env.XAI_API_KEY);
  if (fromEnv) return fromEnv;
  const agentDir = clean(process.env.PI_CODING_AGENT_DIR);
  if (agentDir) {
    const fromAgent = readXaiTokenFromAuthFile(path.join(agentDir, "auth.json"));
    if (fromAgent) return fromAgent;
  }
  const home = clean(process.env.HOME) || os.homedir();
  return readXaiTokenFromAuthFile(path.join(home, ".pi", "agent", "auth.json"));
}

function redact(text: string, secret: string | undefined): string {
  if (!secret) return text;
  return text.split(secret).join("[redacted]");
}

function grokRelayBase(): string {
  return process.env.PIPIUI_GROK_RELAY || "http://127.0.0.1:18891/v1";
}

function codingRelayBase(): string {
  return process.env.PIPIUI_CODING_RELAY || "http://127.0.0.1:18888/v1";
}

function isGrokModel(model: ActiveModel): boolean {
  const p = (model?.provider || "").toLowerCase();
  const id = (model?.id || "").toLowerCase();
  return p.includes("grok") || p === "xai" || p.includes("xai") || id.includes("grok") || id.includes("xai");
}

function isGptModel(model: ActiveModel): boolean {
  const p = (model?.provider || "").toLowerCase();
  const id = (model?.id || "").toLowerCase();
  return (
    p.includes("coding") ||
    p.includes("openai") ||
    p.includes("codex") ||
    id.includes("gpt") ||
    id.includes("codex")
  );
}

function useCodingPath(model: ActiveModel): boolean {
  return isGptModel(model) && !isGrokModel(model);
}

function codingModelId(model: ActiveModel): string {
  const id = (model?.id || "").toLowerCase();
  if (id.includes("5.4")) return "gpt-5.4-high-image";
  if (id.includes("5.5")) return "gpt-5.5-high-image";
  if (id.includes("5.6")) return "gpt-5.6-high-image";
  return "gpt-5.6-high-image";
}

function normalizeAspect(value: unknown): string | undefined {
  const raw = clean(value);
  return raw && ALLOWED_ASPECT.has(raw) ? raw : undefined;
}

function attachmentsDir(cwd: string): string {
  const dir = path.join(cwd, ".pi", "attachments");
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function stampName(ext: string): string {
  return new Date().toISOString().replace(/[:.]/g, "-") + "." + ext;
}

function extForMime(mime: string): string {
  const m = mime.toLowerCase();
  if (m.includes("jpeg") || m.endsWith("/jpg") || m.endsWith(".jpg")) return "jpg";
  if (m.includes("webp")) return "webp";
  if (m.includes("gif")) return "gif";
  return "png";
}

function resolveRef(input: string, cwd: string): string | null {
  const raw = input.trim();
  if (!raw) return null;
  if (/^data:image\/[a-zA-Z0-9.+-]+;base64,/i.test(raw)) return raw;
  try {
    const abs = path.isAbsolute(raw) ? raw : path.resolve(cwd, raw);
    const buf = fs.readFileSync(abs);
    const ext = path.extname(abs).toLowerCase();
    const mime =
      ext === ".jpg" || ext === ".jpeg"
        ? "image/jpeg"
        : ext === ".webp"
          ? "image/webp"
          : ext === ".gif"
            ? "image/gif"
            : "image/png";
    return `data:${mime};base64,${buf.toString("base64")}`;
  } catch {
    return null;
  }
}

function collectRawRefs(image: unknown, referencePaths: unknown): string[] {
  const out: string[] = [];
  const push = (value: unknown) => {
    if (typeof value === "string" && value.trim()) out.push(value.trim());
  };
  if (Array.isArray(image)) image.forEach(push);
  else push(image);
  if (Array.isArray(referencePaths)) referencePaths.forEach(push);
  else push(referencePaths);
  return out;
}

function resolveRefs(image: unknown, referencePaths: unknown, cwd: string): string[] {
  const resolved: string[] = [];
  for (const raw of collectRawRefs(image, referencePaths)) {
    const uri = resolveRef(raw, cwd);
    if (!uri) continue;
    resolved.push(uri);
    if (resolved.length >= 3) break;
  }
  return resolved;
}

function cwdOf(ctx: { cwd?: unknown } | undefined): string {
  return typeof ctx?.cwd === "string" && ctx.cwd.trim() ? ctx.cwd : process.cwd();
}

async function postJSON(url: string, body: unknown, bearer: string): Promise<any> {
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: `Bearer ${bearer}`,
    },
    body: JSON.stringify(body),
  });
  const text = await res.text();
  let json: any;
  try {
    json = JSON.parse(text);
  } catch {
    const err = new Error(`HTTP ${res.status}: ${text.slice(0, 300)}`) as HttpError;
    err.status = res.status;
    throw err;
  }
  if (!res.ok) {
    const err = new Error(`HTTP ${res.status}: ${text.slice(0, 300)}`) as HttpError;
    err.status = res.status;
    throw err;
  }
  return json;
}

function extractDataUri(content: string): { mime: string; b64: string } | null {
  const m = content.match(/data:(image\/[a-zA-Z0-9.+-]+);base64,([A-Za-z0-9+/=\s]+)/);
  if (!m) return null;
  return { mime: m[1], b64: m[2].replace(/\s+/g, "") };
}

function saveImage(cwd: string, b64: string, mime: string): { data: Buffer; filePath: string; mime: string } {
  const data = Buffer.from(b64, "base64");
  const filePath = path.join(attachmentsDir(cwd), stampName(extForMime(mime)));
  fs.writeFileSync(filePath, data);
  return { data, filePath, mime };
}

function imagineBody(
  model: string,
  prompt: string,
  aspect: string | undefined,
  refs: string[] | undefined,
): Record<string, unknown> {
  const body: Record<string, unknown> = {
    model,
    prompt,
    n: 1,
    response_format: "b64_json",
  };
  if (aspect) body.aspect_ratio = aspect;
  if (refs && refs.length > 0) {
    body.image = { url: refs[0] };
    if (refs.length > 1) body.images = refs.map((url) => ({ url }));
  }
  return body;
}

function imageFromResponse(json: any, defaultMime: string): { b64: string; mime: string } {
  const item = json?.data?.[0];
  const b64 = item?.b64_json || item?.b64;
  if (!b64) throw new Error("response had no image");
  return { b64, mime: typeof item?.mime_type === "string" && item.mime_type ? item.mime_type : defaultMime };
}

async function grokImagine(
  prompt: string,
  aspect: string | undefined,
  refs: string[] | undefined,
  cwd: string,
  token: string | undefined,
): Promise<ImagineResult> {
  const relayBase = grokRelayBase();
  const pathSuffix = refs && refs.length > 0 ? "/images/edits" : "/images/generations";

  const once = async (
    base: string,
    bearer: string,
    model: string,
    backend: string,
    defaultMime: string,
  ): Promise<ImagineResult> => {
    const json = await postJSON(`${base}${pathSuffix}`, imagineBody(model, prompt, aspect, refs), bearer);
    const image = imageFromResponse(json, defaultMime);
    const saved = saveImage(cwd, image.b64, image.mime);
    return { ...saved, backend, model };
  };

  if (token) {
    try {
      return await once(OFFICIAL_V1, token, OFFICIAL_MODEL, "Grok Imagine", "image/jpeg");
    } catch (error) {
      const status = (error as HttpError)?.status;
      if (status === 401 || status === 403) {
        return await once(relayBase, "local", RELAY_MODEL, "Grok Imagine Relay", "image/png");
      }
      throw error;
    }
  }

  return await once(relayBase, "local", RELAY_MODEL, "Grok Imagine Relay", "image/png");
}

async function generateCodingChat(
  prompt: string,
  cwd: string,
  model: ActiveModel,
): Promise<ImagineResult> {
  const base = codingRelayBase();
  const modelId = codingModelId(model);
  const json = await postJSON(
    `${base}/chat/completions`,
    {
      model: modelId,
      messages: [{ role: "user", content: prompt }],
      stream: false,
    },
    "local",
  );
  let content = json?.choices?.[0]?.message?.content ?? "";
  if (Array.isArray(content)) {
    content = content.map((c: any) => c?.text || "").join("\n");
  }
  const uri = extractDataUri(String(content));
  if (!uri) throw new Error("chat response had no data:image (model may not have called image generation)");
  const saved = saveImage(cwd, uri.b64, uri.mime);
  return { ...saved, backend: `Coding Relay (${modelId})`, model: modelId };
}

function refusal() {
  return {
    content: [{ type: "text" as const, text: CONFIRM_REFUSAL }],
    details: {},
    isError: true,
  };
}

function fail(tool: string, error: unknown, token: string | undefined, hint?: string) {
  const message = redact(String((error as any)?.message || error), token);
  return {
    content: [
      {
        type: "text" as const,
        text: hint ? `${tool} failed: ${message}\n${hint}` : `${tool} failed: ${message}`,
      },
    ],
    details: {},
    isError: true,
  };
}

function success(result: ImagineResult) {
  return {
    content: [
      { type: "text" as const, text: result.filePath },
      {
        type: "image" as const,
        data: result.data.toString("base64"),
        mimeType: result.mime,
      },
    ],
    details: { path: result.filePath, backend: result.backend, model: result.model },
  };
}

const imageParam = Type.Union([Type.String(), Type.Array(Type.String())], {
  description: "Local path(s) or data URI(s) of reference images (max 3).",
});

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "image_gen",
    label: "Generate Image",
    description: "Generate an image after the user confirms subject and style. Returns the image and saved path.",
    promptSnippet: "Generate images after the user confirms",
    promptGuidelines: [
      "Confirm subject and style in chat first, then call image_gen with confirmed=true.",
    ],
    parameters: Type.Object({
      prompt: Type.String({ description: "Image description." }),
      confirmed: Type.Boolean({ description: "True only after the user confirmed in chat." }),
      aspect_ratio: Type.Optional(Type.String({ description: "Optional aspect ratio (invalid values are ignored)." })),
    }),
    async execute(_id, params, _signal, _onUpdate, ctx) {
      if (!params.confirmed) return refusal();
      const model = ctx.model as ActiveModel;
      const cwd = cwdOf(ctx);
      const aspect = normalizeAspect((params as { aspect_ratio?: unknown }).aspect_ratio);
      const token = resolveXaiToken();
      try {
        if (useCodingPath(model)) {
          return success(await generateCodingChat(params.prompt, cwd, model));
        }
        return success(await grokImagine(params.prompt, aspect, undefined, cwd, token));
      } catch (error) {
        return fail("image_gen", error, token);
      }
    },
  });

  pi.registerTool({
    name: "image_edit",
    label: "Edit Image",
    description: "Edit an image with up to 3 reference photos after the user confirms. Returns the image and saved path.",
    promptSnippet: "Edit images after the user confirms",
    promptGuidelines: [
      "Confirm subject, style, and reference images in chat first, then call image_edit with confirmed=true.",
    ],
    parameters: Type.Object({
      prompt: Type.String({ description: "Edit instruction." }),
      confirmed: Type.Boolean({ description: "True only after the user confirmed in chat." }),
      image: Type.Optional(imageParam),
      aspect_ratio: Type.Optional(Type.String({ description: "Optional aspect ratio (invalid values are ignored)." })),
      reference_paths: Type.Optional(
        Type.Union([Type.String(), Type.Array(Type.String())], {
          description: "Legacy alias for image; merged into the reference list.",
        }),
      ),
    }),
    async execute(_id, params, _signal, _onUpdate, ctx) {
      if (!params.confirmed) return refusal();
      const model = ctx.model as ActiveModel;
      const cwd = cwdOf(ctx);
      if (useCodingPath(model)) {
        return fail("image_edit", "image editing requires Grok Imagine", undefined);
      }
      const refs = resolveRefs(
        (params as { image?: unknown }).image,
        (params as { reference_paths?: unknown }).reference_paths,
        cwd,
      );
      if (refs.length === 0) {
        return fail("image_edit", "no readable reference image", undefined);
      }
      const aspect = normalizeAspect((params as { aspect_ratio?: unknown }).aspect_ratio);
      const token = resolveXaiToken();
      try {
        return success(await grokImagine(params.prompt, aspect, refs, cwd, token));
      } catch (error) {
        return fail("image_edit", error, token);
      }
    },
  });

  // No before_agent_start block: long-form rules come from confirmed=false.
}
