// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// xAI retired Live Search. A top-level `search_parameters` field on
// `/v1/chat/completions` now returns 410 Gone:
//   "Live search is deprecated. Please switch to the Agent Tools API"
// Docs: https://docs.x.ai/docs/guides/tools/overview
//
// Agent Tools (`web_search` / `x_search`) run on the Responses API. This host
// still speaks official xAI as openai-completions, so this extension only
// strips the retired field and leaves client/pi-web-access `web_search` in
// place. Do not re-inject `search_parameters`.
//
// It also captures api.x.ai's `x-ratelimit-*` response headers (the only
// programmatic quota signal left for SuperGrok/X Premium OAuth accounts) into
// `<agentDir>/grok-rate-limits.json` for the host's Grok 账号额度 pill.
import { renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

type CompletionsPayload = {
  model?: string;
  messages?: unknown;
  tools?: unknown[];
  [key: string]: unknown;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isXaiCompletionsModel(model: { provider?: string; api?: string } | undefined): boolean {
  if (!model) return false;
  const provider = (model.provider || "").toLowerCase();
  if (provider !== "xai") return false;
  return model.api === "openai-completions";
}

function isXaiCompletionsRequest(
  model: { provider?: string; api?: string } | undefined,
  payload: unknown,
): payload is CompletionsPayload {
  if (!isXaiCompletionsModel(model)) return false;
  if (!isRecord(payload)) return false;
  // Chat Completions uses `messages`; Responses uses `input`.
  return Array.isArray(payload.messages);
}

const RATE_LIMIT_WRITE_INTERVAL_MS = 30_000;
let lastRateLimitWriteMs = 0;

function headerValue(headers: Record<string, unknown>, name: string): string | undefined {
  const lower = name.toLowerCase();
  for (const [key, value] of Object.entries(headers)) {
    if (key.toLowerCase() === lower && typeof value === "string") return value;
  }
  return undefined;
}

/**
 * Persist the newest rate-limit numbers so the host quota pill can read them without a probe
 * request. Throttled: streaming turns fire this repeatedly with identical headers.
 */
function captureRateLimitHeaders(headers: Record<string, unknown> | undefined, now: number): void {
  const agentDir = process.env.PI_CODING_AGENT_DIR;
  const limitRequests = headerValue(headers ?? {}, "x-ratelimit-limit-requests");
  if (!agentDir || limitRequests === undefined) return;
  if (now - lastRateLimitWriteMs < RATE_LIMIT_WRITE_INTERVAL_MS) return;
  lastRateLimitWriteMs = now;
  const payload = {
    capturedAt: now,
    limitRequests: Number(limitRequests),
    remainingRequests: Number(headerValue(headers ?? {}, "x-ratelimit-remaining-requests")),
    limitTokens: Number(headerValue(headers ?? {}, "x-ratelimit-limit-tokens")),
    remainingTokens: Number(headerValue(headers ?? {}, "x-ratelimit-remaining-tokens")),
  };
  try {
    const target = join(agentDir, "grok-rate-limits.json");
    const temporary = `${target}.${process.pid}.tmp`;
    writeFileSync(temporary, `${JSON.stringify(payload)}\n`);
    renameSync(temporary, target);
  } catch {
    // Quota capture is best-effort; a failed write must never break the chat.
  }
}

export default function (pi: ExtensionAPI) {
  pi.on("before_provider_request", (event, ctx) => {
    const model = ctx.model;
    if (!isXaiCompletionsRequest(model, event.payload)) {
      return;
    }

    const payload = event.payload as CompletionsPayload;
    if (!Object.prototype.hasOwnProperty.call(payload, "search_parameters")) {
      return;
    }

    const next = { ...payload };
    delete next.search_parameters;
    return next;
  });

  pi.on("after_provider_response", (event, ctx) => {
    const model = ctx.model;
    // grok-relay and other relays report their own quota; only official api.x.ai headers count.
    if (model && model.provider.toLowerCase() !== "xai") return;
    captureRateLimitHeaders(event.headers, Date.now());
  });

  pi.registerCommand("xai-tools", {
    description: "Show whether xAI server-side search is active",
    handler: async (_args, ctx) => {
      const model = ctx.model;
      const active = isXaiCompletionsModel(model);
      const lines = [
        `model: ${model ? `${model.provider}/${model.id}` : "(none)"}`,
        `api: ${model?.api ?? "(none)"}`,
        "xAI Live Search: retired (search_parameters returns 410)",
        active
          ? "Use client web_search (pi-web-access). Do not send search_parameters."
          : "inactive (need xai + openai-completions)",
      ];
      ctx.ui.notify(lines.join("\n"), active ? "info" : "warning");
    },
  });
}
