// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Inject xAI's server-side search (search_parameters: {mode:"auto"}) into xai
// openai-completions (chat/completions) requests. xAI runs the search on its servers when
// enabled; the model decides automatically.
// Docs: https://docs.x.ai/docs/guides/search
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

// xAI's `/v1/chat/completions` accepts a top-level `search_parameters` object. `mode: "auto"`
// lets the model decide when to perform a server-side web search.
const GROK_SEARCH_PARAMETERS = { mode: "auto" } as const;

type CompletionsPayload = {
  model?: string;
  messages?: unknown;
  tools?: unknown[];
  [key: string]: unknown;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isXaiCompletionsModel(model: { provider?: string; api?: string } | undefined): boolean {
  if (!model) return false;
  const provider = (model.provider || "").toLowerCase();
  if (provider !== "xai") return false;
  return model.api === "openai-completions";
}

function isXaiCompletionsRequest(
  model: { provider?: string; api?: string } | undefined,
  payload: unknown,
): payload is CompletionsPayload {
  if (!isXaiCompletionsModel(model)) return false;
  if (!isRecord(payload)) return false;
  // Chat Completions uses `messages`; Responses uses `input`.
  return Array.isArray(payload.messages);
}

function isWebSearchTool(tool: Record<string, unknown>): boolean {
  const type = typeof tool.type === "string" ? tool.type : "";
  const fn = isRecord(tool.function) ? tool.function : undefined;
  const name = typeof tool.name === "string" ? tool.name : (typeof fn?.name === "string" ? fn.name : "");
  return type === "web_search" || name === "web_search";
}

function mergeServerTools(existing: unknown): unknown[] {
  const current = Array.isArray(existing) ? [...existing] : [];
  // Drop client/custom tools named/typed web_search so they don't collide with xAI's
  // server-side search. Keep fetch_content, browser_search and every other tool.
  return current.filter((tool) => {
    if (!isRecord(tool)) return true;
    return !isWebSearchTool(tool);
  });
}

export default function (pi: ExtensionAPI) {
  pi.on("before_provider_request", (event, ctx) => {
    const model = ctx.model;
    if (!isXaiCompletionsRequest(model, event.payload)) {
      return;
    }

    const payload = event.payload as CompletionsPayload;
    return {
      ...payload,
      tools: mergeServerTools(payload.tools),
      search_parameters: { ...GROK_SEARCH_PARAMETERS },
    };
  });

  pi.on("before_agent_start", (event, ctx) => {
    const model = ctx.model;
    if (!isXaiCompletionsModel(model)) {
      return;
    }

    const tip = [
      "",
      "## xAI server tools",
      "When the active model is official xAI Grok (`xai` / openai-completions), server-side search is enabled on every request:",
      "- `search` — live web search on xAI's servers (prefer over bash/curl for research)",
      "It executes automatically. Keep using local `read`/`bash`/`edit`/`write` for the workspace.",
    ].join("\n");

    if (event.systemPrompt.includes("## xAI server tools")) {
      return;
    }
    return {
      systemPrompt: `${event.systemPrompt}${tip}`,
    };
  });

  pi.registerCommand("xai-tools", {
    description: "Show whether xAI server-side search is active",
    handler: async (_args, ctx) => {
      const model = ctx.model;
      const active = isXaiCompletionsModel(model);
      const lines = [
        `model: ${model ? `${model.provider}/${model.id}` : "(none)"}`,
        `api: ${model?.api ?? "(none)"}`,
        `xAI server tools: ${active ? "ENABLED (search_parameters)" : "inactive (need xai + openai-completions)"}`,
      ];
      ctx.ui.notify(lines.join("\n"), active ? "info" : "warning");
    },
  });
}
