// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Chat-mode image generation: LLM confirms intent, then calls generate_image.
// Backends match Grok Build / local relays (not pi chat RPC).
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import * as fs from "node:fs";
import * as path from "node:path";

const GROK_V1 = process.env.PIPIUI_GROK_RELAY || "http://127.0.0.1:18891/v1";
const CODING_V1 = process.env.PIPIUI_CODING_RELAY || "http://127.0.0.1:18888/v1";

type ActiveModel = { provider?: string; id?: string; name?: string } | undefined;

function pickBackend(model: ActiveModel): {
  kind: "grok-rest" | "grok-edit" | "coding-chat";
  base: string;
  modelId: string;
  label: string;
} {
  const p = (model?.provider || "").toLowerCase();
  const id = (model?.id || "").toLowerCase();
  const isGrok =
    p.includes("grok") || p === "xai" || id.includes("grok");
  const isGpt =
    p.includes("coding") ||
    p.includes("openai") ||
    p.includes("codex") ||
    id.includes("gpt") ||
    id.includes("codex");

  if (isGpt && !isGrok) {
    // Prefer high image suffix; relay strips unknown effort parts.
    let modelId = "gpt-5.6-high-image";
    if (id.includes("5.4")) modelId = "gpt-5.4-high-image";
    else if (id.includes("5.5")) modelId = "gpt-5.5-high-image";
    else if (id.includes("5.6")) modelId = "gpt-5.6-high-image";
    return {
      kind: "coding-chat",
      base: CODING_V1,
      modelId,
      label: `Coding Relay (${modelId})`,
    };
  }

  return {
    kind: "grok-rest",
    base: GROK_V1,
    modelId: "grok-imagine-image-quality",
    label: "Grok Imagine REST",
  };
}

function attachmentsDir(cwd: string): string {
  const dir = path.join(cwd, ".pi", "attachments");
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function stampName(ext: string): string {
  return new Date().toISOString().replace(/[:.]/g, "-") + "." + ext;
}

function readRefAsDataURI(filePath: string): string | null {
  try {
    const abs = path.isAbsolute(filePath) ? filePath : path.resolve(filePath);
    const buf = fs.readFileSync(abs);
    const ext = path.extname(abs).toLowerCase();
    const mime =
      ext === ".jpg" || ext === ".jpeg"
        ? "image/jpeg"
        : ext === ".webp"
          ? "image/webp"
          : ext === ".gif"
            ? "image/gif"
            : "image/png";
    return `data:${mime};base64,${buf.toString("base64")}`;
  } catch {
    return null;
  }
}

async function postJSON(url: string, body: unknown): Promise<any> {
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: "Bearer local",
    },
    body: JSON.stringify(body),
  });
  const text = await res.text();
  let json: any;
  try {
    json = JSON.parse(text);
  } catch {
    throw new Error(`HTTP ${res.status}: ${text.slice(0, 300)}`);
  }
  if (!res.ok) {
    throw new Error(`HTTP ${res.status}: ${text.slice(0, 300)}`);
  }
  return json;
}

function extractDataUri(content: string): { mime: string; b64: string } | null {
  const m = content.match(/data:(image\/[a-zA-Z0-9.+-]+);base64,([A-Za-z0-9+/=\s]+)/);
  if (!m) return null;
  return { mime: m[1], b64: m[2].replace(/\s+/g, "") };
}

async function generateGrokRest(
  base: string,
  modelId: string,
  prompt: string,
  refs: string[],
  cwd: string,
): Promise<{ data: Buffer; mime: string; filePath: string; via: string }> {
  if (refs.length > 0) {
    // Image edit / i2i
    const images = refs
      .map(readRefAsDataURI)
      .filter((x): x is string => !!x)
      .map((url) => ({ url }));
    if (images.length === 0) throw new Error("reference_paths 无法读取");
    const body: any = {
      model: modelId,
      prompt,
      n: 1,
      response_format: "b64_json",
      image: images[0],
    };
    if (images.length > 1) body.images = images;
    let json: any;
    try {
      json = await postJSON(`${base}/images/edits`, body);
    } catch {
      // Fallback: some relays only expose generations with image field
      json = await postJSON(`${base}/images/generations`, {
        model: modelId,
        prompt,
        n: 1,
        response_format: "b64_json",
        image: images[0],
      });
    }
    const b64 = json?.data?.[0]?.b64_json || json?.data?.[0]?.b64;
    if (!b64) throw new Error("edit 响应无图片");
    const data = Buffer.from(b64, "base64");
    const filePath = path.join(attachmentsDir(cwd), stampName("png"));
    fs.writeFileSync(filePath, data);
    return { data, mime: "image/png", filePath, via: `${base}/images/edits` };
  }

  const json = await postJSON(`${base}/images/generations`, {
    model: modelId,
    prompt,
    n: 1,
    response_format: "b64_json",
  });
  const b64 = json?.data?.[0]?.b64_json || json?.data?.[0]?.b64;
  if (!b64) throw new Error("generations 响应无图片");
  const data = Buffer.from(b64, "base64");
  const filePath = path.join(attachmentsDir(cwd), stampName("png"));
  fs.writeFileSync(filePath, data);
  return { data, mime: "image/png", filePath, via: `${base}/images/generations` };
}

async function generateCodingChat(
  base: string,
  modelId: string,
  prompt: string,
  cwd: string,
): Promise<{ data: Buffer; mime: string; filePath: string; via: string }> {
  const json = await postJSON(`${base}/chat/completions`, {
    model: modelId,
    messages: [{ role: "user", content: prompt }],
    stream: false,
  });
  let content = json?.choices?.[0]?.message?.content ?? "";
  if (Array.isArray(content)) {
    content = content.map((c: any) => c?.text || "").join("\n");
  }
  const uri = extractDataUri(String(content));
  if (!uri) throw new Error("chat 响应里没有 data:image（模型可能未调用生图工具）");
  const data = Buffer.from(uri.b64, "base64");
  const ext = uri.mime.includes("jpeg") ? "jpg" : "png";
  const filePath = path.join(attachmentsDir(cwd), stampName(ext));
  fs.writeFileSync(filePath, data);
  return { data, mime: uri.mime, filePath, via: `${base}/chat/completions model=${modelId}` };
}

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "generate_image",
    label: "Generate Image",
    // Kept deliberately short: this rides in the cached prefix of every request, including
    // the many sessions that never generate an image. The long-form rules are returned by
    // the confirmed=false branch below, which lands in the conversation instead.
    description:
      "Generate or edit an image (Grok Imagine / Coding Relay; backend picked from the active " +
      "model). Call only after the user confirmed in chat. Returns the image and its saved path.",
    promptSnippet: "Generate or edit images after the user confirms",
    promptGuidelines: [
      "When asked in chat to generate/draw/edit an image, confirm subject and style first, then call generate_image with confirmed=true.",
    ],
    parameters: Type.Object({
      prompt: Type.String({ description: "Image description or edit instruction." }),
      confirmed: Type.Boolean({ description: "True only after the user confirmed in chat." }),
      reference_paths: Type.Optional(
        Type.Array(Type.String(), { description: "Absolute paths of reference images for i2i/edit." }),
      ),
    }),
    async execute(_id, params, _signal, _onUpdate, ctx) {
      if (!params.confirmed) {
        return {
          content: [
            {
              type: "text" as const,
              text: [
                "refused: confirmed=false.",
                "",
                "How this tool is meant to be used:",
                "1. Briefly confirm subject, style, and whether to use any reference images the user attached.",
                "2. Only after they confirm, call again with confirmed=true.",
                "3. For image-to-image / edit, pass the real absolute paths from the conversation in",
                "   reference_paths (attachments live under .pi/attachments/). Never invent a path such as",
                "   /home/workdir/attachments/, and do not use the read tool on one.",
                "4. The backend follows the active model automatically: Grok/xAI → Grok Imagine,",
                "   GPT/Codex → Coding Relay *-image. You do not select it.",
              ].join("\n"),
            },
          ],
          details: {},
          isError: true,
        };
      }

      const model = ctx.model as ActiveModel;
      const backend = pickBackend(model);
      const cwd = process.cwd();
      const refs: string[] = Array.isArray(params.reference_paths)
        ? params.reference_paths
        : [];

      try {
        const result =
          backend.kind === "coding-chat"
            ? await generateCodingChat(backend.base, backend.modelId, params.prompt, cwd)
            : await generateGrokRest(backend.base, backend.modelId, params.prompt, refs, cwd);

        const note =
          `Generated via ${backend.label}\n` +
          `model: ${backend.modelId}\n` +
          `saved: ${result.filePath}\n` +
          `endpoint: ${result.via}`;

        return {
          content: [
            { type: "text" as const, text: note },
            {
              type: "image" as const,
              data: result.data.toString("base64"),
              mimeType: result.mime,
            },
          ],
          details: { path: result.filePath, backend: backend.label },
        };
      } catch (e: any) {
        return {
          content: [
            {
              type: "text" as const,
              text:
                `generate_image failed: ${e?.message || e}\n` +
                `Tried ${backend.label} (${backend.modelId}). Is the relay running?`,
            },
          ],
          details: {},
          isError: true,
        };
      }
    },
  });

  // No before_agent_start block here on purpose. It used to append an image-generation
  // section to the system prompt that merely restated promptGuidelines and the tool
  // description — ~130 tokens of the cached prefix, on every request, for a tool most
  // sessions never call. The long form now comes back from the confirmed=false branch,
  // which lands in the conversation rather than the prefix.
  // (Its marker guard never worked either: the hook always receives the base prompt.)
}