// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Inject Google's server-side google_search (Grounding with Google Search) into
// google-generative-ai (generateContent) requests.
// Docs: https://ai.google.dev/gemini-api/docs/grounding
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

// REST JSON uses snake_case; v1beta supports the same shape. `google_search: {}` enables
// Grounding with Google Search on the server, returning citations in the response.
const GEMINI_GOOGLE_SEARCH_TOOL = { google_search: {} } as const;

type GenerateContentPayload = {
  model?: string;
  contents?: unknown;
  tools?: unknown[];
  [key: string]: unknown;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isGoogleModel(model: { provider?: string; api?: string } | undefined): boolean {
  if (!model) return false;
  const provider = (model.provider || "").toLowerCase();
  if (provider !== "google") return false;
  return model.api === "google-generative-ai";
}

function isGoogleGenerateContentRequest(
  model: { provider?: string; api?: string } | undefined,
  payload: unknown,
): payload is GenerateContentPayload {
  if (!isGoogleModel(model)) return false;
  if (!isRecord(payload)) return false;
  return Array.isArray(payload.contents);
}

// Gemini declares client tools as functionDeclarations inside a tools element. Strip a
// function named `web_search` so the server-side google_search does not double up on it.
function isWebSearchTool(tool: Record<string, unknown>): boolean {
  const decls = tool.functionDeclarations;
  if (!Array.isArray(decls)) return false;
  return decls.some((d) => isRecord(d) && d.name === "web_search");
}

function stripWebSearchDeclarations(tool: Record<string, unknown>): Record<string, unknown> | undefined {
  const decls = tool.functionDeclarations;
  if (!Array.isArray(decls)) return tool;
  const kept = decls.filter((d) => !(isRecord(d) && d.name === "web_search"));
  if (kept.length === decls.length) return tool;
  if (kept.length === 0) return undefined;
  return { ...tool, functionDeclarations: kept };
}

function mergeServerTools(existing: unknown): unknown[] {
  const current = Array.isArray(existing) ? [...existing] : [];

  const { filtered, hasGoogleSearch } = current.reduce<{
    filtered: unknown[];
    hasGoogleSearch: boolean;
  }>(
    (acc, tool) => {
      if (!isRecord(tool)) {
        acc.filtered.push(tool);
        return acc;
      }
      if (isRecord(tool.google_search)) {
        acc.hasGoogleSearch = true;
        acc.filtered.push(tool);
        return acc;
      }
      const stripped = stripWebSearchDeclarations(tool);
      if (stripped !== undefined) {
        acc.filtered.push(stripped);
      }
      return acc;
    },
    { filtered: [], hasGoogleSearch: false },
  );

  if (!hasGoogleSearch) {
    filtered.push({ ...GEMINI_GOOGLE_SEARCH_TOOL });
  }
  return filtered;
}

export default function (pi: ExtensionAPI) {
  pi.on("before_provider_request", (event, ctx) => {
    const model = ctx.model;
    if (!isGoogleGenerateContentRequest(model, event.payload)) {
      return;
    }

    const payload = event.payload as GenerateContentPayload;
    return {
      ...payload,
      tools: mergeServerTools(payload.tools),
    };
  });

  pi.on("before_agent_start", (event, ctx) => {
    const model = ctx.model;
    if (!isGoogleModel(model)) {
      return;
    }

    const tip = [
      "",
      "## Gemini server tools",
      "When the active model is official Google Gemini (`google` / google-generative-ai), Grounding with Google Search is enabled on every request:",
      "- `google_search` — live web search with citations (prefer over bash/curl for research)",
      "It executes on Google's servers automatically. Keep using local `read`/`bash`/`edit`/`write` for the workspace.",
    ].join("\n");

    if (event.systemPrompt.includes("## Gemini server tools")) {
      return;
    }
    return {
      systemPrompt: `${event.systemPrompt}${tip}`,
    };
  });

  pi.registerCommand("gemini-tools", {
    description: "Show whether Gemini server-side google_search is active",
    handler: async (_args, ctx) => {
      const model = ctx.model;
      const active = isGoogleModel(model);
      const lines = [
        `model: ${model ? `${model.provider}/${model.id}` : "(none)"}`,
        `api: ${model?.api ?? "(none)"}`,
        `Gemini server tools: ${active ? "ENABLED (google_search)" : "inactive (need google + google-generative-ai)"}`,
      ];
      ctx.ui.notify(lines.join("\n"), active ? "info" : "warning");
    },
  });
}
