// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Auto-mount Zhipu's web_search_prime MCP server for GLM main sessions, reusing the same
// GLM API key that powers account-usage. This is a self-contained streamable-http MCP
// client (only Zhipu's one server); it never touches ~/.pi/agent/mcp.json or patches the
// embedded pi runtime. When the main-session provider is not GLM, or no key can be
// resolved, this extension returns immediately and has zero effect.
//
// Protocol details mirror pi-mcp-extension@1.5.0 + @modelcontextprotocol/sdk@1.30.0
// (both shipped in this repo): initialize -> notifications/initialized -> tools/list ->
// tools/call, with the Mcp-Session-Id response header echoed back on later requests.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type, type TSchema } from "typebox";
import { readFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

// ─── Endpoint & protocol constants ────────────────────────────────────────────
const ENDPOINT = "https://open.bigmodel.cn/api/mcp/web_search_prime/mcp";
const LATEST_PROTOCOL_VERSION = "2025-11-25";
const SUPPORTED_PROTOCOL_VERSIONS = new Set([
  "2025-11-25",
  "2025-06-18",
  "2025-03-26",
  "2024-11-05",
  "2024-10-07",
]);
const CONNECT_TIMEOUT_MS = 9000;
const CALL_TIMEOUT_MS = 30000;

// GLM provider ids (must align with account-usage-core's apiKey() providerIds).
const GLM_PROVIDERS = new Set(["zai-coding-cn", "zai", "glm"]);

// Tool namespace per pi-mcp-extension buildToolName(): <prefix>_<server>_<tool>.
// "zhipu_search" is chosen to avoid colliding with a user's pi-mcp `mcp_*_tool` names.
const TOOL_PREFIX = "mcp";
const SERVER_NAME = "zhipu_search";

// ─── Types ────────────────────────────────────────────────────────────────────
type JsonRpcResult = { result?: unknown; error?: { code?: unknown; message?: string } };

type RemoteTool = {
  name: string;
  description?: string;
  inputSchema: Record<string, unknown>;
};

// ─── Small helpers ────────────────────────────────────────────────────────────
const clean = (value: unknown): string | undefined => {
  if (typeof value !== "string") return undefined;
  let result = value.trim();
  if (
    (result.startsWith('"') && result.endsWith('"')) ||
    (result.startsWith("'") && result.endsWith("'"))
  ) {
    result = result.slice(1, -1).trim();
  }
  return result || undefined;
};
const asObject = (value: unknown): Record<string, unknown> | undefined =>
  typeof value === "object" && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;

/**
 * Is this a GLM main-session? Reads PIPIUI_MAIN_MODEL (spawned as "<provider>/<id>") and
 * the provider segment that precedes the first "/". Unknown/missing model is not GLM.
 */
function isGlmMainModel(): boolean {
  const main = process.env.PIPIUI_MAIN_MODEL;
  if (!main) return false;
  const provider = main.split("/")[0]?.trim().toLowerCase();
  return Boolean(provider && GLM_PROVIDERS.has(provider));
}

/**
 * Resolve the GLM API key using the same precedence chain as account-usage-core's
 * apiKey()/GLM adapter: env → ~/.pi/agent/auth.json (zai-coding-cn, then zai, then glm)
 * → home-relative key files. Returns undefined when nothing usable is found (silent skip).
 */
async function resolveApiKey(): Promise<string | undefined> {
  // 1. Environment variables, iterated in account-usage-core order.
  for (const name of [
    "Z_AI_API_KEY",
    "ZAI_CODING_CN_API_KEY",
    "BIGMODEL_API_KEY",
    "ZHIPU_API_KEY",
    "ZHIPUAI_API_KEY",
    "ZAI_API_KEY",
    "GLM_API_KEY",
  ]) {
    const value = clean(process.env[name]);
    if (value) return value;
  }

  // 2. ~/.pi/agent/auth.json — { "<providerId>": { key|access|access_token } }.
  try {
    const text = await readFile(join(homedir(), ".pi", "agent", "auth.json"), "utf8");
    const root = asObject(JSON.parse(text));
    for (const id of ["zai-coding-cn", "zai", "glm"]) {
      const entry = asObject(root?.[id]);
      if (!entry) continue;
      for (const key of ["key", "access", "access_token"]) {
        const value = clean(entry[key]);
        if (value) return value;
      }
    }
  } catch {
    // Missing/unreadable auth.json → fall through to key files.
  }

  // 3. Home-relative key files (CodexBar-style), first usable line.
  for (const rel of [
    ".coding-relay/glm-api-key",
    ".config/bigmodel/api_key",
    ".config/zhipu/api_key",
  ]) {
    try {
      const text = await readFile(join(homedir(), rel), "utf8");
      const value = clean(text.split(/\r?\n/, 1)[0]);
      if (value) return value;
    } catch {
      // Missing file → try next candidate.
    }
  }

  return undefined;
}

function bearerHeaders(key: string, sessionId: string | undefined): Record<string, string> {
  const headers: Record<string, string> = {
    Authorization: `Bearer ${key}`,
    "Content-Type": "application/json",
    Accept: "application/json, text/event-stream",
  };
  if (sessionId) headers["Mcp-Session-Id"] = sessionId;
  return headers;
}

/** Parse a JSON response body that may be direct JSON or an SSE event stream. */
function parseResponseBody(body: string, contentType: string, id: number): JsonRpcResult | undefined {
  if (contentType.includes("text/event-stream")) {
    for (const line of body.split(/\r?\n/)) {
      if (!line.startsWith("data:")) continue;
      const payload = line.slice(5).trim();
      if (!payload) continue;
      try {
        const parsed: unknown = JSON.parse(payload);
        const response = Array.isArray(parsed)
          ? parsed.find((m) => asObject(m)?.id === id)
          : asObject(parsed)?.id === id
            ? parsed
            : undefined;
        if (response) return response as unknown as JsonRpcResult;
      } catch {
        // Skip malformed SSE data lines.
      }
    }
    return undefined;
  }
  try {
    const parsed: unknown = JSON.parse(body);
    return Array.isArray(parsed)
      ? (parsed.find((m) => asObject(m)?.id === id) as unknown as JsonRpcResult)
      : (parsed as unknown as JsonRpcResult);
  } catch {
    return undefined;
  }
}

// ─── State (module-scoped; one main session per process) ─────────────────────
let sessionKey: string | undefined;
let sessionId: string | undefined;
let remoteTools: RemoteTool[] | undefined;
let connectionPromise: Promise<RemoteTool[]> | undefined;

/**
 * Initialize the MCP session (initialize handshake + tools/list) once, memoized.
 * Network/protocol failures bubble up to callers, which swallow them so a failed
 * search never aborts the session.
 */
async function connect(): Promise<RemoteTool[]> {
  if (remoteTools) return remoteTools;
  if (connectionPromise) return connectionPromise;
  connectionPromise = (async () => {
    const key = sessionKey!;
    const init = await fetch(ENDPOINT, {
      method: "POST",
      headers: bearerHeaders(key, undefined),
      body: JSON.stringify({
        jsonrpc: "2.0",
        id: 1,
        method: "initialize",
        params: {
          protocolVersion: LATEST_PROTOCOL_VERSION,
          capabilities: {},
          clientInfo: { name: "pipiui-glm-search-mcp", version: "1.0.0" },
        },
      }),
      signal: AbortSignal.timeout(CONNECT_TIMEOUT_MS),
    });
    const newSessionId = init.headers.get("mcp-session-id") ?? undefined;
    if (!init.ok) {
      await init.body?.cancel().catch(() => {});
      throw new Error(`init ${init.status}`);
    }
    const initBody = await init.text();
    const initResult = parseResponseBody(
      initBody,
      init.headers.get("content-type") ?? "",
      1,
    );
    const initResultValue = asObject(initResult?.result);
    const negotiated = clean(initResultValue?.protocolVersion);
    if (!negotiated || !SUPPORTED_PROTOCOL_VERSIONS.has(negotiated)) {
      throw new Error("unsupported protocol");
    }
    sessionId = newSessionId;

    // Best-effort notifications/initialized (notification; no response expected).
    try {
      const r = await fetch(ENDPOINT, {
        method: "POST",
        headers: bearerHeaders(key, sessionId),
        body: JSON.stringify({ jsonrpc: "2.0", method: "notifications/initialized" }),
        signal: AbortSignal.timeout(CONNECT_TIMEOUT_MS),
      });
      await r.body?.cancel().catch(() => {});
    } catch {
      // Ignore — servers may not require it.
    }

    const listReq = await fetch(ENDPOINT, {
      method: "POST",
      headers: bearerHeaders(key, sessionId),
      body: JSON.stringify({ jsonrpc: "2.0", id: 2, method: "tools/list", params: {} }),
      signal: AbortSignal.timeout(CONNECT_TIMEOUT_MS),
    });
    if (!listReq.ok) {
      await listReq.body?.cancel().catch(() => {});
      throw new Error(`tools/list ${listReq.status}`);
    }
    const listBody = await listReq.text();
    const listResult = parseResponseBody(
      listBody,
      listReq.headers.get("content-type") ?? "",
      2,
    );
    const tools = asObject(listResult?.result)?.tools;
    if (!Array.isArray(tools)) throw new Error("tools/list empty");
    const discovered = tools
      .map(asObject)
      .filter((t): t is Record<string, unknown> => Boolean(t))
      .map((t) => ({
        name: clean(t.name) ?? String(t.name),
        description: clean(t.description) ?? undefined,
        inputSchema:
          (asObject(t.inputSchema) as Record<string, unknown>) ?? { type: "object" },
      }))
      .filter((t) => t.name);
    remoteTools = discovered;
    return remoteTools;
  })().catch((err) => {
    connectionPromise = undefined;
    throw err;
  });
  return connectionPromise;
}

/** Invoke a single remote tool and return the resulting text (never includes the key). */
async function callTool(remoteName: string, args: unknown): Promise<string> {
  const tools = await connect();
  const remote = tools.find((t) => t.name === remoteName);
  if (!remote) return `工具 "${remoteName}" 不可用`;
  const response = await fetch(ENDPOINT, {
    method: "POST",
    headers: bearerHeaders(sessionKey!, sessionId),
    body: JSON.stringify({
      jsonrpc: "2.0",
      id: 3,
      method: "tools/call",
      params: { name: remote.name, arguments: args ?? {} },
    }),
    signal: AbortSignal.timeout(CALL_TIMEOUT_MS),
  });
  if (!response.ok) {
    await response.body?.cancel().catch(() => {});
    return `search failed (HTTP ${response.status})`;
  }
  const body = await response.text();
  const result = parseResponseBody(body, response.headers.get("content-type") ?? "", 3);
  const resultValue = asObject(result?.result);
  const content = Array.isArray(resultValue?.content) ? resultValue.content : [];
  const text = contentToText(content);
  if (resultValue?.isError === true) return text || "search failed";
  return text;
}

// ─── TypeBox schema conversion (mirrors pi-mcp-extension convertJsonSchemaToTypebox) ──
function toTypebox(schema: unknown): TSchema {
  if (!schema || typeof schema !== "object" || Array.isArray(schema)) return Type.Any();
  const s = schema as Record<string, unknown>;
  const description = typeof s.description === "string" ? s.description : undefined;
  const opts = description ? { description } : {};

  const rawType = s.type;
  const type = Array.isArray(rawType)
    ? (rawType.find((t) => t !== "null") as string | undefined)
    : typeof rawType === "string"
      ? rawType
      : undefined;
  const nullable = Array.isArray(rawType) && rawType.includes("null");

  let base: TSchema;
  switch (type) {
    case "string": {
      const enumVals = s.enum;
      if (Array.isArray(enumVals) && enumVals.every((v) => typeof v === "string")) {
        base = Type.Union(enumVals.map((v) => Type.Literal(v))) as unknown as TSchema;
      } else {
        base = Type.String(opts);
      }
      break;
    }
    case "number":
    case "integer":
      base = Type.Number(opts);
      break;
    case "boolean":
      base = Type.Boolean(opts);
      break;
    case "null":
      base = Type.Null(opts);
      break;
    case "array":
      base = Type.Array(
        s.items ? toTypebox(s.items) : Type.Unknown(),
        opts,
      ) as unknown as TSchema;
      break;
    case "object": {
      const properties = s.properties as Record<string, unknown> | undefined;
      const required = new Set<string>(
        Array.isArray(s.required) ? (s.required as string[]) : [],
      );
      if (!properties) {
        base = Type.Record(Type.String(), Type.Unknown(), opts);
        break;
      }
      const props: Record<string, TSchema> = {};
      for (const [key, value] of Object.entries(properties)) {
        props[key] = required.has(key)
          ? toTypebox(value)
          : Type.Optional(toTypebox(value)) as unknown as TSchema;
      }
      const objOpts: Record<string, unknown> = { ...opts };
      if (s.additionalProperties === false) objOpts.additionalProperties = false;
      base = Type.Object(props, objOpts) as unknown as TSchema;
      break;
    }
    default:
      base = Type.Any(opts);
  }
  return nullable ? (Type.Union([base, Type.Null()]) as unknown as TSchema) : base;
}

/** Convert MCP content items into plain text for the model. */
function contentToText(items: unknown[]): string {
  return items
    .map((raw) => {
      const item = asObject(raw);
      if (!item) return String(raw);
      switch (item.type) {
        case "text":
          return String(item.text ?? "");
        case "image":
          return `[Image: ${item.mimeType ?? "unknown"}, base64 embedded]`;
        case "audio":
          return `[Audio: ${item.mimeType ?? "unknown"}, base64 embedded]`;
        case "resource": {
          const r = asObject(item.resource);
          if (r?.text) return String(r.text);
          if (r?.blob) return `[Resource blob: ${r.uri ?? "unknown"}]`;
          return `[Resource: ${r?.uri ?? "unknown"}]`;
        }
        default:
          return JSON.stringify(item);
      }
    })
    .join("\n");
}

/** Build a pi-compatible tool name (pi-mcp-extension's buildToolName convention). */
function buildToolName(remoteName: string): string {
  const raw = `${TOOL_PREFIX}_${SERVER_NAME}_${remoteName}`;
  const safe = raw.replace(/[^a-zA-Z0-9_]/g, "_");
  const MAX = 64;
  if (safe.length <= MAX) return safe;
  const hash = Math.abs(
    safe.split("").reduce((acc, c) => ((acc << 5) - acc + c.charCodeAt(0)) | 0, 0),
  )
    .toString(36)
    .slice(0, 8);
  return safe.slice(0, MAX - 9) + "_" + hash;
}

// ─── Pi extension ─────────────────────────────────────────────────────────────
export default async function (pi: ExtensionAPI): Promise<void> {
  if (!isGlmMainModel()) return; // Non-GLM provider → zero behavior change.
  const key = await resolveApiKey();
  if (!key) return; // No usable GLM key → silent skip.
  sessionKey = key;

  // Connect lazily per session (async-safe per pi docs) and register discovered tools.
  // Any failure is swallowed: a failed search must never block or abort the session.
  pi.on("session_start", async () => {
    try {
      const tools = await connect();
      for (const tool of tools) {
        pi.registerTool({
          name: buildToolName(tool.name),
          label: tool.name,
          description: tool.description ?? `Zhipu MCP tool: ${tool.name}`,
          promptSnippet: (tool.description ?? `web_search_prime ${tool.name}`).slice(0, 120),
          parameters: toTypebox(tool.inputSchema),
          async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
            try {
              const text = await callTool(tool.name, params);
              return { content: [{ type: "text", text }], details: {} };
            } catch {
              // Connection/protocol failure at call time → neutral text, no key.
              return {
                content: [{ type: "text", text: "search unavailable" }],
                details: {},
              };
            }
          },
        });
      }
      // Activate so the tools surface in the system prompt (pi-mcp activation pattern).
      const names = tools.map((t) => buildToolName(t.name));
      pi.setActiveTools([...new Set([...pi.getActiveTools(), ...names])]);
    } catch {
      // Silent failure — session continues without the search tools.
    }
  });
}
