// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Inject Anthropic server-side web_search into anthropic-messages requests.
// Docs: https://platform.claude.com/docs/en/agents-and-tools/tool-use/web-search-tool
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

// Basic version: works without code_execution / dynamic filtering.
// Use allowed_callers:direct on newer types if upgrading later.
const CLAUDE_WEB_SEARCH_TOOL = {
  type: "web_search_20250305",
  name: "web_search",
  max_uses: 8,
} as const;

type MessagesPayload = {
  model?: string;
  messages?: unknown;
  tools?: unknown[];
  [key: string]: unknown;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isAnthropicMessagesModel(model: { provider?: string; api?: string } | undefined): boolean {
  if (!model) return false;
  const provider = (model.provider || "").toLowerCase();
  if (provider !== "anthropic" && !provider.includes("anthropic") && !provider.includes("claude")) {
    return false;
  }
  return model.api === "anthropic-messages";
}

function isAnthropicMessagesRequest(
  model: { provider?: string; api?: string } | undefined,
  payload: unknown,
): payload is MessagesPayload {
  if (!isAnthropicMessagesModel(model)) return false;
  if (!isRecord(payload)) return false;
  return Array.isArray(payload.messages);
}

function isAnthropicServerWebSearch(tool: Record<string, unknown>): boolean {
  const type = typeof tool.type === "string" ? tool.type : "";
  return type.startsWith("web_search_");
}

function mergeServerTools(existing: unknown): unknown[] {
  const current = Array.isArray(existing) ? [...existing] : [];
  // Drop client/custom tools named web_search so they don't collide with the
  // Anthropic server tool (same name, different shape).
  const filtered = current.filter((tool) => {
    if (!isRecord(tool)) return true;
    if (isAnthropicServerWebSearch(tool)) return true;
    const name = typeof tool.name === "string" ? tool.name : "";
    return name !== "web_search";
  });

  const hasServer = filtered.some(
    (tool) => isRecord(tool) && isAnthropicServerWebSearch(tool),
  );
  if (!hasServer) {
    filtered.push({ ...CLAUDE_WEB_SEARCH_TOOL });
  }
  return filtered;
}

export default function (pi: ExtensionAPI) {
  pi.on("before_provider_request", (event, ctx) => {
    const model = ctx.model;
    if (!isAnthropicMessagesRequest(model, event.payload)) {
      return;
    }

    const payload = event.payload as MessagesPayload;
    return {
      ...payload,
      tools: mergeServerTools(payload.tools),
    };
  });

  pi.on("before_agent_start", (event, ctx) => {
    const model = ctx.model;
    if (!isAnthropicMessagesModel(model)) {
      return;
    }

    const tip = [
      "",
      "## Claude server tools",
      "When the active model is official Anthropic Claude (`anthropic` / anthropic-messages), this server-side tool is enabled on every request:",
      "- `web_search` — live web search with citations (prefer over bash/curl for research)",
      "It executes on Anthropic servers automatically. Keep using local `read`/`bash`/`edit`/`write` for the workspace.",
    ].join("\n");

    if (event.systemPrompt.includes("## Claude server tools")) {
      return;
    }
    return {
      systemPrompt: `${event.systemPrompt}${tip}`,
    };
  });

  pi.registerCommand("claude-tools", {
    description: "Show whether Claude hosted web_search is active",
    handler: async (_args, ctx) => {
      const model = ctx.model;
      const active = isAnthropicMessagesModel(model);
      const lines = [
        `model: ${model ? `${model.provider}/${model.id}` : "(none)"}`,
        `api: ${model?.api ?? "(none)"}`,
        `Claude server tools: ${active ? "ENABLED (web_search)" : "inactive (need anthropic + anthropic-messages)"}`,
      ];
      ctx.ui.notify(lines.join("\n"), active ? "info" : "warning");
    },
  });
}