// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Exposes the Pipi UI in-app WebView as browser_* tools via a local HTTP bridge.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { randomUUID } from "node:crypto";
import { isTrivialBrowserEval } from "./browser-eval-guard.ts";

const PORT = process.env.PIPIUI_BRIDGE_PORT;
const KEY = process.env.PIPIUI_SESSION_KEY;
const CAPABILITY = process.env.PIPIUI_SESSION_CAPABILITY;

const REQUEST_TIMEOUT_MS = 35_000;
const CANCEL_TIMEOUT_MS = 1_500;

async function cancelBridgeRequest(requestID: string): Promise<void> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), CANCEL_TIMEOUT_MS);
  try {
    await fetch(`http://127.0.0.1:${PORT}/rpc`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      signal: controller.signal,
      body: JSON.stringify({ schemaVersion: 1, sessionCapability: CAPABILITY, action: "browser_action", event: { action: "browser_cancel", requestID } }),
    });
  } catch {
    // Disconnect cancellation is also registered by the Swift bridge.
  } finally {
    clearTimeout(timer);
  }
}

async function bridge(
  action: string,
  params: Record<string, unknown> = {},
  externalSignal?: AbortSignal,
): Promise<any> {
  const requestID = randomUUID();
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
  const forwardAbort = () => controller.abort();
  if (externalSignal?.aborted) controller.abort();
  else externalSignal?.addEventListener("abort", forwardAbort, { once: true });
  try {
    const res = await fetch(`http://127.0.0.1:${PORT}/rpc`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      signal: controller.signal,
      body: JSON.stringify({ schemaVersion: 1, sessionCapability: CAPABILITY, action: "browser_action", event: { action, requestID, ...params } }),
    });
    return await res.json();
  } catch (error) {
    if (controller.signal.aborted) {
      await cancelBridgeRequest(requestID);
      throw new Error("browser request timed out or was cancelled");
    }
    throw error;
  } finally {
    clearTimeout(timer);
    externalSignal?.removeEventListener("abort", forwardAbort);
  }
}

function text(t: string, details: Record<string, unknown> = {}) {
  return { content: [{ type: "text" as const, text: t }], details };
}

function bridgeFailure(r: any) {
  const summary = {
    error: r?.error || "browser bridge action failed",
    code: r?.code,
    requiresObservation: r?.requiresObservation,
    requiresUserInput: r?.requiresUserInput,
    observation: r?.observation,
  };
  return {
    content: [{ type: "text" as const, text: JSON.stringify(summary, null, 2) }],
    details: r || {},
    isError: true,
  };
}

function formatObservation(r: any): string {
  const lines = [
    `URL: ${r.url || ""}`,
    `Title: ${r.title || ""}`,
    `Snapshot: ${r.snapshotID || ""}`,
    `Loading: ${r.loading === true}`,
    `Viewport: ${r.viewport?.width || 0}x${r.viewport?.height || 0}`,
    `Scroll: ${r.scroll?.pixelsAbove || 0}px above, ${r.scroll?.pixelsBelow || 0}px below (${r.scroll?.positionPercent || 0}%)`,
    "Elements:",
  ];
  for (const element of r.elements || []) lines.push(JSON.stringify(element));
  if (r.truncated) lines.push("[observation truncated: refine scope or scroll]");
  if (Array.isArray(r.limitations) && r.limitations.length) {
    lines.push("Limitations:", ...r.limitations.map((item: string) => `- ${item}`));
  }
  if (r.action) lines.push(`Action: ${JSON.stringify(r.action)}`);
  if (r.note) lines.push(`Note: ${r.note}`);
  return lines.join("\n");
}

// Full parameter docs live here, not in the tool schema: help text is delivered as a
// tool result, which appends to the conversation instead of rewriting the cached
// prefix. See docs/progressive-disclosure.md.
const HELP = [
  "browser actions:",
  "",
  "navigate {url}          Open a URL in the panel and wait for load. Scheme optional;",
  "                        localhost defaults to http. Settles on didFinish + a short network-idle",
  "                        window (resource timing heuristic). Returns a fresh observation.",
  "observe {scope?}        Snapshot interactive DOM. scope='viewport' (default) or 'page'.",
  "wait {mode?, selector?, timeout?, idle_ms?, snapshot_id?, element_index|element_token?}",
  "                        mode='selector' (default when selector/target given): wait until a CSS",
  "                        selector is visible, or a snapshot element target is valid again.",
  "                        mode='idle' (default otherwise): wait until document.readyState is",
  "                        complete and Performance resource timing stays quiet for idle_ms",
  "                        (default 400ms). timeout is seconds (default 10, max 30). On success",
  "                        returns a fresh observation; on timeout code=browser_wait_timeout.",
  "click {snapshot_id, element_index|element_token}",
  "input {snapshot_id, element_index|element_token, text}",
  "select {snapshot_id, element_index|element_token, option}",
  "scroll {direction?, amount?, snapshot_id?, element_index|element_token?}",
  "                        amount is 0.1..10 viewport lengths (default 0.8). Mutating actions",
  "                        invalidate the prior snapshot and return a fresh observation.",
  "                        Password, OTP, and payment fields require user handoff in the panel.",
  "content {mode?}         Raw fallback. mode='text' (default) or 'html'; may be large.",
  "                        WARNING: bypasses structured redaction — may expose credentials,",
  "                        tokens, and payment details. Avoid on auth/checkout pages.",
  "eval {js}               Page-DOM only. Never string literals / keep-alive; use observe then click/input.",
  "                        WARNING: can read DOM values and secrets directly. Avoid on",
  "                        auth/checkout pages; prefer observe/click/input.",
  "console {clear?}        Console output (log/info/warn/error), JS exceptions and failed",
  "                        navigations since the last clear. clear=true empties the buffer.",
  "screenshot              Screenshot of the current page, returned as an image you can look at.",
  "                        WARNING: pixels are not redacted — passwords/OTP/card numbers visible",
  "                        on screen will appear in the image. Avoid capturing auth/checkout UI",
  "                        unless the user explicitly needs a visual check.",
  "",
  "Structured DOM covers the main document, open shadow roots, and one same-origin iframe level.",
  "Use screenshot or Computer Use for cross-origin iframes, closed shadow roots, Canvas/WebGL.",
  "JS dialogs (alert/confirm/prompt) are suppressed and not controllable — if a page needs a",
  "dialog response, stop and use screenshot or ask the user (handoff).",
  "file inputs cannot receive local paths from this tool — use user handoff or Computer Use",
  "for uploads.",
  "Sensitive-field heuristics cover password/OTP/payment-ish controls but do NOT guarantee",
  "capture of SSN, ID numbers, cardholder name, or CAPTCHA fields; when unsure, hand off.",
  "This tool always controls the built-in WebView. For Chrome, use open_application then computer;",
  "the user selects the tab and you must re-observe title/URL/screenshot/AX before each write batch.",
  "back | forward | reload Navigate the active built-in browser tab.",
  "help                    This text.",
].join("\n");

export default function (pi: ExtensionAPI) {
  if (!PORT || !KEY) return; // Not running inside Pipi UI; stay dormant.

  // One stable tool instead of five browser_* tools. The tool set never changes, so the
  // prompt prefix stays cached, and the per-request schema cost drops ~400 tokens.
  pi.registerTool({
    name: "browser",
    label: "Browser",
    description:
      "Drive the built-in WebView with structured observations and typed DOM actions. " +
      "actions: navigate, observe, wait, click, input, type, select, scroll, content, eval, console, screenshot, back, forward, reload, help. " +
      "eval is page-DOM only (no literals/keep-alive). Fallbacks content/eval/screenshot bypass structured redaction and may expose credentials — avoid on auth/checkout pages. " +
      'Call with action:"help" for full parameter docs.',
    parameters: Type.Object({
      action: Type.String({
        description: "navigate | observe | wait | click | input | select | scroll | content | eval | console | screenshot | back | forward | reload | help",
      }),
      url: Type.Optional(Type.String()),
      js: Type.Optional(Type.String()),
      mode: Type.Optional(Type.Union([
        Type.Literal("text"), Type.Literal("html"), Type.Literal("selector"), Type.Literal("idle"),
      ])),
      clear: Type.Optional(Type.Boolean()),
      scope: Type.Optional(Type.Union([Type.Literal("viewport"), Type.Literal("page")])),
      snapshot_id: Type.Optional(Type.String()),
      element_index: Type.Optional(Type.Number()),
      element_token: Type.Optional(Type.String()),
      text: Type.Optional(Type.String()),
      option: Type.Optional(Type.String()),
      direction: Type.Optional(Type.Union([
        Type.Literal("up"), Type.Literal("down"), Type.Literal("left"), Type.Literal("right"),
      ])),
      amount: Type.Optional(Type.Number({ minimum: 0.1, maximum: 10 })),
      selector: Type.Optional(Type.String()),
      timeout: Type.Optional(Type.Number({ minimum: 0.05, maximum: 30 })),
      idle_ms: Type.Optional(Type.Number({ minimum: 50, maximum: 5000 })),
    }),
    async execute(_id, params, signal) {
      switch (params.action) {
        case "navigate": {
          if (!params.url) return text('browser navigate requires "url".\n\n' + HELP);
          const r = await bridge("navigate", { url: params.url, scope: params.scope ?? "viewport" }, signal);
          return r.ok ? text(formatObservation(r), r) : bridgeFailure(r);
        }
        case "observe": {
          const r = await bridge("observe", { scope: params.scope ?? "viewport" }, signal);
          return r.ok ? text(formatObservation(r), r) : bridgeFailure(r);
        }
        case "wait": {
          const mode = params.mode === "idle" || params.mode === "selector"
            ? params.mode
            : (typeof params.selector === "string" && params.selector.trim()
              || typeof params.element_index === "number"
              || (typeof params.element_token === "string" && params.element_token.length > 0)
                ? "selector"
                : "idle");
          if (mode === "selector") {
            const hasSelector = typeof params.selector === "string" && params.selector.trim().length > 0;
            const hasIndex = typeof params.element_index === "number";
            const hasToken = typeof params.element_token === "string" && params.element_token.length > 0;
            if (!hasSelector && hasIndex === hasToken) {
              return text(`browser wait selector mode requires selector or exactly one of element_index or element_token.\n\n${HELP}`);
            }
            if (hasSelector && (hasIndex || hasToken || params.snapshot_id)) {
              return text(`browser wait selector mode accepts selector or a snapshot element target, not both.\n\n${HELP}`);
            }
            if (!hasSelector && !params.snapshot_id) {
              return text(`browser wait with an element target requires snapshot_id.\n\n${HELP}`);
            }
          } else if (params.mode && params.mode !== "idle" && params.mode !== "selector"
            && params.mode !== "text" && params.mode !== "html") {
            return text(`browser wait mode must be "selector" or "idle".\n\n${HELP}`);
          }
          const r = await bridge("wait", {
            mode,
            scope: params.scope ?? "viewport",
            ...(typeof params.selector === "string" ? { selector: params.selector } : {}),
            ...(typeof params.timeout === "number" ? { timeout: params.timeout } : {}),
            ...(typeof params.idle_ms === "number" ? { idle_ms: params.idle_ms } : {}),
            ...(typeof params.snapshot_id === "string" ? { snapshot_id: params.snapshot_id } : {}),
            ...(typeof params.element_index === "number" ? { element_index: params.element_index } : {}),
            ...(typeof params.element_token === "string" ? { element_token: params.element_token } : {}),
          }, signal);
          return r.ok ? text(formatObservation(r), r) : bridgeFailure(r);
        }
        case "type": {
          if (!params.selector || typeof params.text !== "string") return text("browser type requires selector and text.\n\n" + HELP);
          const r = await bridge("type", { selector: params.selector, text: params.text, scope: params.scope ?? "viewport" }, signal);
          return r.ok ? text(formatObservation(r), r) : bridgeFailure(r);
        }
        case "click":
        case "input":
        case "select": {
          const hasIndex = typeof params.element_index === "number";
          const hasToken = typeof params.element_token === "string" && params.element_token.length > 0;
          if (!params.snapshot_id || hasIndex === hasToken) {
            return text(`browser ${params.action} requires snapshot_id and exactly one of element_index or element_token.\n\n${HELP}`);
          }
          if (params.action === "input" && typeof params.text !== "string") {
            return text(`browser input requires text.\n\n${HELP}`);
          }
          if (params.action === "select" && typeof params.option !== "string") {
            return text(`browser select requires option.\n\n${HELP}`);
          }
          const r = await bridge(params.action, {
            scope: params.scope ?? "viewport",
            snapshot_id: params.snapshot_id,
            ...(hasIndex ? { element_index: params.element_index } : { element_token: params.element_token }),
            ...(params.action === "input" ? { text: params.text } : {}),
            ...(params.action === "select" ? { option: params.option } : {}),
          }, signal);
          return r.ok ? text(formatObservation(r), r) : bridgeFailure(r);
        }
        case "scroll": {
          const hasIndex = typeof params.element_index === "number";
          const hasToken = typeof params.element_token === "string" && params.element_token.length > 0;
          const hasTarget = Boolean(params.snapshot_id || hasIndex || hasToken);
          if (hasTarget && (!params.snapshot_id || hasIndex === hasToken)) {
            return text(`targeted browser scroll requires snapshot_id and exactly one of element_index or element_token.\n\n${HELP}`);
          }
          const r = await bridge("scroll", {
            scope: params.scope ?? "viewport",
            direction: params.direction ?? "down",
            amount: params.amount ?? 0.8,
            ...(hasTarget ? {
              snapshot_id: params.snapshot_id,
              ...(hasIndex ? { element_index: params.element_index } : { element_token: params.element_token }),
            } : {}),
          }, signal);
          return r.ok ? text(formatObservation(r), r) : bridgeFailure(r);
        }
        case "content": {
          const r = await bridge("content", { mode: params.mode ?? "text" }, signal);
          if (!r.ok) return bridgeFailure(r);
          const suffix = r.truncated ? "\n\n[content truncated at 100000 chars]" : "";
          return text((r.content || "(empty page)") + suffix);
        }
        case "eval": {
          if (!params.js) return text('browser eval requires "js".\n\n' + HELP);
          if (isTrivialBrowserEval(params.js)) {
            return text(
              "eval rejected because js does not read or change the page. " +
                "do not use eval to return string literals / count / keep-alive / print progress. " +
                "to click/type: observe then snapshot_id + element_index or element_token.\n\n" +
                HELP,
            );
          }
          const r = await bridge("eval", { js: params.js }, signal);
          if (!r.ok) return bridgeFailure(r);
          return text(String(r.result ?? "undefined"));
        }
        case "console": {
          const r = await bridge("console", { clear: params.clear ?? false }, signal);
          if (!r.ok) return bridgeFailure(r);
          const logs: string[] = r.logs || [];
          return text(logs.length ? logs.join("\n") : "(console is empty)");
        }
        case "screenshot": {
          const r = await bridge("screenshot", {}, signal);
          if (!r.ok) return bridgeFailure(r);
          return {
            content: [{ type: "image" as const, data: r.base64, mimeType: r.mimeType || "image/png" }],
            details: {},
          };
        }
        case "back":
        case "forward":
        case "reload": {
          const r = await bridge(params.action, { scope: params.scope ?? "viewport" }, signal);
          return r.ok ? text(formatObservation(r), r) : bridgeFailure(r);
        }
        case "help":
          return text(HELP);
        default:
          return text(`Unknown browser action "${params.action}".\n\n${HELP}`);
      }
    },
  });
}