// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// xAI retired Live Search. A top-level `search_parameters` field on
// `/v1/chat/completions` now returns 410 Gone:
//   "Live search is deprecated. Please switch to the Agent Tools API"
// Docs: https://docs.x.ai/docs/guides/tools/overview
//
// Grok Build / xAI Agent Tools run on the Responses API as hosted
// `{ type: "web_search" }`. Every channel whose provider field is `xai`
// (official api.x.ai, relays, custom endpoints, any Grok model id) is
// remapped onto openai-responses and the hosted tool is injected. Client
// function tools named `web_search` are dropped so they cannot collide.
// Incompatible relays must fail visibly — no silent fallback to Pipi
// pi-web-access web_search.
//
// It also captures api.x.ai's `x-ratelimit-*` response headers (the only
// programmatic quota signal left for SuperGrok/X Premium OAuth accounts) into
// `<agentDir>/grok-rate-limits.json` for the host's Grok 账号额度 pill.
import { renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";

const XAI_WEB_SEARCH_TOOL = {
  type: "web_search",
} as const;

const XAI_RESPONSES_API = "openai-responses";

type ProviderPayload = {
  model?: string;
  input?: unknown;
  messages?: unknown;
  tools?: unknown[];
  [key: string]: unknown;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isXaiProvider(model: { provider?: string } | undefined): boolean {
  return (model?.provider || "").toLowerCase() === "xai";
}

function isXaiResponsesRequest(
  model: { provider?: string; api?: string } | undefined,
  payload: unknown,
): payload is ProviderPayload {
  if (!isXaiProvider(model)) return false;
  if (!isRecord(payload)) return false;
  return Array.isArray(payload.input);
}

function isXaiCompletionsRequest(
  model: { provider?: string; api?: string } | undefined,
  payload: unknown,
): payload is ProviderPayload {
  if (!isXaiProvider(model)) return false;
  if (!isRecord(payload)) return false;
  return Array.isArray(payload.messages) && !Array.isArray(payload.input);
}

function isClientWebSearchTool(tool: Record<string, unknown>): boolean {
  const type = typeof tool.type === "string" ? tool.type : "";
  const name = typeof tool.name === "string" ? tool.name : "";
  if (name === "web_search") return true;
  if (type === "function") {
    const fn = isRecord(tool.function) ? tool.function : undefined;
    const fnName = typeof fn?.name === "string" ? fn.name : "";
    return fnName === "web_search";
  }
  return false;
}

function isHostedWebSearchTool(tool: Record<string, unknown>): boolean {
  return tool.type === "web_search" && (typeof tool.name !== "string" || tool.name === "web_search")
    && tool.function === undefined;
}

function dropClientWebSearch(existing: unknown): unknown[] {
  const current = Array.isArray(existing) ? [...existing] : [];
  return current.filter((tool) => {
    if (!isRecord(tool)) return true;
    if (isHostedWebSearchTool(tool)) return true;
    return !isClientWebSearchTool(tool);
  });
}

function mergeHostedWebSearch(existing: unknown): unknown[] {
  const filtered = dropClientWebSearch(existing);
  const hasHosted = filtered.some((tool) => isRecord(tool) && isHostedWebSearchTool(tool));
  if (!hasHosted) filtered.push({ ...XAI_WEB_SEARCH_TOOL });
  return filtered;
}

function withoutSearchParameters(payload: ProviderPayload): ProviderPayload {
  if (!Object.prototype.hasOwnProperty.call(payload, "search_parameters")) return payload;
  const next = { ...payload };
  delete next.search_parameters;
  return next;
}

function remapXaiModelsToResponses(models: unknown[]): unknown[] {
  return models.map((model) => {
    if (!isRecord(model)) return model;
    return { ...model, api: XAI_RESPONSES_API };
  });
}

async function applyXaiResponsesApi(pi: ExtensionAPI, ctx: ExtensionContext): Promise<void> {
  const registry = ctx.modelRegistry;
  if (!registry?.getProvider) return;
  const provider = registry.getProvider("xai");
  const models = provider?.getModels ? provider.getModels() : [];
  if (!Array.isArray(models) || models.length === 0) return;
  pi.registerProvider("xai", {
    api: XAI_RESPONSES_API,
    models: remapXaiModelsToResponses(models),
  });
}

const RATE_LIMIT_WRITE_INTERVAL_MS = 30_000;
let lastRateLimitWriteMs = 0;

function headerValue(headers: Record<string, unknown>, name: string): string | undefined {
  const lower = name.toLowerCase();
  for (const [key, value] of Object.entries(headers)) {
    if (key.toLowerCase() === lower && typeof value === "string") return value;
  }
  return undefined;
}

/**
 * Persist the newest rate-limit numbers so the host quota pill can read them without a probe
 * request. Throttled: streaming turns fire this repeatedly with identical headers.
 */
function captureRateLimitHeaders(headers: Record<string, unknown> | undefined, now: number): void {
  const agentDir = process.env.PI_CODING_AGENT_DIR;
  const limitRequests = headerValue(headers ?? {}, "x-ratelimit-limit-requests");
  if (!agentDir || limitRequests === undefined) return;
  if (now - lastRateLimitWriteMs < RATE_LIMIT_WRITE_INTERVAL_MS) return;
  lastRateLimitWriteMs = now;
  const payload = {
    capturedAt: now,
    limitRequests: Number(limitRequests),
    remainingRequests: Number(headerValue(headers ?? {}, "x-ratelimit-remaining-requests")),
    limitTokens: Number(headerValue(headers ?? {}, "x-ratelimit-limit-tokens")),
    remainingTokens: Number(headerValue(headers ?? {}, "x-ratelimit-remaining-tokens")),
  };
  try {
    const target = join(agentDir, "grok-rate-limits.json");
    const temporary = `${target}.${process.pid}.tmp`;
    writeFileSync(temporary, `${JSON.stringify(payload)}\n`);
    renameSync(temporary, target);
  } catch {
    // Quota capture is best-effort; a failed write must never break the chat.
  }
}

export default function (pi: ExtensionAPI) {
  pi.on("session_start", (_event, ctx) => {
    return applyXaiResponsesApi(pi, ctx).catch((error) => {
      console.error(
        `[pipiui-xai-server-tools] failed to remap xAI models onto Responses: ${error instanceof Error ? error.message : String(error)}`,
      );
    });
  });

  pi.on("before_provider_request", (event, ctx) => {
    const model = ctx.model;
    if (!isXaiProvider(model) || !isRecord(event.payload)) {
      return;
    }

    if (isXaiResponsesRequest(model, event.payload)) {
      const payload = withoutSearchParameters(event.payload);
      return {
        ...payload,
        tools: mergeHostedWebSearch(payload.tools),
      };
    }

    if (isXaiCompletionsRequest(model, event.payload)) {
      // Legacy completions: never send 410 Live Search, never keep colliding
      // client web_search. Do not inject hosted tools here — they belong on
      // Responses. Relays still on completions should fail after remap, not
      // silently use Pipi web_search.
      const payload = withoutSearchParameters(event.payload);
      return {
        ...payload,
        tools: dropClientWebSearch(payload.tools),
      };
    }

    if (Object.prototype.hasOwnProperty.call(event.payload, "search_parameters")) {
      return withoutSearchParameters(event.payload as ProviderPayload);
    }
  });

  pi.on("after_provider_response", (event, ctx) => {
    const model = ctx.model;
    // grok-relay and other relays report their own quota; only official api.x.ai headers count.
    if (model && model.provider.toLowerCase() !== "xai") return;
    captureRateLimitHeaders(event.headers, Date.now());
  });

  pi.on("before_agent_start", (event, ctx) => {
    const model = ctx.model;
    if (!isXaiProvider(model)) {
      return;
    }

    const tip = [
      "",
      "## xAI server tools",
      "When the active model is any `xai` provider channel, xAI Responses hosted Agent Tools are enabled on every request:",
      "- `web_search` — live web search executed on xAI servers (prefer over bash/curl and over client/pi-web-access web_search)",
      "Do not send `search_parameters` (retired Live Search, returns 410). Keep using local `read`/`bash`/`edit`/`write` for the workspace.",
    ].join("\n");

    if (event.systemPrompt.includes("## xAI server tools")) {
      return;
    }
    return {
      systemPrompt: `${event.systemPrompt}${tip}`,
    };
  });

  pi.registerCommand("xai-tools", {
    description: "Show whether xAI hosted web_search is active",
    handler: async (_args, ctx) => {
      const model = ctx.model;
      const active = isXaiProvider(model);
      const lines = [
        `model: ${model ? `${model.provider}/${model.id}` : "(none)"}`,
        `api: ${model?.api ?? "(none)"}`,
        "xAI Live Search: retired (search_parameters returns 410)",
        active
          ? "xAI server tools: ENABLED (Responses hosted web_search). Client web_search is removed to avoid collisions."
          : "inactive (need provider=xai)",
      ];
      ctx.ui.notify(lines.join("\n"), active ? "info" : "warning");
    },
  });
}
