// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Inject OpenAI server-side web_search into openai-responses requests.
// Docs: https://platform.openai.com/docs/guides/tools-web-search
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

// Server-side "hosted" tool shipped by OpenAI for the Responses API. Using it means
// the search executes on OpenAI's servers instead of a client tool with the same name.
const OPENAI_WEB_SEARCH_TOOL = {
  type: "web_search",
} as const;

type ResponsesPayload = {
  model?: string;
  input?: unknown;
  tools?: unknown[];
  [key: string]: unknown;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isOpenAIResponsesModel(model: { provider?: string; api?: string } | undefined): boolean {
  if (!model) return false;
  const provider = (model.provider || "").toLowerCase();
  if (provider !== "openai") return false;
  return model.api === "openai-responses";
}

function isOpenAIResponsesRequest(
  model: { provider?: string; api?: string } | undefined,
  payload: unknown,
): payload is ResponsesPayload {
  if (!isOpenAIResponsesModel(model)) return false;
  if (!isRecord(payload)) return false;
  // Responses API uses `input`; Chat Completions uses `messages`.
  return Array.isArray(payload.input);
}

function isWebSearchTool(tool: Record<string, unknown>): boolean {
  const type = typeof tool.type === "string" ? tool.type : "";
  const name = typeof tool.name === "string" ? tool.name : "";
  return type === "web_search" || name === "web_search";
}

function mergeServerTools(existing: unknown): unknown[] {
  const current = Array.isArray(existing) ? [...existing] : [];
  // Drop client/custom tools named/web_search typed web_search so they don't collide with
  // the OpenAI server tool (same name, different execution path). Keep every other tool.
  const filtered = current.filter((tool) => {
    if (!isRecord(tool)) return true;
    return !isWebSearchTool(tool);
  });

  const hasServer = filtered.some((tool) => isRecord(tool) && isWebSearchTool(tool));
  if (!hasServer) {
    filtered.push({ ...OPENAI_WEB_SEARCH_TOOL });
  }
  return filtered;
}

export default function (pi: ExtensionAPI) {
  pi.on("before_provider_request", (event, ctx) => {
    const model = ctx.model;
    if (!isOpenAIResponsesRequest(model, event.payload)) {
      return;
    }

    const payload = event.payload as ResponsesPayload;
    const next: ResponsesPayload = {
      ...payload,
      tools: mergeServerTools(payload.tools),
    };
    // Official Responses create params include parallel_tool_calls (openai-python
    // ResponseCreateParams). Honor an explicit false; otherwise enable.
    if (payload.parallel_tool_calls !== false) {
      next.parallel_tool_calls = true;
    }
    return next;
  });

  pi.on("before_agent_start", (event, ctx) => {
    const model = ctx.model;
    if (!isOpenAIResponsesModel(model)) {
      return;
    }

    const tip = [
      "",
      "## OpenAI server tools",
      "When the active model is official OpenAI (`openai` / openai-responses), this server-side tool is enabled on every request:",
      "- `web_search` — live web search (prefer over bash/curl for research)",
      "It executes on OpenAI servers automatically. Keep using local `read`/`bash`/`edit`/`write` for the workspace.",
    ].join("\n");

    if (event.systemPrompt.includes("## OpenAI server tools")) {
      return;
    }
    return {
      systemPrompt: `${event.systemPrompt}${tip}`,
    };
  });

  pi.registerCommand("openai-tools", {
    description: "Show whether OpenAI hosted web_search is active",
    handler: async (_args, ctx) => {
      const model = ctx.model;
      const active = isOpenAIResponsesModel(model);
      const lines = [
        `model: ${model ? `${model.provider}/${model.id}` : "(none)"}`,
        `api: ${model?.api ?? "(none)"}`,
        `OpenAI server tools: ${active ? "ENABLED (web_search)" : "inactive (need openai + openai-responses)"}`,
      ];
      ctx.ui.notify(lines.join("\n"), active ? "info" : "warning");
    },
  });
}
