// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
// Inject OpenAI/ChatGPT Codex hosted web_search into openai-codex-responses requests.
// Upstream: https://chatgpt.com/backend-api/codex/responses
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const CODEX_SERVER_TOOLS = [{ type: "web_search" }] as const;

type ResponsesPayload = {
  model?: string;
  input?: unknown;
  tools?: unknown[];
  [key: string]: unknown;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isOpenAICodexResponsesRequest(
  model: { provider?: string; api?: string } | undefined,
  payload: unknown,
): payload is ResponsesPayload {
  if (!model) return false;
  const provider = (model.provider || "").toLowerCase();
  if (provider !== "openai-codex" && !provider.includes("openai-codex")) return false;
  if (model.api !== "openai-codex-responses") return false;
  if (!isRecord(payload)) return false;
  // Responses API uses `input`; Chat Completions uses `messages`.
  return Array.isArray(payload.input);
}

function mergeServerTools(existing: unknown): unknown[] {
  const current = Array.isArray(existing) ? [...existing] : [];
  const present = new Set(
    current
      .filter(isRecord)
      .map((tool) => (typeof tool.type === "string" ? tool.type : undefined))
      .filter((type): type is string => Boolean(type)),
  );

  const merged = [...current];
  for (const tool of CODEX_SERVER_TOOLS) {
    if (!present.has(tool.type)) {
      merged.push({ ...tool });
    }
  }
  return merged;
}

function isCodexResponsesModel(model: { provider?: string; api?: string } | undefined): boolean {
  if (!model) return false;
  const provider = (model.provider || "").toLowerCase();
  if (provider !== "openai-codex" && !provider.includes("openai-codex")) return false;
  return model.api === "openai-codex-responses";
}

export default function (pi: ExtensionAPI) {
  pi.on("before_provider_request", (event, ctx) => {
    const model = ctx.model;
    if (!isOpenAICodexResponsesRequest(model, event.payload)) {
      return;
    }

    const payload = event.payload as ResponsesPayload;
    return {
      ...payload,
      tools: mergeServerTools(payload.tools),
    };
  });

  // Tell the model the hosted tool is available alongside Pi's local tools.
  pi.on("before_agent_start", (event, ctx) => {
    const model = ctx.model;
    if (!isCodexResponsesModel(model)) {
      return;
    }

    const tip = [
      "",
      "## Codex server tools",
      "When the active model is official ChatGPT Codex (`openai-codex` / openai-codex-responses), this server-side tool is enabled on every request:",
      "- `web_search` — live web search (prefer over bash/curl for research)",
      "It executes on OpenAI/ChatGPT servers automatically. Keep using local `read`/`bash`/`edit`/`write` for the workspace.",
    ].join("\n");

    if (event.systemPrompt.includes("## Codex server tools")) {
      return;
    }
    return {
      systemPrompt: `${event.systemPrompt}${tip}`,
    };
  });

  pi.registerCommand("codex-tools", {
    description: "Show whether Codex hosted web_search is active",
    handler: async (_args, ctx) => {
      const model = ctx.model;
      const active = isCodexResponsesModel(model);
      const lines = [
        `model: ${model ? `${model.provider}/${model.id}` : "(none)"}`,
        `api: ${model?.api ?? "(none)"}`,
        `Codex server tools: ${active ? "ENABLED (web_search)" : "inactive (need openai-codex + openai-codex-responses)"}`,
      ];
      ctx.ui.notify(lines.join("\n"), active ? "info" : "warning");
    },
  });
}