// Auto-generated by Pipi UI — do not edit (overwritten on every app launch).
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

export default function (pi: ExtensionAPI) {
  pi.registerCommand("pipiui_reload", {
    description: "Reload extensions, skills, prompts, themes, and context files (PipiUI internal)",
    handler: async (_args, ctx) => {
      await ctx.reload();
      ctx.ui.notify("Reloaded extensions, skills, prompts, and context files", "info");
    },
  });
}