import { afterEach, describe, expect, it } from "vitest";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";
import { createPiHostBackend } from "../src/index.js";

describe("configured models",()=>{let root="";afterEach(async()=>{if(root)await rm(root,{recursive:true,force:true})});it("loads available models and default state without resuming a session",async()=>{root=await mkdtemp(join(tmpdir(),"pipi-models-"));const agent=join(root,"agent");await mkdir(agent,{recursive:true});await writeFile(join(agent,"settings.json"),JSON.stringify({defaultProvider:"relay",defaultModel:"fast",defaultThinkingLevel:"high"}));await writeFile(join(agent,"models.json"),JSON.stringify({providers:{relay:{apiKey:"$RELAY_KEY",models:[{id:"fast",name:"Fast",reasoning:true},{id:"cheap",name:"Cheap",reasoning:false}]},disabled:{apiKey:"",models:[{id:"hidden",name:"Hidden",reasoning:true}]}}}));const backend=createPiHostBackend({agentDir:agent,env:{RELAY_KEY:"present"},authRuntime:{getProviders:async()=>[],getAvailable:async()=>[],login:async()=>undefined,logout:async()=>undefined}});expect(await backend.handle("listModels",[])).toEqual([{provider:"relay",id:"fast",name:"Fast",reasoning:true,thinkingConfigurable:true,supportsImages:true},{provider:"relay",id:"cheap",name:"Cheap",reasoning:false,thinkingConfigurable:false,supportsImages:true}]);expect(await backend.handle("getModelState",[])).toMatchObject({model:{provider:"relay",id:"fast"},thinkingLevel:"high"});});});

describe("session-scoped model state",()=>{let root="";afterEach(async()=>{if(root)await rm(root,{recursive:true,force:true})});it("applies the configured model and thinking level before the first prompt",async()=>{root=await mkdtemp(join(tmpdir(),"pipi-session-model-"));const agent=join(root,"agent");const cwd=join(root,"project");const dir=join(root,"sessions","project");await mkdir(agent,{recursive:true});await mkdir(cwd,{recursive:true});await mkdir(dir,{recursive:true});await writeFile(join(agent,"settings.json"),JSON.stringify({defaultProvider:"relay",defaultModel:"fast",defaultThinkingLevel:"high"}));await writeFile(join(agent,"models.json"),JSON.stringify({providers:{relay:{apiKey:"$RELAY_KEY",models:[{id:"fast",name:"Fast",reasoning:true},{id:"cheap",name:"Cheap",reasoning:true}]}}}));await writeFile(join(dir,"session.jsonl"),JSON.stringify({type:"session",version:3,id:"session-1",timestamp:"2026-08-10T00:00:00.000Z",cwd})+"\n");const backend=createPiHostBackend({agentDir:agent,sessionsRoot:join(root,"sessions"),runtimeRoot:join(root,"runtime"),env:{RELAY_KEY:"present"},piPath:"node",spawn:(_bin,_args,options)=>spawn("/usr/local/bin/node",[new URL("./fake-pi.mjs",import.meta.url).pathname],{...options,env:{...options.env,PATH:"/usr/local/bin:/usr/bin:/bin"}}) as any,authRuntime:{getProviders:async()=>[],getAvailable:async()=>[],login:async()=>undefined,logout:async()=>undefined}});await backend.handle("sendPrompt",["session-1","hello"]);expect(await backend.handle("getModelState",["session-1"])).toMatchObject({model:{provider:"relay",id:"fast"},thinkingLevel:"high"});await backend.close();});

it("targets model and thinking changes to the requested session",async()=>{root=await mkdtemp(join(tmpdir(),"pipi-session-scope-"));const agent=join(root,"agent");const cwd=join(root,"project");const dir=join(root,"sessions","project");await mkdir(agent,{recursive:true});await mkdir(cwd,{recursive:true});await mkdir(dir,{recursive:true});await writeFile(join(agent,"settings.json"),JSON.stringify({defaultProvider:"fake",defaultModel:"fake-1",defaultThinkingLevel:"medium"}));await writeFile(join(agent,"models.json"),JSON.stringify({providers:{fake:{apiKey:"$FAKE_KEY",models:[{id:"fake-1",name:"Fake",reasoning:true}]}}}));for(const id of ["session-1","session-2"])await writeFile(join(dir,`${id}.jsonl`),JSON.stringify({type:"session",version:3,id,timestamp:"2026-08-10T00:00:00.000Z",cwd})+"\n");const backend=createPiHostBackend({agentDir:agent,sessionsRoot:join(root,"sessions"),runtimeRoot:join(root,"runtime"),env:{FAKE_KEY:"present"},piPath:"node",spawn:(_bin,_args,options)=>spawn("/usr/local/bin/node",[new URL("./fake-pi.mjs",import.meta.url).pathname],{...options,env:{...options.env,PATH:"/usr/local/bin:/usr/bin:/bin"}}) as any,authRuntime:{getProviders:async()=>[],getAvailable:async()=>[],login:async()=>undefined,logout:async()=>undefined}});await backend.handle("getModelState",["session-1"]);await backend.handle("getModelState",["session-2"]);await backend.handle("setModel",["session-2","other","model-2"]);await backend.handle("setThinkingLevel",["session-2","high"]);expect(await backend.handle("getModelState",["session-1"])).toMatchObject({model:{provider:"fake",id:"fake-1"},thinkingLevel:"medium"});expect(await backend.handle("getModelState",["session-2"])).toMatchObject({model:{provider:"other",id:"model-2"},thinkingLevel:"high"});await backend.close();});});
