import { afterEach, describe, expect, it } from "vitest";
import { mkdtemp, mkdir, readFile, rm, writeFile, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";
import { createPiHostBackend } from "../src/index.js";

describe("model visibility persistence",()=>{let root="";afterEach(async()=>{if(root)await rm(root,{recursive:true,force:true})});it("returns [] for a missing file, round-trips explicit acknowledgements, and rejects invalid data",async()=>{root=await mkdtemp(join(tmpdir(),"pipi-vis-"));const agent=join(root,"agent");await mkdir(agent,{recursive:true});const backend=createPiHostBackend({agentDir:agent});expect(await backend.handle("getHiddenModelIds",[])).toEqual([]);const saved=await backend.handle("setHiddenModelIds",[["openai/gpt-5","anthropic/claude-sonnet-4","openai/gpt-5"]]);expect(saved).toEqual(["anthropic/claude-sonnet-4","openai/gpt-5"]);expect(await backend.handle("getHiddenModelIds",[])).toEqual(["anthropic/claude-sonnet-4","openai/gpt-5"]);const onDisk=JSON.parse(await readFile(join(agent,"pipiui-settings.json"),"utf8"));expect(onDisk).toEqual({hiddenModelIds:["anthropic/claude-sonnet-4","openai/gpt-5"]});const leftovers=(await readdir(agent)).filter(name=>name.includes(".tmp-"));expect(leftovers).toEqual([]);const fresh=createPiHostBackend({agentDir:agent});expect(await fresh.handle("getHiddenModelIds",[])).toEqual(["anthropic/claude-sonnet-4","openai/gpt-5"]);await expect(fresh.handle("setHiddenModelIds",[undefined])).rejects.toThrow("hiddenModelIds 必须是 string[]");const invalidAgent=join(root,"invalid-agent");await mkdir(invalidAgent,{recursive:true});await writeFile(join(invalidAgent,"pipiui-settings.json"),JSON.stringify({hiddenModelIds:["openai/gpt-5",42]}));await expect(createPiHostBackend({agentDir:invalidAgent}).handle("getHiddenModelIds",[])).rejects.toThrow("hiddenModelIds 必须是 string[]");});});

describe("semantic sidebar preference persistence",()=>{let root="";afterEach(async()=>{if(root)await rm(root,{recursive:true,force:true})});it("atomically merges into pipiui-settings without clobbering model fields",async()=>{root=await mkdtemp(join(tmpdir(),"pipi-sidebar-pref-"));const agent=join(root,"agent");await mkdir(agent,{recursive:true});await writeFile(join(agent,"pipiui-settings.json"),JSON.stringify({hiddenModelIds:["openai/gpt-5"],subagentModels:{worker:[{model:"gpt-5"}]}}));const backend=createPiHostBackend({agentDir:agent});expect(await backend.handle("getSidebarSessionPreferences",[])).toEqual({pinnedSessionIds:[],archivedSessionIds:[]});expect(await backend.handle("setSidebarSessionPreferences",[{pinnedSessionIds:["s1","s2","s1"],archivedSessionIds:["s2","s3"]}])).toEqual({pinnedSessionIds:["s1"],archivedSessionIds:["s2","s3"]});const saved=JSON.parse(await readFile(join(agent,"pipiui-settings.json"),"utf8"));expect(saved).toMatchObject({hiddenModelIds:["openai/gpt-5"],subagentModels:{worker:[{model:"gpt-5"}]},sidebarSessionPreferences:{pinnedSessionIds:["s1"],archivedSessionIds:["s2","s3"]}});expect((await readdir(agent)).filter(name=>name.includes(".tmp-"))).toEqual([]);await expect(backend.handle("setSidebarSessionPreferences",[{pinnedSessionIds:[1],archivedSessionIds:[]}])).rejects.toThrow("pinnedSessionIds");});});

describe("configured model image capability",()=>{let root="";afterEach(async()=>{if(root)await rm(root,{recursive:true,force:true})});it("marks deepseek as non-vision via the Swift heuristic and others as vision-capable",async()=>{root=await mkdtemp(join(tmpdir(),"pipi-vision-"));const agent=join(root,"agent");await mkdir(agent,{recursive:true});await writeFile(join(agent,"models.json"),JSON.stringify({providers:{deepseek:{apiKey:"k",models:[{id:"deepseek-v3",reasoning:true}]},openai:{apiKey:"k",models:[{id:"gpt-4o",reasoning:true}]},custom:{apiKey:"k",models:[{id:"vision-model",input:["image","text"],reasoning:true}]}}}));const backend=createPiHostBackend({agentDir:agent});const models:any[]=await backend.handle("listModels",[]);expect(models.find(m=>m.id==="deepseek-v3")).toMatchObject({supportsImages:false});expect(models.find(m=>m.id==="gpt-4o")).toMatchObject({supportsImages:true});expect(models.find(m=>m.id==="vision-model")).toMatchObject({supportsImages:true});});});

describe("prompt image attachments",()=>{let root="";afterEach(async()=>{if(root)await rm(root,{recursive:true,force:true})});it("writes attachments under <cwd>/.pi/attachments and sends the images RPC field",async()=>{root=await mkdtemp(join(tmpdir(),"pipi-img-"));const cwd=join(root,"project");const dir=join(root,"sessions","project");await mkdir(dir,{recursive:true});await mkdir(cwd,{recursive:true});const path=join(dir,"session.jsonl");await writeFile(path,JSON.stringify({type:"session",version:3,id:"session-1",timestamp:"2026-08-10T00:00:00.000Z",cwd})+"\n");const backend=createPiHostBackend({sessionsRoot:join(root,"sessions"),runtimeRoot:join(root,"runtime"),piPath:"node",spawn:(_bin,_args,options)=>spawn("/usr/local/bin/node",[new URL("./fake-pi.mjs",import.meta.url).pathname],{...options,env:{...options.env,PATH:"/usr/local/bin:/usr/bin:/bin"}}) as any});const logs:any[]=[];const off=backend.subscribe(e=>{if(e.channel==="agents"&&e.event.type==="agent_log"&&e.event.agentId==="agent-images")logs.push(e.event.text)});const attachment={dataBase64:Buffer.from("PNGDATA").toString("base64"),mimeType:"image/png",name:"shot.png"};await backend.handle("sendPrompt",["session-1","看图",[attachment]]);await new Promise(r=>setTimeout(r,20));off();expect(logs.some(text=>text.includes("IMAGES=")&&text.includes("\"type\":\"image\"")&&text.includes(attachment.dataBase64)&&text.includes("image/png"))).toBe(true);const written=await readFile(join(cwd,".pi","attachments","shot.png"),"utf8");expect(written).toBe("PNGDATA");});});
